### ISSUE TITLE
Add documentation for configuration

### ISSUE THREAD

**Issue by Ameobea** [facebook/pyre-check#10]
I looked through the website and in the repo, but I didn't find a list of configuration options for the `.pyre_configuration` directory.  The getting started guide mentions setting some config settings after running `pyre init`, but I can't see to find anything other than that.

**Comment by dkgi** [comment]
Unfortunately the documentation is not quite there yet. @shannonzhu is currently working on documenting the configuration. We'll keep you posted :)

**Comment by Ameobea** [comment]
Awesome; thanks for the cool tool!

**Comment by dkgi** [comment]
Configuration can be found here: https://pyre-check.org/docs/configuration.html
Let us know if we missed something :)

**Comment by rpgoldman** [comment]
@dkgi It would be helpful if you could explain how search path could be initialized in the pyre configuration file.  I am using it successfully as a command line option (`--search-path`) but haven't figured out its use in the configuration file.  In particular, what data type is a `SEARCH_PATH`?  A pathname? a list of pathnames?  Thanks!

**Comment by dark** [comment]
@rpgoldman 
`search_path` is a list of pathnames:
```
{                                                  
  "search_path" : ["/some/directory", "/some/other/directory"]                                  
}
```

**Comment by rpgoldman** [comment]
For some reason that isn't working for me.  When I try to use the following configuration file, pyre does not see the stubs I have put in `/Users/rpg/projects/xplan/yeast-gates-data/stubs/`, but when I pass that directory using `--search-path`, it does.  Any idea why not?  Could the `autogenerated` configuration option interfere with `search-path`?
```
$ cat .pyre_configuration 
{
  "binary": "/Users/rpg/Library/Python/3.7/bin/pyre.bin",
  "source_directories": [
    "."
  ],
  "typeshed": "/Users/rpg/Library/Python/3.7/lib/pyre_check/typeshed/",
  "autogenerated": ["/Users/rpg/projects/xplan/yeast-gates-data/Charts/",
                    "/Users/rpg/projects/xplan/yeast-gates-data/Model2.0/",
                    "/Users/rpg/projects/xplan/yeast-gates-data/Models/",
                    "/Users/rpg/projects/xplan/yeast-gates-data/.mypy_cache/",
                    "/Users/rpg/projects/xplan/yeast-gates-dataprior/",
                    "/Users/rpg/projects/xplan/yeast-gates-data/pymc3-data/",
                    "/Users/rpg/projects/xplan/yeast-gates-data/stubs/"],
   "search-path": ["/Users/rpg/projects/xplan/yeast-gates-data/stubs/"]
}rpg@RPG-MacBook-Pro: ~/projects/xplan/yeast-gates-data $ ls /Users/rpg/projects/xplan/yeast-gates-data/stubs/
FlowCytometryTools/  numpy@  pymc3@
```

**Comment by dark** [comment]
The config item is `search_path` not `search-path` :)

**Comment by rpgoldman** [comment]
Thanks! As a long-time lisp user (Emacs and Common), that is not a surprising mistake for me to make. But the command-line option works with the hyphen instead of an underscore: you might want to remark on this in the configuration docs.

**Comment by dark** [comment]
It's a mistake that happens more often than you'd expect :) 4d0e7976f22c7e6161d3d4f9f0e79509e7e7e14f added some code to warn when a configuration item is not recognized, but we haven't published a new release since. Maybe it's time I push that button.
