### ISSUE TITLE
Undefined attribute [16]: Module `celery` has no attribute `Celery`.

### ISSUE THREAD

**Issue by lambdabaa** [facebook/pyre-check#110]
Possibly related to their usage of `__all__` in https://github.com/celery/celery/blob/master/celery/app/__init__.py#L14.

**Comment by dark** [comment]
The reason for the failure here is actually a bit different.
The celery sources are not annotated, and the project does not provide stub files. Hence, Pyre does not know anything about the types of the `celery` module.

We will improve the wording of the error a little bit, but unfortunately there's not much else we can do here. The developers of `celery` need to add types to their codebase for Pyre to work.
Closing.
