### ISSUE TITLE
Invalid result on a simple program

### ISSUE THREAD

**Issue by llimllib** [facebook/pyre-check#12]
Here's a program that throws a type error when there is not one (AFAICS?):

```python
import boto3


def bug() -> str:
    boto3
    return "bananas"
```

Throws:

```
$ pyre restart
 ƛ No server running
 ƛ Server not running at `.`. Starting...
 ƛ Server initializing...
 ƛ No servers running
 ƛ Found 1 type error!
bug.py:5:4 Undefined name [18]: Global name `boto3` is undefined.
```

`boto3` is clearly not undefined.

**Comment by dkgi** [comment]
@llimllib: thanks for trying out Pyre :)

The error you're getting means that Pyre does not know about `boto3`. Pyre has various ways of knowing about third-party libraries. A lot of them are defined in typeshed, which is shipped with Pyre itself. Apart from that you can tell Pyre where to look for them, e.g. by adding 

```
"search_path": ["where/to/find/additional/python/files/or/stubs"],
```

to your `.pyre_configuration`. You can also pass this with `--search-path` or tell python to use your current `$PYTHONPATH` during the lookup (with `--preserve-pythonpath`).

Unfortunately, all of those options are currently not very well documented, see also https://github.com/facebook/pyre-check/issues/10

**Comment by llimllib** [comment]
Ah! thanks for the quick response, I guess I'm surprised that a type checker is concerned about whether boto3 actually exists or not.

Anyway, here's a vote for making `--preserve-pythonpath` the default, who would not want that on?

**Comment by llimllib** [comment]
Maybe the default if there is no config file? Anyway, I found the error very confusing so I suspect others new to the project will too.

Thanks for your hard work on the tool, I’m using it because im excited for it.

**Comment by JelleZijlstra** [comment]
Would it make more sense to have unimported modules default to evaluating to `Any`? That's the behavior I usually choose with mypy (`--follow-imports=silent` is the relevant option I believe), and I think that's generally the sensible behavior if you're using libraries that don't have stubs available.
