### ISSUE TITLE
Working in pipenv?

### ISSUE THREAD

**Issue by sztomi** [facebook/pyre-check#121]
I encountered the problem described here: https://github.com/facebook/pyre-check/issues/64

I found that it's fairly easy to fix:

```
$ pyre --search-path=$(pipenv --venv)/lib/python3.7/site-packages check
```

I'm guessing this is something that pyre might be able to do automatically/transparently. Is this something I could set in the configuration (without having to commit the absolute path to my virtualenv, which is specific to my environment)?

**Comment by dkgi** [comment]
Hi @sztomi. Thanks for the report.

I guess we could do something similar we do for the binary location but for search paths: https://github.com/facebook/pyre-check/blob/master/client/configuration.py#L356

Happy to look at pull requests for this.

**Comment by dark** [comment]
This was closed automatically via the commit above; if you are using pyre from master please let us know if this works, otherwise it will be available in the next release.
