### ISSUE TITLE
pyre still not processing local do_not_check paths

### ISSUE THREAD

**Issue by rpgoldman** [facebook/pyre-check#122]
I am running pyre 0.0.16, which I believe should have this fixed, according to previous issue #92 
I'm on MacOS (High Sierra, not Mojave) with python 3.6.5

I am trying to have pyre ignore the `lib/` directory that was installed by `virtualenv`.  I have a local `.pyre_configuration`.  Here are its contents:
```
{
  "analysis_directories": [
    "."
  ],
  "binary": "/Users/rpg/projects/xplan/xplan-experiment-analysis/bin/pyre.bin",
  "typeshed": "/Users/rpg/projects/xplan/xplan-experiment-analysis/lib/pyre_check/typeshed/",
  "search_path": [ "stubs" ],
  "do_not_check": [ "stubs", "bin", "lib" ]
}
```
But when I run `pyre  --show-parse-errors check`, I see the following:
```
 ƛ Could not parse file at lib/python3.6/site-packages/pandas/core/arrays/base.py:204:0-204:0
          # type: () -> int
  ^
 ƛ Could not parse file at lib/python3.6/site-packages/ipykernel/kernelapp.py:421:28-421:28
                         file=sys.stderr)
                             ^
 ƛ Could not parse file at lib/python3.6/site-packages/scipy/stats/_continuous_distns.py:1:0-1:0
  ﻿#
  ^
 ƛ Could not parse file at lib/python3.6/site-packages/pandas/core/base.py:798:0-798:0
          # type: () -> np.ndarray
  ^
 ƛ Could not parse file at lib/python3.6/site-packages/xarray/core/computation.py:162:0-162:0
      # type: (...) -> List[OrderedDict[Any, Variable]]
  ^
 ƛ Could not parse file at lib/python3.6/site-packages/mypy/typeshed/tests/check_consistent.py:37:43-37:43
      for file1, *others in consistent_files:
                                            ^
 ƛ Could not parse file at lib/python3.6/site-packages/jedi/_compatibility.py:368:16-368:16
          print >> sys.stderr, args
                 ^
 ƛ Could not parse file at lib/python3.6/site-packages/arviz/plots/forestplot.py:460:51-460:51
          end_y = max(y for y, *_ in self.iterator())
                                                    ^
 ƛ Could not parse file at lib/python3.6/site-packages/arviz/data/io_cmdstan.py:181:48-181:48
                  for sample, *_ in parsed_output:
```
I read the text of #94 and the referenced changeset bd0f410 (I didn't fully understand the explanation -- whether all the pathnames were coerced to absolute, or whether they had to be absolute in the configuration file).  So I modified the configuration file to have this:
```
  "do_not_check": [ "stubs", "bin", "/Users/rpg/projects/xplan/xplan-experiment-analysis/lib" ]
```
But that line does not prevent pyre from generating the same parse errors on files in the `lib/` subdirectory.

I put a break point at the bottom of the `__init__` method for `Configuration`, and I can see that my entries *are* there:
```
(Pdb) for x in self.do_not_check: print(x)
/Users/rpg/projects/xplan/yeast-gates-data/stubs
/Users/rpg/projects/xplan/xplan-experiment-analysis/bin
/Users/rpg/projects/xplan/xplan-experiment-analysis/lib
```
Then I worried that I might need trailing `/` for directory names.  But adding that did not fix the problem, either.  Finally, I tried the absolute pathname for the directory with the trailing slash.  Still the same problem.
The only thing I can think of is an issue in the `fnmatch.fnmatch` function or the way paths are being checked.
BTW, do I understand correctly that `do_not_check` only causes errors corresponding to DNC files to go unreported, instead of actually preventing `pyre` from processing the files?  That's what it looks like because the `do_not_check` processing seems to be in `commands/reporting.py`.

**Comment by dark** [comment]
> BTW, do I understand correctly that do_not_check only causes errors corresponding to DNC files to go unreported, instead of actually preventing pyre from processing the files? That's what it looks like because the do_not_check processing seems to be in commands/reporting.py.

That is correct.
All files under "source_directories" and "search_path" are always parsed fully. Only error reporting is skipped.
Please see #81 for a similar question that was asked some time ago.

(unrelated, but I noticed it anyway :) )
We have silently deprecated "analysis_directories" as part of #112 in `0.0.17`, please replace that with "source_directories" in your config file.

**Comment by rpgoldman** [comment]
I guess I'm not sure why this decision was made.  Maybe it's because your use case is different from mine.  My use case is exploratory data analysis and involves the use of virtual environments.
Because of virtual environments, it really is not helpful to me to have `pyre` complain about the files in my `lib` directories, and that includes its parser not liking what's in there.  Note that this is actually a fatal error for me -- `pyre check` crashes with error code -11 because of the parsing errors.
```
2018-11-20 09:59:40,051 DEBUG No configuration found at `.pyre_configuration.local`.
2018-11-20 09:59:40,052 DEBUG Reading configuration `.pyre_configuration`...
2018-11-20 09:59:40,052 DEBUG Found analysis_directories: `.`
2018-11-20 09:59:40,177 DEBUG Running `/Users/rpg/projects/xplan/xplan-experiment-analysis/bin/pyre.bin check -project-root /Users/rpg/projects/xplan/xplan-experiment-analysis -filter-directories . -workers 8 -typeshed /Users/rpg/projects/xplan/xplan-experiment-analysis/lib/pyre_check/typeshed/ -search-path stubs /Users/rpg/projects/xplan/xplan-experiment-analysis`
2018-11-20 09:59:40,372 INFO Finding type stubs in `/Users/rpg/projects/xplan/xplan-experiment-analysis`...
2018-11-20 09:59:40,492 INFO Finding type stubs in `/Users/rpg/projects/xplan/yeast-gates-data/stubs`...
2018-11-20 09:59:40,498 INFO Finding type stubs in `/Users/rpg/projects/xplan/xplan-experiment-analysis/lib/pyre_check/typeshed/stdlib`...
2018-11-20 09:59:40,503 INFO Finding type stubs in `/Users/rpg/projects/xplan/xplan-experiment-analysis/lib/pyre_check/typeshed/third_party`...
2018-11-20 09:59:40,534 INFO Finding external sources in `/Users/rpg/projects/xplan/yeast-gates-data/stubs`...
2018-11-20 09:59:40,635 INFO Parsing 2884 stubs and external sources...
2018-11-20 09:59:41,912 PERFORMANCE Stubs parsed: 1.546440s
2018-11-20 09:59:42,252 INFO Parsing 5419 sources in `/Users/rpg/projects/xplan/xplan-experiment-analysis`...
2018-11-20 09:59:52,372 WARNING Could not parse 9 files due to syntax errors! Run with `--show-parse-errors` for more details.

2018-11-20 09:59:52,475 PERFORMANCE Sources parsed: 10.405333s
2018-11-20 09:59:53,307 PERFORMANCE Registered ignores: 0.935105s
2018-11-20 09:59:53,410 INFO Building type environment...
2018-11-20 10:00:03,649 ERROR Client exited with error code -11
```

**Comment by rpgoldman** [comment]
The above was from the log.  I'm not sure how to get a backtrace from the pyre error.  I tried `--show-error-traces` but perhaps that's for type errors rather than pyre errors?  Is there a way to get a more informative error trace?

**Comment by rpgoldman** [comment]
WRT the console, I am using just the standard Mac OS terminal program, not qtconsole (I take it that's some sort of KDE thing?).
Looking at #119 it looks like I should be trying to run `pyre.bin`.  I'll try to do that and get back to you.
I still think finer-grained control over what pyre does and doesn't see would be helpful. I am really not sure why the number of files it reports is so high.
I suppose I could make a directory full of symlinks as a way of working around this but... yuck.  It would be a lot nicer if I could really hide files from pyre, instead of just squelching their error messages.

**Comment by rpgoldman** [comment]
See my issue #124 for the segmentation fault.
As I mention there, pyre is checking all the files in my virtualenv, which seems to account for the very high line count.
Since some of those are libraries for which I have added type stubs, does that create any potential for confusion?

**Comment by dark** [comment]
Support for this feature has been added in master, it will appear in the next release (we have not scheduled a date for it yet).
