### ISSUE TITLE
Unexpected output: 0-based offset for column and 1-based offset for row

### ISSUE THREAD

**Issue by atb00ker** [facebook/pyre-check#126]
**Please consider:**
```
def foo() -> int:
    return 'string'
```

**Output received:**
```
test.py:2:4 Incompatible ... 
```

**Expected output:**
```
test.py:2:5 Incompatible ...
```

From the ouptut it seems like pyre is using 0-based offset for column and 1-based offset for row.
Can you please confirm if it is a 0-based offset or am i messing up the setup?
Thanks

**Comment by atb00ker** [comment]
Appologies for disturbing the issues channel, however, it seems there are no other channels linked in the documentation, if this is noise, please help me to find the correct channel.
Thank You.

**Comment by dark** [comment]
@atb00ker That is correct. Pyre starts a file at row 1, column 0.

**Comment by atb00ker** [comment]
Thank you for the information.

**Comment by dark** [comment]
No problem, feel free to reopen this issue if you have a follow-up.
