### ISSUE TITLE
Parse errors in Django and Celery

### ISSUE THREAD

**Issue by stebunovd** [facebook/pyre-check#131]
Hi there,

I was testing `pyre v0.0.18` with my project which uses Django and Celery, and it was throwing parse  errors on the following files:

```sh
$ pyre --show-parse-errors check
 ƛ Could not parse file at django/forms/forms.py:347:65-347:65
              error = {field or NON_FIELD_ERRORS: error.error_list}
                                                                  ^
 ƛ Could not parse file at celery/utils/saferepr.py:211:0-211:0
      # type: (deque, Set, int, int, Callable) -> Iterator[Any]
  ^
```

links to sources: 

- https://github.com/django/django/blob/stable/2.1.x/django/forms/forms.py#L347
- https://github.com/celery/celery/blob/4.2/celery/utils/saferepr.py#L211

Does the parse error mean that pyre can't recognize these lines as a valid Python code?

**Comment by dark** [comment]
Hi @stebunovd,
that is correct, the Pyre parser rejects those files at the moment. As a consequence, the content of those files is unavailable to the type-checker.

We are constantly improving our parser to recognize more code, and we also accept patches to the parser if you'd like to contribute :)

**Comment by MaggieMoss** [comment]
@stebunovd thanks for reporting this issue! The fix will be out in the next release :)
