### ISSUE TITLE
for iterator value collection not supported

### ISSUE THREAD

**Issue by thehesiod** [facebook/pyre-check#137]
it's choking on this line in my code:
```python
for stationName, stationSubType, stationData, *rules in self._station_data_iterator():
    pass
```

in particular I believe the `*rules` that aggregates any untupled values

**Comment by MaggieMoss** [comment]
@thehesiod thanks for logging this issue! This is fixed with this commit [0d52a7a](https://github.com/facebook/pyre-check/commit/0d52a7a61b680ad2e1b9110ccd1106d0f1705b5f)
