### ISSUE TITLE
Only "Undefind import [21]" "Undefined name [18]" on Debian 9

### ISSUE THREAD

**Issue by overviolet** [facebook/pyre-check#138]
Only "Undefined import [21]: Could not find a module corresponding to import " and "Undefined name [18]" errors on Debian 9.
Meanwhile on ubuntu 16.04 much more inferences were found for the same code.

**Comment by dkgi** [comment]
@overviolet: can you provide a bit more context here? Which version of Pyre are you running, how are you running it and what code are you running it on? Thanks :)

**Comment by overviolet** [comment]
Hi. I tried to reproduce issue on synthetic example and found out that this is my mistake related to docker usage. So please accept my apologies. closed.)
