### ISSUE TITLE
Can we change setup.sh to only support opam 2?

### ISSUE THREAD

**Issue by KevinHock** [facebook/pyre-check#142]
#### Summary
[Library versions were recently pinned in `scripts/setup.sh`](https://github.com/facebook/pyre-check/commit/dafd76259d9a22dd07ab693bb90ca66da909f224), including [`dune.1.6.2`](https://opam.ocaml.org/packages/dune/dune.1.6.2/), in [opam versions before major version 2](https://opam.ocaml.org/blog/deprecating-opam-1-2-0/), this doesn't seem available.

#### Output
 `opam info dune` from opam version `1.2.2` outputs 
```
available-versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1
```
whereas with opam version `2.0.3` outputs
```
all-versions           1.0.0  1.0.1  1.1.0  1.1.1  1.2.0  1.2.1  1.3.0  1.4.0  1.5.0  1.5.1
                       1.6.0  1.6.1  1.6.2  1.6.3  1.7.0  1.7.1  1.7.2  1.7.3  1.8.0  1.8.1
                       1.8.2
```

The way I came across this problem:
After doing [`./scripts/setup.sh --local`](https://pyre-check.org/docs/installation.html#getting-the-source) I got
```
...
=-=- Updating package repositories =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
...
[ERROR] No package matches ppx_deriving_yojson.3.3.
[ERROR] No package matches yojson.1.5.0.
[ERROR] No package matches dune.1.6.2.
[ERROR] No package matches base64.3.1.0.
```

#### Questions

I can replace the `else` body of [the opam major version check](https://github.com/facebook/pyre-check/commit/ebdf56c4bceb230accd7867be7cbaea60d38f1e0) with something like "Please use opam 2", thoughts?

**Comment by grievejia** [comment]
Thanks for the investigation! I don't have a machine with opam1.2 to verify that but I do think that if `dune` has limited availability then what you propose sounds reasonable.

**Comment by sinancepel** [comment]
Closing, the 0.0.25 release should have this fixed.
