### ISSUE TITLE
Could not find a module corresponding to import `lxml.etree`

### ISSUE THREAD

**Issue by seahurt** [facebook/pyre-check#144]
It seems like lxml package is different from other module, it doesn't have etree.py in its installation dir. But my code just works when executed. 

Maybe you guys know how to solve this. 

Hear is the full stdout info:

```
 ƛ Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
 ƛ Found 2 type errors!
utils/mailmerge.py:4:0 Undefined import [21]: Could not find a module corresponding to import `lxml.etree`.
utils/mailmerge.py:5:0 Undefined import [21]: Could not find a module corresponding to import `lxml`.
```

sys info

```
MacOS 10.14.3

python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```

**Comment by Congee** [comment]
you should be able to find lxml.etree here https://github.com/JelleZijlstra/lxml-stubs
but we are still missing lxml.html :\

**Comment by JelleZijlstra** [comment]
Contributions to the lxml stubs are welcome. :)
