### ISSUE TITLE
Incremental mode does not work without `pywatchman`

### ISSUE THREAD

**Issue by aspin** [facebook/pyre-check#146]
Related to comments I posted in https://github.com/facebook/pyre-check/issues/20.

Short of it is that incremental mode fails silently from the user's perspective if the `pywatchman` package is not installed manually by the user. `pyre rage` indicates a general lack of any watchman related log messages, but if you dig into `.pyre/file_monitor/file_monitor.log`, you'll find messages like

```
2019-04-02 12:23:36,294 INFO Not starting file_monitor due to No module named 'pywatchman'
[0G[K ƛ[0m Not starting file_monitor due to No module named 'pywatchman'
```

easy fix for anyone else now:
`pip install pywatchman`

**Comment by sinancepel** [comment]
Thank you for your PR! Closing this issue since that ought to take care of it.
