### ISSUE TITLE
Add document that supports 3.6+ only at the moment?

### ISSUE THREAD

**Issue by hvnsweeting** [facebook/pyre-check#15]
Just so interested as the news pop up, I tried to install pyre-check immediately , but on the first run, it shows up a weird error on syntax error and after a while searching, I found out this only supports 3.6+ at the moment - when my version is 3.5.
Maybe should add one line or two on README that pyre only support 3.6+ for now? That would definitely helpful for newcomers.

Btw, I'm installing Python 3.6 to test it out,
Thanks for the great tool!

**Comment by dkgi** [comment]
Thanks for the feedback :) We're aware of the issue and are working on supporting Python 3.4+. Tracking this in https://github.com/facebook/pyre-check/issues/4.

**Comment by hvnsweeting** [comment]
Then I would suggest rename the existing issue

> error on centos 7.4 & 7.5 

 which is pretty misleading and make users open others issues
