### ISSUE TITLE
Common taint configs and stubs?

### ISSUE THREAD

**Issue by 1one-w01f** [facebook/pyre-check#152]
2 quick questions.

Was wondering if it would be possible to include some common taint configs and stubs in future releases, either in the `default` of `taint/configuration.ml` or as sample code in the documentation? This would make taint analysis more easily applicable to different software systems. `taint/configuration.ml` already contains some default rules.

Also, was wondering what do `features: []` do in the taint config shown in [https://pyre-check.org/docs/static-analysis.html](https://pyre-check.org/docs/static-analysis.html)?

**Comment by nwalsh1995** [comment]
I have created a repo https://github.com/nwalsh1995/pyre-security-configs that we can contribute to in order to enumerate all of the source/sinks as possible.

I don't mind maintaining this repo, but I think it best for Facebook to be the maintainer of these checks in the pyre-check repository.

**Comment by the-storm** [comment]
I think it is a good idea to maintain that. Let me check what we can do :)

**Comment by the-storm** [comment]
@fahndrich  can answer the question about features :)

**Comment by adrianbn** [comment]
I'd definitely like to see this maintained by pyre, even if on a different repository. I'm sure people would contribute sinks, sources, and sanitizers for the most popular frameworks in addition to the stdlib.

**Comment by fahndrich** [comment]
Features are little bits of information we attach to flows that can be used to filter the resulting issues. E.g., you could write a taint-in-taint-out model for a particular function and on that annotation add a feature: `TaintInTaintOut[Via[my-feature]]`

Any flow that goes through that particular place will have `my-feature` attached. Similarly, you can attach features to source and sink specifications in .pysa files.

**Comment by dkgi** [comment]
Started adding some of our stubs with e4eafb8817c74c1d83db9c1609878d2460591a01. More contributions welcome. Will close this out for now.
