### ISSUE TITLE
Incessant High CPU Usage

### ISSUE THREAD

**Issue by arjun-menon** [facebook/pyre-check#157]
Pyre is incessantly consuming 100% of one of my CPU cores. It's enough to cause my laptop fan to spin very loudly, and battery life to drop.

I only started using Pyre yesterday, with VS Code, for a _very small_ Python project. The 100% CPU usage never dropped, even after a few hours. I restarted Pyre a bunch of times, and the CPU usage hits 100% almost immediately after Pyre spins up.

Here are some (cropped) KSysGuard screenshots showing this:

![pyre-cpu-usage-1](https://user-images.githubusercontent.com/1961201/56874271-e80f8980-6a49-11e9-88b3-2b97ac704d0d.png)

The 13% above for `pyre.bin` is across all 8 cores. It's actually using 100% of one core. See below:

![pyre-cpu-usage-2](https://user-images.githubusercontent.com/1961201/56874280-fcec1d00-6a49-11e9-91ab-b7715b12e023.png)

It seems like the kernel is shuffling the `pyre.bin` to a different CPU core about every minute.

If there's any way I can provide additional diagnostics, do _let me know how_. (For example: using the debug/dev version of Pyre with verbose logging, pulling a specific branch of Pyre and running it, etc.)

**Comment by sinancepel** [comment]
@arjun-menon thanks for the report. I have a suspicion about what's happening here, and will test a fix and report back.

**Comment by sinancepel** [comment]
Verified that https://github.com/facebook/pyre-check/commit/194c364bd2933beb3905a3fc6eb14e9290978e91 fixes this issue - we will release 0.0.25 soon with this fix included. Thanks for the report! I'll close when the new version is released.

**Comment by sinancepel** [comment]
0.0.25 was released, recommend that you download it :)

**Comment by arjun-menon** [comment]
Confirmed. I installed 0.0.25, _**and this has been fixed**!_ Thank you!
