### ISSUE TITLE
Test `pyre` in Windows Subsystem for Linux

### ISSUE THREAD

**Issue by cooperlees** [facebook/pyre-check#162]
I feel there might be a chance that pyre.bin might run today in WSL or need very little work to run in Windows Subsystem for Linux
- https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

This could allow Windows support for the many Python windows users :)

**Comment by grievejia** [comment]
This might be interesting. None of us code on Windows so we have no idea what it is blocked on.

Unfortunately this week I'm traveling to PyCon and did not bring my Surface Pro with me. I can take a look after we get back from Cleveland.

**Comment by cooperlees** [comment]
I’m here at PyCon too. Let’s meet up. I’ll try install the services on a VM and see how far I get :)

**Comment by cooperlees** [comment]
Ok, so I got this working. I followed:
- https://docs.microsoft.com/en-us/windows/wsl/install-win10
To get WSL installed and then Ubuntu and I `apt get upgrade && apt get update`.

Once I had Ubuntu, I `cd /mnt/c/ && git clone https://github.com/facebookincubator/ptr.git`
- Then there were some deps I had to add, but I got `pyre` to run in a venv:
```bash
sudo apt install python3-venv build-essential python3-dev libpython3-dev
python3 -m venv /tmp/tp
/tmp/tp/bin/pip install --update pip setuptools wheel
/tmp/tp/bin/pip install pyre-check
source /tmp/tp/bin/activate
pyre --source-directory . check

(tp) cooper@TESTFAC-1FMHLI2:/mnt/c/temp/ptr$ pyre --source-directory . check
 ƛ Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
 ƛ No type errors found
```

Would you accept a PR adding this to your documentation somewhere?

**Comment by grievejia** [comment]
Good to know that `pyre` works under WSL, and thanks for the pointer! Yes a PR would definitely be nice :)
