### ISSUE TITLE
Committing config - avoiding hardcoded paths with user names

### ISSUE THREAD

**Issue by hawkins** [facebook/pyre-check#165]
I'm looking to use Pyre in a setting where developers work on the project on local workstations under different users, which means that paths to typeshed such as `"/home/hawkins/.local/lib/pyre_check/typeshed/"` are problematic for other developers, because they now have to replace `hawkins` with whatever their username may be.

I've tried replacing this fixed path with `"~/.local/lib/pyre_check/typeshed"`. `/home/$USER/.local/lib/pyre_check/typeshed/"`, but both fail saying they're invalid paths.

i.e.: 

```
 ƛ ~/.local/lib/pyre_check/typeshed/ is not a valid directory.
 ƛ $HOME/.local/lib/pyre_check/typeshed/ is not a valid directory.
 ƛ /home/$USER/.local/lib/pyre_check/typeshed/ is not a valid directory.
```

What's the idiomatic way to set up paths in a pyre_config to be committed to a project? Or is there some other pattern we should be following (unique non-committed pyre config files in our home dir, etc)?

**Comment by hawkins** [comment]
It seems like #52 almost hits on this, but that's more about ignoring generated folders than wildcard paths (which may apply to this issue?)

**Comment by dkgi** [comment]
@hawkins, we're reading the typeshed from the configuration here:

https://github.com/facebook/pyre-check/blob/master/client/configuration.py#L421

I'm not super familiar with the current logic there but I think it'd be reasonable to run `os.path.expanduser` on this. Happy to accept a pull request to that extent.

**Comment by hawkins** [comment]
Awesome, I'll put something together this evening to that effect then

**Comment by hawkins** [comment]
I've got a first pass open for it now at #166 , though it's a little rushed still
