### ISSUE TITLE
Use of `find` does not work on macOS

### ISSUE THREAD

**Issue by mgraczyk** [facebook/pyre-check#17]
In `pyre-check/scripts/filesystem.py`, the system`find` utility is run via the `subprocess` module:

 https://github.com/facebook/pyre-check/blob/71d5d5bbddd69b29b8f1f2eb80760ea6b33517fb/scripts/filesystem.py#L121

`find` is passed the `-regextype` argument, but the BSD `find` utility included with macOS does not understand this argument. The result is a slightly cryptic error:

```bash
$ pyre
 ƛ Shared source directory is stale, updating...find: -regextype: unknown primary or operator
 ƛ pyre was unable to locate a source directory. Ensure that your project is built and re-run pyre.
```

I haven't thoroughly tested, but it looks like the `-regextype` argument can be removed for the regex used here. The `-xtype` argument gives a similar error, but I believe it can be changed to `type` since the behavior is the same for `-type f`.

Making those two changes resolves the issue for me.

**Comment by Kriechi** [comment]
@mgraczyk Thanks for the pointers!
Even if I fix the two things you mentioned, the find invocation still fails, now with this error:
`find: posix-egrep: No such file or directory`.

Where did you get `posix-egrep`? I couldn't find it in homebrew...

**Comment by dark** [comment]
Thanks for the report @mgraczyk 
I'll look into it.
