### ISSUE TITLE
Getting odd "Could not find a module corresponding to import ..." messages

### ISSUE THREAD

**Issue by johann-petrak** [facebook/pyre-check#172]
I am running pyre as `pyre --source-directory . check` from within a python package and get messages like "Undefined import [21]: Could not find a module corresponding to import \`torch\`."
It also complains about loguru, numpy and others. 

The torch package (and other packages pyre complains about) are installed fine (there is nothing special about them, they are installed using conda or pip into the standard locations for a per-user anaconda installation) and work fine when I run python on those files. Even a file that contains only `import torch` and nothing else will show that error. 

I am using pyre 0.0.24 under anaconda 4.6.11 on Ubuntu linux 18.04, no environment is activated.

**Comment by grievejia** [comment]
This usually happens when typeshed and/or your python site package directory are not under the search path. See [this page](https://pyre-check.org/docs/configuration.html) for more info about how to set up the configurations.

**Comment by johann-petrak** [comment]
As I said, these packages are installed in their standard locations and are on the search path. However there may be no typeshed info available for them (how can I check?)
But if this is just about the fact that those packages have no type information association, the message "could not find a module ..." sounds a bit misleading as it gives the impression that what cannot be located is the module, not some separate type information.

**Comment by grievejia** [comment]
I don't think we automatically include any "standard locations" in pyre at the moment. Those have to be set explicitly in `.pyre_configuration` file (via the `search_path` field) as the linked page suggest. If you run `pyre --source-directory . --noninteractive check`, the directories under which pyre search for source files will be dumped on the command line. 

I believe our current behavior is to not emit "could not find a module" error if typeshed stub is missing but the actual source code can be found under the pyre search path (which, again, have no relation with either the system search path or the python search path by default).

**Comment by lionellloh** [comment]
Fwiw, I had the same issue, and despite playing with .pyre_configuration, it didn't quite work out. 

I reinitialize by running `pyre init` and I think it might have generate the type stubs to get things working
