### ISSUE TITLE
`List[Any]` is not compatible with `Sequence[str]`

### ISSUE THREAD

**Issue by JelleZijlstra** [facebook/pyre-check#18]
A variable of type `List[Any]` should be compatible with an argument of type `Sequence[str]`, because `List` is a subtype of `Sequence` and `Any` is a subtype of anything, but pyre rejects it:
```
$ cat srcdir/seqany.py 
from typing import Any, List, Sequence

def f1(lst: Sequence[str]) -> None:
    pass

def f2() -> None:
    lst: List[Any] = []
    f1(lst)
$ pyre --source-directory srcdir/ --verbose check
...
srcdir/seqany.py:8:7 Incompatible parameter type [6]: Expected `Sequence[str]` but got `List[typing.Any]`.
```

**Comment by sinancepel** [comment]
Thanks for the report! We'll address this ASAP.

**Comment by sinancepel** [comment]
Closed by https://github.com/facebook/pyre-check/commit/7da0559a42e6a1cdf98da9302353641f75118eaa

**Comment by JelleZijlstra** [comment]
Thanks for the quick fix!
