### ISSUE TITLE
Plans for inferred return types?

### ISSUE THREAD

**Issue by travigd** [facebook/pyre-check#181]
One of the nicest parts about TypeScript and Flow is that it can infer the return type of functions (assuming all the inputs are appropriately typed).

I know this isn't always possible (especially when using untyped code internally) but it would be nice if this were possible (possibly raising an error in strict mode if the return type couldn't be inferred).

For example, this should fail.
```python
def getfour():
    return "four"

print(getfour() + 4)
```

**Comment by travigd** [comment]
Related: it would be nice to have a roadmap for the directions that Pyre is headed (e.g. whether or not this is within the scope of this project).

**Comment by dkgi** [comment]
We avoid inter-procedrual inferences as they limit the ability to parallelize type checking. This is by design.

Re roadmap: we're starting to do planning for the second half of 2019 now. We'll add a roadmap to the repository once we're done with this round of planning.

**Comment by dkgi** [comment]
We published our roadmap with 99231a9.
