### ISSUE TITLE
IPython dependency blocking

### ISSUE THREAD

**Issue by cigrainger** [facebook/pyre-check#182]
I'm using pyproject.toml and `poetry` for dependency management and `pyre`'s ipython dependency seems to be pinned at 0.6.5. Not sure what this dep is for in the first place (seems like it'd be a development dependency for you guys?). But either way, it blocks me from using the newest version of `ipython` alongside `pyre`, which is painful. Any chance this can be resolved?

**Comment by grievejia** [comment]
Pyre itself does not rely on ipython. The issue comes from the bundled [`sapp` tool](https://github.com/facebook/pyre-check/tree/master/tools/sapp):

> Ipython 7 uses prompt_toolkit 2. Ipython 6 uses prompt_toolkit 1, which is incompatible with prompt_toolkit 2. The current version of the sapp code uses features from prompt_toolkit 1.

This should be a fixable problem in theory but I'm not sure if any team member has the bandwidth to work on it. A PR is always welcomed.

**Comment by grievejia** [comment]
The `sapp` dependency has been removed in the latest pyre release. It should only depends on `pywatchman` now.
