### ISSUE TITLE
add source distribution on pypi

### ISSUE THREAD

**Issue by nwalsh1995** [facebook/pyre-check#184]
Hi all,

Right now only wheels are being uploaded on pypi, is it possible we can get source distribution as well? Some companies only allow for source distributed packages to be used internally.

**Comment by MaggieMoss** [comment]
@nwalsh1995 Just wanted to give you a quick update - we should have this ready to go with our next open source release.

**Comment by nwalsh1995** [comment]
Hi @MaggieMoss, thanks for picking this up. I have been poking at it and came up with the following which seems to work (sdist only, minimal changes):
```
diff --git a/scripts/build-pypi-package.sh b/scripts/build-pypi-package.sh
index 49a0bcd4..16668da2 100755
--- a/scripts/build-pypi-package.sh
+++ b/scripts/build-pypi-package.sh
@@ -218,6 +218,10 @@ cat > "${BUILD_ROOT}/setup.cfg" <<HEREDOC
 license_file = LICENSE
 HEREDOC
 
+cat > "${BUILD_ROOT}/MANIFEST.in" <<HEREDOC
+include pyre_check/sapp/requirements.txt
+HEREDOC
+
 # Test descriptions before building:
 # https://github.com/pypa/readme_renderer
 if [[ "${HAS_PIP_GREATER_THAN_1_5}" == 'yes' ]]; then
@@ -225,7 +229,7 @@ if [[ "${HAS_PIP_GREATER_THAN_1_5}" == 'yes' ]]; then
 fi
 
 # Build.
-python3 setup.py bdist_wheel
+python3 setup.py sdist
 
 # Move artifact outside the build directory.
 mkdir -p "${SCRIPTS_DIRECTORY}/dist"
```
Just dumping in case it helps out

**Comment by nwalsh1995** [comment]
@MaggieMoss  I see pyre-check 0.0.29 is released but no source files: https://pypi.org/project/pyre-check/0.0.29/#files

Just wondering on the status

**Comment by MaggieMoss** [comment]
I've just added the source files to that release - let me know if you have any issues there :)

**Comment by nwalsh1995** [comment]
@MaggieMoss getting the following (install on mac):
```
$ pip install pyre-check --no-binary :all:
Collecting pyre-check
  Could not find a version that satisfies the requirement pyre-check (from versions: 0.0.29-macosx_10_11_x86_64)
No matching distribution found for pyre-check
```

**Comment by nwalsh1995** [comment]
Hi all, still affected by the above ^.

@MaggieMoss should we re-open this ticket?

**Comment by MaggieMoss** [comment]
Apologies, I missed this. Looking into it now.

**Comment by MaggieMoss** [comment]
@nwalsh1995  Just wanted to give you an update - the latest release should fix this issue. Let me know if you're still having trouble!
