### ISSUE TITLE
v0.0.28 spurious (?) error with nested recursive function

### ISSUE THREAD

**Issue by mlin** [facebook/pyre-check#186]
```python
def fib(m: int) -> int:
    def inner(n: int) -> int:
        return n if n in [0, 1] else (inner(n-1) + inner(n-2))
    return inner(m)
```

pyre v0.0.28 newly complains

> Undefined name [18]: Global name `inner` is not defined, or there is at least one control flow path that doesn't define `inner`.

**Comment by MaggieMoss** [comment]
Hi @mlin just wanted to give you a quick update - we've recently added a fix for this and it will be included in our next open source release. Thanks for logging the issue :)
