### ISSUE TITLE
Type error reported on linux but not on macOS

### ISSUE THREAD

**Issue by samuela** [facebook/pyre-check#187]
I have a peculiar situation in which a bit of code type checks just fine locally (macOS 10.14.4), but not on CI (circleci/python:3.7 docker image). I've confirmed that I'm using the same version of pyre-check on both machines:
```
circleci $ pipenv run pyre --version
No watchman binary found. 
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install.html
Defaulting to non-incremental check.
 ƛ Found: `/home/circleci/.local/share/virtualenvs/project-zxI9dQ-Q/lib/pyre_che
binary version: unversioned
client version: 0.0.28
local $ pipenv run pyre --version
 ƛ Found: `/Users/skainswo/.local/share/virtualenvs/research-CJWjSlE2/lib/pyre_check/typeshed/`
binary version: unversioned
client version: 0.0.28
```
but they do not produce the same results when running `pyre check`. Locally there are no type errors but on CI:
```
research/estop/pendulum_example_rollout.py:27:0 Undefined attribute [16]: `gym.envs.classic_control.pendulum.PendulumEnv` has no attribute `last_u`.
research/estop/pendulum_example_rollout.py:30:2 Undefined attribute [16]: `gym.envs.classic_control.pendulum.PendulumEnv` has no attribute `state`.
```
which is quite peculiar to me. I've even confirmed that the md5 hashes of `gym/envs/classic_control/pendulum.py` match locally and remotely, and I have a clean git state on both machines. I've also `pipenv --rm`ed the virtualenv locally and tried reinstalling everything from scratch. The problematic piece of code looks like
```python
gymenv = PendulumEnv()
gymenv.reset()
gymenv.last_u = jp.array(1e-12)  # type failure here! 

for t in range(states.shape[0]):
  gymenv.state = states[t] + jp.pi  # type failure here! 
  gymenv.render()
```
This exact same code type checked both locally/remotely with `gym==0.13.0` and `pyre-check==0.0.27` but is no longer consistent with `gym==0.13.1` and `pyre-check==0.0.28`.

I'm at a loss for what could be causing this discrepancy, but it's definitely concerning. Happy to provide access to my private repo for debugging purposes.

**Comment by samuela** [comment]
Update: downgrading to `pyre-check==0.0.27` on CI (but keeping `gym==0.13.0`) resolves the type errors on CI.

**Comment by MaggieMoss** [comment]
Thanks for reporting this issue! It should be fixed in `v0.0.29`.

**Comment by samuela** [comment]
@MaggieMoss I tried upgrading to `pyre-check==0.0.29` but unfortunately I'm seeing the exact same behavior.

**Comment by samuela** [comment]
Seems to be resolve in `0.0.30`.
