### ISSUE TITLE
[Question] Pyre-check for refactoring python code

### ISSUE THREAD

**Issue by neomatrix369** [facebook/pyre-check#188]
Has anyone used pyre-check to perform code refactoring given that we can generate AST or call graph.

On the topic of ASTs / call graphs, is it possible to generate an AST / call graph from a project full of python source files which form a dependency graph with each other starting from the main source program to the last leaf in the branch

or

is the parse still able to generate ASTs or call graphs from single files at a time?

Finally, what is the difference in principle between an AST or call graph generated by `pyre-check`

**Comment by neomatrix369** [comment]
Any chance of getting a response to some of my queries if not all of them. :)

**Comment by dkgi** [comment]
@neomatrix369, sorry for the delay here. Yes, we are actively working on refactoring tools that leverage Pyre's type information and are planning to open source these soon. I'll update this once the release is out. In the meantime, we have some refactoring tools that do not use type information: https://github.com/facebookincubator/Bowler.

**Comment by neomatrix369** [comment]
> @neomatrix369, sorry for the delay here. Yes, we are actively working on refactoring tools that leverage Pyre's type information and are planning to open source these soon. I'll update this once the release is out. In the meantime, we have some refactoring tools that do not use type information: https://github.com/facebookincubator/Bowler.

Thanks for the reply. How are pyre-check and bowler blend in, otherwise it might be a reinvention of the wheel?

Can Bowler be integrated into IDEs like PyCharm for eg?

**Comment by neomatrix369** [comment]
> Finally, what is the difference in principle between an AST or call graph generated by pyre-check
Thinking about this query, I have answered this myself already.

**Comment by neomatrix369** [comment]
About the queries regarding AST and call-graphs, I know pyre-check is able to generate an AST, is this still limited to single-source files or does it also take into consideration its dependencies and dependent source files? The later would be handy to generate an AST across the whole project. Of course, separate ASTs per source file would be more manageable.

**Comment by bgw** [comment]
> How are pyre-check and bowler going to blend in, otherwise it might be a reinvention of the wheel in some way?

@neomatrix369, it's still too early to comment on exactly how this will work. Much of the integration is still being spec'ed out.

**Comment by bgw** [comment]
@neomatrix369, we recently open-sourced LibCST: https://github.com/Instagram/LibCST

@rayjzeng has been working on a metadata API (undocumented and in-progress, but [the code is here](https://github.com/Instagram/LibCST/tree/master/libcst/metadata)). That metadata API should allow us to associate arbitrary bits of metadata with the tree, which (hopefully) could include pyre types at some future point.

**Comment by sritejakv** [comment]
> About the queries regarding AST and call-graphs, I know pyre-check is able to generate an AST, is this still limited to single-source files or does it also take into consideration its dependencies and dependent source files? The later would be handy to generate an AST across the whole project. Of course, separate ASTs per source file would be more manageable.

Seconding this question! How can I generate a call-graph using Pyre?

**Comment by neomatrix369** [comment]
> > About the queries regarding AST and call-graphs, I know pyre-check is able to generate an AST, is this still limited to single-source files or does it also take into consideration its dependencies and dependent source files? The later would be handy to generate an AST across the whole project. Of course, separate ASTs per source file would be more manageable.
> 
> Seconding this question! How can I generate a call-graph using Pyre?

I think there is a way to generate an AST/call graph - have a look at the CLI options and the docs!

I'm pretty sure I saw something on the issues saying that!

**Comment by dkgi** [comment]
If you're running the static analysis bits on a project you should be able to dump the full call-graph with `pyre analyze --save-results-to . --dump-call-graph`. You should get a json file in `.pyre/` somewhere.

We recently migrated our call-graph construction logic and it should now also be available through queries to the server. E.g. if you have Pyre running on a project you should be able to run `pyre query help` to get a list of supported commands. Both `callees` and `callees_with_location` should let you reconstruct the full callgraph.

**Comment by MaggieMoss** [comment]
Closing this issue with some links to LibCST documentation:
- https://libcst.readthedocs.io/en/latest/metadata.html#type-inference-metadata
- https://libcst.readthedocs.io/en/latest/codemods_tutorial.html
