### ISSUE TITLE
ignore_all_errors in configuration fails if folder does not exist

### ISSUE THREAD

**Issue by adrianbn** [facebook/pyre-check#190]
With the latest version of pyre, specifying a directory that does not exist in `ignore_all_errors` makes pyre fail. Here's an example `.pyre_configuration`:
```
{
  "source_directories": [
    "."
  ],
  "ignore_all_errors": [
    "setup.py",
    "test/",
    "build/"
  ]
}
```
And this is the error returned by `pyre` if the `build` folder does not exist (i.e. project hasn't been built yet):
```
> pyre
No watchman binary found.
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install.html
Defaulting to non-incremental check.
 ƛ Invalid configuration: Nonexistent path passed in to `ignore_all_errors`                         field: `/Users/adrian/code/test/build
```

This was not a problem with at least 0.0.27, but it definitely fails in 0.0.29. 

Thanks!

**Comment by grievejia** [comment]
Thanks for the report! This issue has been fixed on master (commit 8d0af4) and will be included in the next open source release.

**Comment by adrianbn** [comment]
Awesome, thanks for the quick turnaround!
