### ISSUE TITLE
scoping of the name bound by method definitions is too wide

### ISSUE THREAD

**Issue by jesboat** [facebook/pyre-check#191]
Within a class statement, a method (defined using the normal syntax) binds its name only in later statements in the class. Pyre mishandles this when a method has the same name as a type used in an annotation. As an example,

```python
#pyre-strict

class Demo(object):
    v: int

    def __init__(self, arg: int) -> None:
        self.v = arg

    def int(self) -> int:
        return self.v
```

The correct interpretation is that v's annotation is evaluated in a scope which does not yet include the `def int` and so v is annotated with the global int; likewise for the return type annotation of the method. (This is based on the python docs which state "The class’s suite is then executed in a new execution frame (see Naming and binding), using a newly created local namespace and the original global namespace. (Usually, the suite contains mostly function definitions.) When the class’s suite finishes execution, its execution frame is discarded but its local namespace is saved. 3 A class object is then created using the inheritance list for the base classes and the saved local namespace for the attribute dictionary." (language reference, 8.7) and " All annotation expressions are evaluated when the function definition is executed, just like default values."  (PEP3107)) It is also consistent with CPython:

```
Python 3.7.3 (default, Apr 27 2019, 18:00:58) 
[Clang 9.0.0 (clang-900.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import demo1
>>> demo1.Demo.__annotations__['v']
<class 'int'>
>>> demo1.Demo.int.__annotations__['return']
<class 'int'>
>>> 
```

However, Pyre treats the `def int` as binding `int` in the annotations, yielding type errors:

```
demo1.py:4:4 Missing attribute annotation [4]: Attribute `v` of class `demo1.Demo` has no type specified.
demo1.py:4:7 Invalid type [31]: Expression `Demo.int` is not a valid type.
demo1.py:6:28 Invalid type [31]: Expression `Demo.int` is not a valid type.
demo1.py:9:21 Invalid type [31]: Expression `Demo.int` is not a valid type.
```

The concrete example which inspired this was

```python
class Bitset(object):
    _val: int
    
    ...
    
    def int(self) -> int:
        return self._val
```

**Comment by yangdanny97** [comment]
This example no longer repros internally, so It might have been fixed by @grievejia recent qualification changes.

It still repros on the playground, but it will be fixed in the next release.
