### ISSUE TITLE
Incremental mode not detecting changes

### ISSUE THREAD

**Issue by tuvistavie** [facebook/pyre-check#20]
Hi,

I am trying out pyre, but the incremental mode does not seem to be detecting changes after the first run.

Here is the sample file I am using

```python
# my_lib/sample.py

class Foo:
    def __init__(self) -> None:
        self.prop_ = "bar"


class Bar:
    def __init__(self, foo: Foo) -> None:
        self.prop = "hello " + foo.prop
```

When I run `pyre` the first time, I get the error as expected, but even if I update the file, the server seems to using the old state of the file.

```
$ pyre
 ƛ Server not running at `.`. Starting...
 ƛ Server initializing...
 ƛ Found 1 type error!
my_lib/sample.py:8:31 Undefined attribute [16]: `Foo` has no attribute `prop`.
$ sed -i -e 's/foo\.prop/foo.prop_/' my_lib/sample.py 
$ pyre
 ƛ Waiting for server...
 ƛ Found 1 type error!
my_lib/sample.py:8:31 Undefined attribute [16]: `Foo` has no attribute `prop`.
$ pyre check
 ƛ No type errors found
```

Restarting the server or using `check` works, but I could not find a way to use the incremental mode yet.

Any idea?

Thanks.

### Environment

```
$ cat .pyre_configuration
{
  "binary": "/home/daniel/.asdf/installs/python/3.6.2/bin/pyre.bin",
  "source_directories": [
    "."
  ],
  "typeshed": "/home/daniel/.asdf/installs/python/3.6.2/lib/pyre_check/typeshed/stdlib/"
}
$ uname -r
4.16.8-1-ARCH
$ sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 100000
$ lsof | grep inotify | wc -l
1468
```

**Comment by sinancepel** [comment]
Hello! Could you `cat .watchmanconfig` and if it doesn't exist, run

```bash
echo "{}" > .watchmanconfig
watchman watch .
pyre restart
```

and see if that helps?

**Comment by gvanderest** [comment]
I've run into the same thing, and have tried @sinancepel's suggestion.  Running a `pyre restart` appears to reset the cache, and properly detect the changes on the other side; however, none of it appears to be automated as expected.

The watchmanconfig+restart didn't appear to help in my case.

**Comment by ethanhs** [comment]
The suggested commands caused for me:

```
 ƛ Server not running at `mypkg`. Starting...
 ƛ Server initializing...
 ƛ Client exited with error code 1:

 ƛ Restart the server? [Y/n] Y

 ƛ Parsing 346 stubs and external sources...
Worker.Worker_failed_to_send_job(_)
Raised at file "map.ml", line 131, characters 10-25
 ƛ Parsing 346 stubs and external sources...
Worker.Worker_failed_to_send_job(_)
Raised at file "map.ml", line 131, characters 10-25
Called from file "sexp_conv.ml", line 148, characters 10-37
Worker interrupted with signal: sigpipe
Worker interrupted with signal: sigpipe [26.4s]

```

**Comment by sinancepel** [comment]
Commits to support didSave requests on VSCode when watchman is disabled have made it to trunk: 0e41ed353473dc6449f7fb515f1e8e699a51b75c a245638fafb4f226c149db233cc2d3368f9a94f8

**Comment by aspin** [comment]
Hi there,

Not sure if you prefer new issues or reopening new ones, but I started using Pyre and I've been having this issue.

e.g.
```python
# main.py

**Comment by aspin** [comment]
I figured it out –– pyre has a missing dependency on pywatchman. I'll file a new issue.
