### ISSUE TITLE
`typing.Iterable` is not "an immutable variant for lists"

### ISSUE THREAD

**Issue by anowlcalledjosh** [facebook/pyre-check#200]
[The docs](https://pyre-check.org/docs/error-types.html#list-and-dictionary-mismatches-with-subclassing) say:

> `typing.Iterable` is an immutable variant for lists that allows accessing the list without modifying it. Most commonly used generic containers have immutable variants, and I would encourage you to use them for function parameters whenever you don't need to modify a container in your function.

A `typing.Iterable` (or [`collections.abc.Iterable`](https://docs.python.org/3/library/collections.abc.html#collections.abc.Iterable)) is just "something that provides `__iter__()`"; `Iterable`s don't necessarily support indexing, but lists do. `typing.Sequence` would be a better fit for "immutable variant for lists", or the docs could say something like "...that allows iterating over the list without modifying it".

**Comment by pradeep90** [comment]
The docs now mention when to use `Sequence`.
