### ISSUE TITLE
Pyre / Pytest Integration

### ISSUE THREAD

**Issue by TylerYep** [facebook/pyre-check#206]
I'm using both Pyre and Pytest in my project, but I'm getting the following import errors in Pyre:

```
unit_test/conftest.py:3:0 Undefined import [21]: Could not find a module corresponding to import `pytest`.
unit_test/conftest.py:8:1 Undefined name [18]: Global name `pytest` is not defined, or there is at least one control flow path that doesn't define `pytest`.
```
The code runs fine in Pytest and when I run it from python directly, so I'm guessing there is some path issue in Pyre. Is there some way to add pytest (pip-installed module) to Pyre's path, perhaps via its config or some init-hook?

**Comment by MaggieMoss** [comment]
Hi @TylerYep adding `pytest` to your pyre_configuration `search_path` should help solve the issue: https://pyre-check.org/docs/configuration.html 

Can you let me know if that fixes the errors?

**Comment by TylerYep** [comment]
How exactly do I add pytest to search_path? I tried the following, but I am still getting the same errors.

This is what my .pyre_configuration file looks like:
```
{
  "binary": "/Users/tyleryep/miniconda3/bin/pyre.bin",
  "source_directories": ["."],
  "ignore_all_errors": ["unit_test/conftest.py"],
  "search_path": ["/Users/tyleryep/miniconda3/lib/python3.7/site-packages/pytest-5.1.2.dist-info"],
  "typeshed": "/Users/tyleryep/miniconda3/lib/pyre_check/typeshed/"
}
```

**Comment by yuejia** [comment]
I had the similar problem and adding search_path to the site-packages path works for me. 
```
"search_path": ["/Users/***/.pyenv/versions/3.7.4/envs/py37/lib/python3.7/site-packages"],
```

**Comment by MaggieMoss** [comment]
@TylerYep did @yuejia 's fix solve the issue for you?

**Comment by TylerYep** [comment]
Yes, that solves the errors!

Unfortunately, adding all of the site-packages to the search path quadrupled the parsing and type environment build time.

I got around it by making a separate environment for all of my work, which still doubled the total pyre check time but is at least manageable.

I also tried using:
`"search_path": [{ "site-package": "tqdm" }]`
for individual packages, which sped up the runtime significantly (since Pyre does not have to check unnecessary files), but unfortunately Pytest does not have a corresponding site-packages folder (and there is no way to specify a .py file like so):
`"search_path": [{ "site-package": "pytest.py" }]`

Please let me know if there is a way to link to only Pytest's site-package. Other than that, my issue has been resolved, thank you for all of your help!
