### ISSUE TITLE
Faulty "Unable to unpack 3 values, 2 were expected." error

### ISSUE THREAD

**Issue by samuela** [facebook/pyre-check#211]
I have a bit of code:
```python
def unsafe_openai_gym_env(construct_env,
                          reward_adjustment: float = 0.0) -> Env:
  # blah blah blah
  return Env(initial_distribution, step, reward), gym_env

env, _gym_env = unsafe_openai_gym_env(lambda: gym.make("HalfCheetah-v3"),
                                      reward_adjustment=1.0)
```
which makes complete sense and runs just fine, but pyre is giving me an error:
```
research/estop/half_cheetah/config.py:74:0 Unable to unpack [23]: Unable to unpack 3 values, 2 were expected.
```

**Comment by samuela** [comment]
Furthermore if I change my code to
```python
env, = unsafe_openai_gym_env(lambda: gym.make("HalfCheetah-v3"),
                             reward_adjustment=1.0)
```
then I get
```
 ƛ Found 1 type error!
research/estop/half_cheetah/config.py:66:0 Unable to unpack [23]: Unable to unpack 2 values, 1 were expected.
```
So I can't win!

**Comment by MaggieMoss** [comment]
Thanks for reporting the issue. 

It looks to me like the return annotation on `unsafe_openai_gym_env` should be a `Tuple` and not just an `Env`, since it looks like you're returning more than one item. 

```
from typing import Tuple
def unsafe_openai_gym_env(construct_env,
                          reward_adjustment: float = 0.0) -> Tuple[Env, GymEnv]:

```

Does that help solve the error?

**Comment by samuela** [comment]
@MaggieMoss Ah, good point! I had forgotten about that type annotation. That does indeed resolve that particular error, but I suppose the obvious next question is: Why didn't pyre complain that `Tuple[Env, GymEnv]` was not a subtype of `Env`?

**Comment by MaggieMoss** [comment]
@samuela I am seeing that error when I use the example you described above - which version of Pyre are you running?
