### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by cooperlees** [facebook/pyre-check#213]
Hi,

What's the timeframe for 3.8 support now it's an official Python version?

Seems LibCST is a blocker: https://github.com/Instagram/LibCST/issues/122

**Comment by dseevr** [comment]
Per [this comment](https://github.com/Instagram/LibCST/issues/122#issuecomment-560537830), pyre should be unblocked as far as 3.8 support if it upgrades libcst to `0.2.4`

**Comment by MaggieMoss** [comment]
@dseevr thanks for the update! We'll update soon!

**Comment by jdanekrh** [comment]
Pyre 0.0.41 works for me on 3.8.

**Comment by MaggieMoss** [comment]
Wanted to give an update here - we've added support for the walrus operator and positional only parameters recently, and those updates will be included in our next release :)
