### ISSUE TITLE
How to check a single source file, not a directory?

### ISSUE THREAD

**Issue by cjolowicz** [facebook/pyre-check#217]
How can you check a single source file with pyre?

My project contains the source directories `src` and `tests`, and the file `noxfile.py`. I understand I can use `pyre --source-directory=src  --source-directory=tests check` for the source directories, but there does not seem to be a way to type-check the file `noxfile.py`.

I cannot use `--source-directory=.` because the project directory also contains virtual environments under `.nox`. I tried to use `--source-directory=. --exclude=.nox/.*` but this did not seem to exclude the virtual environments. Anyway, I would prefer to have a way to specify files to be checked, rather than files not to be checked.

Thank you!

**Comment by cjolowicz** [comment]
Update: 

The following command works: 

```
pyre --source-directory=. --exclude=.*/\.nox/.* --exclude=.*/\.pytype/.* check
```

As said above, it would be much clearer to specify the files to be checked. What exactly needs to be excluded can differ between developers, so the `--exclude` options could easily get very boilerplate-y.

Am I missing something here?

**Comment by MaggieMoss** [comment]
Thanks for reporting, and for including your fix. 

Apologies for the frustrating experience.

Have you considered adding a `.pyre_configuration` file, that would let you specify these excluded files, and potentially share them amongst developers?

**Comment by ewianda** [comment]
Was wondering why this was closed. It is useful to just check a single source file like `pyre check noxfile.py`
