### ISSUE TITLE
Undefined import [21]: Could not find a module corresponding to import

### ISSUE THREAD

**Issue by nicoCalvo** [facebook/pyre-check#220]
I tried/follow every open issue and yet I'm not able to sort out the problem of not finding import installed on a venv. I added the source directory as root, but when I do that, I takes other dirs as part of the check (like .penv, .pyre, and some others related to env building).

Could you help me see how this should be done? Considering the following structure:

```
ignoreme_1/*
ignoreme_2/*
.penv/
actual_project/
```
How can I ignore those directories, the penv, and make pyre actually find the imports I'm referring to in the .penv??

Thank you

**Comment by the-storm** [comment]
@nicoCalvo  You probably want to update your pyre configuration file (https://pyre-check.org/docs/pysa-running.html#4-pysa-configuration) to include `"search_path"` key. 
For example

```
 {
  "source_directories": [
    "./actual_project/"
    ],
  "taint_models_path": "stubs/taint",
  "search_path": ["./penv"]
}
```

**Comment by the-storm** [comment]
I will close this issue for now. Feel free to re-open if it does not fix the errors

**Comment by the-storm** [comment]
@nicoCalvo I will close this issue assuming that the last message would help in fixing your error. Feel free to file another issue if you still have the problem
