### ISSUE TITLE
Undefined attribute [16]: `Optional` has no attribute ...

### ISSUE THREAD

**Issue by AndGem** [facebook/pyre-check#221]
Hi Pyre Team,

I encountered the following Problem for which I produced a simplified version with a minimal example. The content below is in a single file: `main.py`. I get inconsistent behavior of pyre check for the lines 21 and 24 (`local_data.some_str = "text123"` and `self.some_data.some_str = "text123"`). Both are essentially identical, except that `local_data` is a reference to `self.some_data`.

```python
from typing import Optional


class SomeDataClass:
    def __init__(self) -> None:
        self.some_str: str = ""


class Bar:
    def __init__(self) -> None:
        self.some_data: Optional[SomeDataClass] = None

    def foo(self, name: str) -> None:
        if name == "start!":
            self.some_data = SomeDataClass()
            return

        if self.some_data is not None:
            local_data = self.some_data
            # assert local_data is not None
            local_data.some_str = "text123"

            # assert self.some_data is not None
            self.some_data.some_str = "text123"
```

If I execute the check with pyre I get the following output:
```sh
➜  pyrebug pyre --source-directory .  check
Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
 ƛ Found 1 type error!
main.py:21:12 Undefined attribute [16]: `Optional` has no attribute `some_str`.
```
*Output*:
- type error in `l. 21`

*Expected Output*: 
- no type error

I would understand also if it would produce for both lines 21 and 24 the same error. But since `local_data` and `self.some_data` should have the same type I except that the result from pyre would be the same for lines 21 and 24.

----------------------------

The issue becomes a bit more strange when slightly modifying the example by enabling only *the first* `assert` in the example:

```python
from typing import Optional


class SomeDataClass:
    def __init__(self) -> None:
        self.some_str: str = ""


class Bar:
    def __init__(self) -> None:
        self.some_data: Optional[SomeDataClass] = None

    def foo(self, name: str) -> None:
        if name == "start!":
            self.some_data = SomeDataClass()
            return

        if self.some_data is not None:
            local_data = self.some_data
            assert local_data is not None
            local_data.some_str = "text123"

            # assert self.some_data is not None
            self.some_data.some_str = "text123"
```
Now executing the check yields the following:
```sh
➜  pyrebug pyre --source-directory .  check
Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
 ƛ Found 1 type error!
main.py:24:12 Undefined attribute [16]: `Optional` has no attribute `some_str`.
```

*Output*:
- type error in `l. 24`

*Expected Output*: 
- no type error

----------------------------

Enabling the second `assert` seems to have no effect though.

I hope this helps, and would be glad to get help (maybe I'm doing something wrong?). 

*Additional Information*:
```sh
➜  pyrebug pyre --version                  
No watchman binary found. 
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install.html
Defaulting to non-incremental check.
Binary version: No version set
Client version: 0.0.33
```

```sh
➜  pyrebug system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.14.6 (18G2022)
      Kernel Version: Darwin 18.7.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ***
      User Name: ***
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 5 days 3:37
```

**Comment by shannonzhu** [comment]
Unfortunately Pyre doesn't allow refinement of non-local values, such as attributes, to persist indefinitely. Since `self.some_data` is annotated as `Optional[SomeDataClass]`, the type checker will not warn if something assigns `None` to `self.some_data` in between the refinement check (e.g, `assert self.some_data` and the next reference to `self.some_data`).

This is equivalent to checking `assert foo(x)` and then hoping the value returned by the next call to `foo(x)` will still have the refinement applied -- esp. since attribute access is implemented with an overridable `__getattr__` function. 

A workaround is to assign the attribute to a local before refinement, if you are hoping the refinement will continue to persist on the next use. Python 3.8 will introduce a walrus operator that will make this much less cumbersome and not require an extra line of code!
