### ISSUE TITLE
pyre fails to start if an ignored directory is missing

### ISSUE THREAD

**Issue by omry** [facebook/pyre-check#227]
If the pyre server is not already running, pyre fails to run if a directory specified in `ignore_all_errors` is missing:

config:
```json
{
  "source_directories": [
    "."
  ],
  "ignore_all_errors": [
    ".nox",
  ]
}

```

```
$ pyre
Nonexistent path passed in to `ignore_all_errors`                         field: `/Users/omry/dev/omegaconf.test/.nox

```

**Comment by MaggieMoss** [comment]
Hi @omry  this seems like the expected behaviour, is there something we can do to improve the error message there?

**Comment by pradeep90** [comment]
@omry This should be fixed by https://github.com/facebook/pyre-check/commit/25ef1a6a71d7132429c8ff479019f908af7a1b58. We no longer raise an error if there is a non-existent path. Thanks for the report.

**Comment by omry** [comment]
Thanks @pradeep90!
