### ISSUE TITLE
Unhelpful error message "ƛ Could not parse file at 1850:8-1850:8"

### ISSUE THREAD

**Issue by anentropic** [facebook/pyre-check#236]
I added my virtualenv site-packages dir to `.pyre_configuration`

when I run `pyre check` I see:

```
 ƛ Parsing 4373 stubs and sources... [3.1s]
```
and then
```
 ƛ Could not parse file at 1850:8-1850:8
          Ø: Set[str] = set()
         ^
 ƛ Could not parse 1 file due to syntax errors!
```

Needless to say, this error would be infinitely more useful if it gave the path of the file where the error occurred....

**Comment by MaggieMoss** [comment]
Hi there! 

We have a fix ready to go for this that will be included in our next release. We should be releasing this week :) Thanks so much for the report!

**Comment by anentropic** [comment]
awesome 👍
