### ISSUE TITLE
Server should return JSON dictionary with top-level `errors` field.

### ISSUE THREAD

**Issue by pradeep90** [facebook/pyre-check#238]
We need to repro and investigate why the server sometimes returns a json response of the form `{'response': {'errors': []}}` instead of `{'errors': []}`.

**Comment by EricLiclair** [comment]
Can you point out a file location for me to dig deeper into? Maybe I can try giving a broad look to the responses. 😄

**Comment by MaggieMoss** [comment]
@EricLiclair I am going to close this issue - IIRC it hasn't been reported recently, and with our v2 server, it should no longer be an issue. I will re-open if it appears again.
