### ISSUE TITLE
No documentation for .pyre_configuration

### ISSUE THREAD

**Issue by j2kun** [facebook/pyre-check#24]
[The documentation](https://pyre-check.org/docs/documentation.html) shows `pyre init` generates a `.pyre_configuration`, but there is no information on how to set the values, or what configs exist.

For example, I don't know how to exclude a particular directory, and by default pyre recursively checks a virtualenv in my project root, spitting out a ton of errors in standard libraries. For example

```
venv/lib/python3.6/site-packages/pip/_internal/configuration.py:212:12 Undefined name [18]: Global name `pip` is undefined.
```

**Comment by sinancepel** [comment]
Thanks for reporting! We're tracking this in https://github.com/facebook/pyre-check/issues/10.
