### ISSUE TITLE
VSCode pyre-check not linting, but CLI works fine

### ISSUE THREAD

**Issue by moxuz** [facebook/pyre-check#25]
I have installed pyre-check in my pyenv virtualenv VSCode project.

Pyre is able to catch an error if I run it through the CLI, but the VSCode extension does not seem to be catching anything. There is no output in any of the problem/bug prompts either.

Here is an image describing the issue. VSCode doesn't show anything, but the CLI catches the error.
<img src="https://dl.dropboxusercontent.com/s/crwjz1zooapr03b/Screenshot%202018-05-12%2009.39.58.png?dl=0" alt="vscode no errors">

```
{
  "binary": "/Users/christophepouliot/.pyenv/versions/spotify-discow-sync/bin/pyre.bin",
  "source_directories": [
    "."
  ],
  "typeshed": "/Users/christophepouliot/.pyenv/versions/3.6.2/envs/spotify-discow-sync/lib/pyre_check/typeshed/stdlib/"
}
```

If I do `pyre restart` in the CLI the VSCode linting will catch the error, but then if I change it to return a string it still lints it as an error. If I `pyre restart` again it still shows an error (although I am returning a string and not an int, which is correct). If I close/reopen VSCode at this point the linting error goes away. Changing it back to returning an int shows no error again until I `pyre restart`, and then this all starts again.

I added a .watchmanconfig but that did not help (Is this needed? I dont see it mentioned)

VSCode 1.23.1
Python 3.6.2 with pyenv virtualenv
VSCode Python version set to /Users/christophepouliot/.pyenv/versions/spotify-discow-sync/bin/python

**Comment by dkgi** [comment]
@sinancepel: can you take a look at this?

**Comment by sinancepel** [comment]
Hi @moxuz, thanks for the report! This looks like VSCode isn't adding your virtual environment to your path. Could you try opening VSCode from your virtual environment in the terminal, and see if pyre works there? 

As for the actual issue itself, I'll investigate whether we can automatically pick up on your virtual environment on the pyre-vscode side.

**Comment by moxuz** [comment]
Hey @sinancepel Thanks for the response. I have been using it/opening it from the virtual env in my terminal. I think the weird part is that it works once after a `pyre restart` but then stops after that.

**Comment by sinancepel** [comment]
@moxuz this looks like an unrelated issue where we weren't properly listening to VSCode's didSave requests, which I'm tracking at https://github.com/facebook/pyre-check/issues/20. I'll close this when a fix is rolled out for that.

**Comment by sinancepel** [comment]
With the following commits, pyre should properly handle VSCode didSave requests, closing this issue. https://github.com/facebook/pyre-check/commit/0e41ed353473dc6449f7fb515f1e8e699a51b75c https://github.com/facebook/pyre-check/commit/a245638fafb4f226c149db233cc2d3368f9a94f8
