### ISSUE TITLE
flow control analysis doesn't handle infinite loops

### ISSUE THREAD

**Issue by matejcik** [facebook/pyre-check#251]
the following code will fail to typecheck:
```python
import random

while True:
    if random.random() > 0.5:
        some_var = True
        break

print(some_var)
```
error is:
```
py.py:8:6 Undefined name [18]: Global name `some_var` is not defined, or there is at least one control flow path that doesn't define `some_var`.
```

**Comment by matejcik** [comment]
pyre-check 0.0.46
Binary version: 407d1bc850869348d1c8c680c546618585bce2b1
Client version: internal-dev

**Comment by mrkmndz** [comment]
I was able to fix this with https://github.com/facebook/pyre-check/commit/0769f1c52efe32fc55b7af978c493d3863d05d01 and https://github.com/facebook/pyre-check/commit/d8dbef75faa77fc1bd5dad1bbe9bc9682d6d4c1d.

These should be included in the next open-source release, or you can build a local version of pyre to use for yourself.

Thank you for the nicely minimized report!
