### ISSUE TITLE
Support for __debug__ special variable

### ISSUE THREAD

**Issue by matejcik** [facebook/pyre-check#252]
the following code will fail to type-check:
```python
if __debug__:
    some_var = True

other_var = False

if __debug__:
    print(some_var == other_var)
```
error is:
```
py.py:7:10 Undefined name [18]: Global name `some_var` is not defined, or there is at least one control flow path that doesn't define `some_var`.
```

This is reasonable for plain old boolean variables. But pyre should know that `__debug__` is statically known to be `True` (maybe even configurable to `False`?) and evaluate the above code accordingly.

pyre-check 0.0.46
Binary version: 407d1bc850869348d1c8c680c546618585bce2b1
Client version: internal-dev

**Comment by MaggieMoss** [comment]
Hi @matejcik thanks for reporting. It looks like the issue isn't that Pyre doesn't know that `__debug__` is a boolean value, but that the variable `some_var` is optionally defined. This is the expected behaviour.

For example: 

```
debug = True

if debug:
    some_var = True

other_var = False

if debug:
    print(some_var == other_var)
```
Still has the following error: 

```
9,10: Undefined name [18]: Global name `some_var` is not defined, or there is at least one control flow path that doesn't define `some_var`.
```

What I would recommend is to define `some_var` as False outside of the conditional. 

```
some_var = False 

if condition:
    some_var = True
```

**Comment by matejcik** [comment]
hello @MaggieMoss,

> It looks like the issue isn't that Pyre doesn't know that `__debug__` is a boolean value

indeed. the issue is that `__debug__` is **statically known** boolean value, which does not change during execution

i.e. the sample code is equivalent to (as long as python runs with `-O0`)

```python
if True:
    some_var = True

other_var = False

if True:
    print(some_var == other_var)
```
which indeed type-checks as valid in Pyre

I understand that declaring the variable outside the conditional would help Pyre here, as it does help in your example. My actual usecase is typechecking Micropython code, where `if __debug__` statements are completely removed from bytecode in production build, so I don't want to clobber the namespace of a production build with variables that aren't used anywhere except in `if __debug__` statements.

**Comment by matejcik** [comment]
see also: https://docs.python.org/3/library/constants.html and https://docs.python.org/3/reference/simple_stmts.html#assert :

> Assignments to __debug__ are illegal. The value for the built-in variable is determined when the interpreter starts.

**Comment by mrkmndz** [comment]
I believe the `if True` example only works because we're able to completely eliminate that optional check.  Supporting this use case would require us to re-do the analysis for both debug=True and debug=False, or either restructure our resolution data structures to condition existence of variables on particular boolean values.  This devolves into quadratic check work very quickly.

In general one of the goals of Pyre is to encourage a style of Python without dynamic variable declaration.

For these reasons I don't imagine we will implement this behavior.

**Comment by matejcik** [comment]
> I believe the `if True` example only works because we're able to completely eliminate that optional check. Supporting this use case would require us to re-do the analysis for both debug=True and debug=False

this would be nice, but a sufficient solution is to leave this choice to the user, same way python interpreter does

> or either restructure our resolution data structures to condition existence of variables on particular boolean values. This devolves into quadratic check work very quickly.

entirely too much work, that also seems to assume that there are going to be more such variables in the future. Again, per https://docs.python.org/3/library/constants.html:

>  The names `None`, `False`, `True` and `__debug__` cannot be reassigned (assignments to them, even as an attribute name, raise SyntaxError), so they can be considered “true” constants.

so `__debug__` is indeed a one-time special case

---

Perhaps an acceptable solution would be a new feature letting the user declare a list of statically known constants and their values for this purpose?

**Comment by matejcik** [comment]
...OTOH conditional blocks should not change _typing_ information, so AFAICT this issue only affects the "undefined name" check. So a good workaround for my case would be disabling that particular check.

**Comment by mrkmndz** [comment]
> this would be nice, but a sufficient solution is to leave this choice to the user, same way python interpreter does

> Perhaps an acceptable solution would be a new feature letting the user declare a list of statically known constants and their values for this purpose?

An active goal of this project is to minimize the amount of differences in type checking results based on configuration options.  We'd like folks to be able to anticipate what Pyre will do just looking at the files themselves, without having to ask questions about the configuration.

> that also seems to assume that there are going to be more such variables in the future

One could easily create other global constants with Final (https://www.python.org/dev/peps/pep-0591/)

> So a good workaround for my case would be disabling that particular check.

You can do this on a per-file basis with `# pyre-ignore-all-errors[18]` (https://pyre-check.org/docs/gradual-typing.html#suppressing-specific-errors)
