### ISSUE TITLE
[Question] Can Pyre-check help in finding duplicate test cases

### ISSUE THREAD

**Issue by neomatrix369** [facebook/pyre-check#259]
Similar to the ideas expressed in the Refactoring query #188 I was thinking has anyone (or can it even be done) used Pyre-check to find duplicate test cases (for Python projects/tests).

I was thinking a duplicate test case would be traversing the same AST from start to finish (or nearly the same AST, give or take).

So if we ran a number of tests individually (or together) and kept a track of their pathways till they terminated, we could overlay them to say these tests are very similar, these are not, and better still if we can say the degree of similarity, or dissimilarity in their pathway can be seen in a heatmap (if we can create one).

I'm happy for discussions and would love to hear thoughts from the other developers working on and/or watching this repo.

If there are other solution(s) that already does something similar I would love to hear about them too.

**Comment by pradeep90** [comment]
I don't think we plan to support this. If you want to deal with AST-level information, I think you'd be better served with LibCST, as mentioned on #188.

I'm not aware of existing solutions for this.
