### ISSUE TITLE
source-directory is not added to the search-path

### ISSUE THREAD

**Issue by abadger** [facebook/pyre-check#263]
I'm not sure if this is a bug or intended behaviour.  I would have asked on an irc channel but couldn't find any such place in the documentation.  Sorry if I just missed that!

I am seeing a variety of symptoms which are all solved by putting the directory above the source-directory into search-path.  I'm not sure if all (or even any) of the symptoms are bugs or if they're considered just how pyre works.  I'm also not sure if my workaround is the correct thing to do or has unintended consequences so bear with me :-)

Here's the setup for some reproducers:
```
mkdir -p pyre-test/code
cd pyre-test

cat << EOF > code/collections.py
def test() -> None:
    print('here')
EOF

cat << EOF > code/relative.py
from .collections import test
test()
EOF

cat << EOF > code/absolute.py
from code.collections import test
test()
EOF

touch code/__init__.py
```

Now... when I run pyre on the code directory I get this:
```
pyre --source-directory code
No watchman binary found. 
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install.html
Defaulting to non-incremental check.
Setting up a `.pyre_configuration` with `pyre init` may reduce overhead.
 ƛ Found 3 type errors!
code/absolute.py:1:0 Undefined import [21]: Could not find a module corresponding to import `code.collections`.
code/absolute.py:2:0 Undefined attribute [16]: Module `code` has no attribute `collections`.
code/relative.py:2:0 Undefined attribute [16]: Module `collections` has no attribute `test`.
```

The workaround I've come up with is to specify the directory that code/ exists in into the search-path by invoking pyre like this:
```
pyre --source-directory code --search-path $(pwd)
```

I'm not sure if that's intended or not, though.  For absolute imports it makes some sense to me since `code` isn't in a search path already.  But for relative imports, it seems odd that that pyre flags it.  If you move the code one directory level deeper like this:
```
code
├── __init__.py
└── subdir
    ├── absolute.py
    ├── collections.py
    ├── __init__.py
    └── relative.py
```

Then the relative import inside of relative.py does not get flagged by pyre.

On the other hand, if the relative import in the subdir had to go up to the top level the pyre will flag it:
```
# code/subdir/relative_upper.py
from ..collections import test
print('test')
```

So all this seems to have an internal logic... Something along the lines of the code directory not being registered as a python package for pyre and so anything that attempts to import from a python module in there will get flagged as a type checking error.  I just don't know if that's intentional and explicitly adding the --search-path to the directory above code is the intended solution or if at least some cases of that are expected to work.

**Comment by MaggieMoss** [comment]
@abadger  

Just curious - have you considered adding a `.pyre_configuration` where you could specify the search path and source directories? 

cc: @grievejia for questions about search paths

**Comment by grievejia** [comment]
@abadger 
- The `search_path` option is intended for external library code you do not control. Files that live under `search_path` will be looked up for class/function definitions but Pyre will never emit any type errors for them. Therefore if you want to see a file get checked by Pyre, you don't want to put its containing folder under `search_path`.
- The way absolute qualification works is that Pyre picks a root directory, and everything else is expanded from this root. In your example,
```
pyre_test
└── code
    ├── __init__.py
    └── subdir
        ├── __init__.py
        ├── absolute.py
        ├── collections.py
        └── relative.py
```
If `pyre_test` is picked as root, then the absolute module path of `collections` would be `code.subdir.collections`. If `pyre_test/code` is picked as root, then the absolute module path of `collections` becomes `subdir.collections`. 

When you run `pyre --source-directory XXX`, Pyre would use `XXX` as the root. That would explain why referencing `collections` with the `code` prefix won't work if you use the `code` directory itself as the source directory. If you want to keep the `code` prefix, pass the parent directory to `--source-directory`. 

- Regarding the relative import -- I believe if this is the filesystem structure you have:
```
code
├── __init__.py
└── subdir
    ├── absolute.py
    ├── collections.py
    ├── __init__.py
    └── relative.py
```
and if this is the content of `relative.py`:
```
from ..collections import test
```
Then you'll actually hit a runtime import error when running `python code/subdir/relative.py`.

Importing from the package (i.e. `from package import XXX`) is only guaranteed to work  at runtime when the importing file is *not* part of the imported package. In that sense, I think `pyre` is correct to warn there. If you want to import `collections.test` in `relative.py`, the best practice is `from .collections import test`.

**Comment by abadger** [comment]
@grievejia Thanks!  Okay, I'll just need to move the code I'm checking into a subdirectory, then.   Out of curiousity, is there a reason that pyre does it this way?  It seems like all other linting tools (mypy, pylint, flake8, etc) allow you to specify the toplevel-python-module-to-check from the command line rather than a directory-containing-toplevel-python-modules-to-check.

* For the relative import, I should have written out the example in total rather than just writing out what I meant in English.  For that one, I was thinking of this directory structure:
```
code
├── __init__.py
├── collections.py
└── subdir
    ├── __init__.py
    └── relative_upper.py
```

That works fine when you do this: 'python3 -c 'from code.subdir import relative_upper; relative_upper.test()` which is how I see this directory structure (code is a python package in my current working directory) (but thanks to your explanation, I now know that pyre doesn't see it that way; it sees it as a directory on sys.path).

@MaggieMoss I haven't had much success modifying .pyre_configuration so, although I have one generated by pyre init, I don't try to modify it anymore (I've never been able to get the pyre warning about a configuration file reducing overhead to go away either... I just thought it was because I wasn't using watchman pyre was getting confused).  The modifications I was making were attempts to create a generic .pyre_configuration that I could check into my repository, though, which is probably a harder problem than simply configuring it to optimise how pyre is used on just my laptop.

This is how I have been invoking pyre in my real code base: `poetry run pyre --source-directory ansibulled  --search-path $(poetry run python -c 'from distutils.sysconfig import get_python_lib;print(get_python_lib())') --search-path stubs/ --search-path .`  I'll have to rearrange my code so that I can do something like `poetry run pyre --source-directory lib  --search-path $(poetry run python -c 'from distutils.sysconfig import get_python_lib;print(get_python_lib())') --search-path stubs/` instead.  I can stick source-directory into .pyre_configuration then.  I'm not sure how to stick search-patch in there, though.  The shell command is what I use to get the virtualenv path where the libraries my project is using live.

This might be moot too... because my goal is to run this in ci and I couldn't find a good way to make .pyre_configuration generic enough to stick into my git repo, I have a shell script which encapsulates the `poetry run pyre [...]` command with all of its command line options.  I typically run that.

(I don't mean to pollute your issue tracker with more stuff that's specific to my environment, I just wanted to make sure I replied to all the questions you all asked :-)

**Comment by grievejia** [comment]
> Out of curiousity, is there a reason that pyre does it this way? It seems like all other linting tools (mypy, pylint, flake8, etc) allow you to specify the toplevel-python-module-to-check from the command line rather than a directory-containing-toplevel-python-modules-to-check.

Laziness 😆 

Jokes aside, I think the issue is that currently the code quality of the Pyre cli is in a sorry state. This adds unnecessarily friction when someone wants to add/change the cli's behavior. I do think that the request of adding a flag to set the toplevel module path is reasonable. It's just that it might take quite a while for it to happen :(

> For that one, I was thinking of this directory structure

To clarify: the new directory structure you proposed there is fine -- it won't error at runtime and Pyre won't complain on it. It would not be fine anymore if you move `collections.py` into `subdir` -- that would create an import loop at runtime in certain situations and hence Pyre would also warn on it.
