### ISSUE TITLE
Example of excluding test files

### ISSUE THREAD

**Issue by bigfoot31** [facebook/pyre-check#264]
the following config is not working
`exclude: ["test_.*"]`

**Comment by gbleaney** [comment]
@bigfoot31 could you try `exclude: [".*/test_.*"]`? If that doesn't work, could you provide a bit more information about the directory structure of your project? Maybe a sample of the output from `tree YOUR_DIRECTORY`?

**Comment by bigfoot31** [comment]
Working. Thank you
