### ISSUE TITLE
Install watchman link broken

### ISSUE THREAD

**Issue by pawelrubin** [facebook/pyre-check#265]
After **pyre-check** fails to find **whatchman** binary:
```shell
No watchman binary found. 
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install.html
Defaulting to non-incremental check.
```

Correct link is: [https://facebook.github.io/watchman/docs/install](https://facebook.github.io/watchman/docs/install)

**Comment by gbleaney** [comment]
@pawelrubin thanks for pointing that out! I've fixed the link now. You should see it in the repo soon, and it should be correct in the next release of pyre
