### ISSUE TITLE
Docs are out of date (querying pyre)

### ISSUE THREAD

**Issue by rvantonder** [facebook/pyre-check#268]
👋   frens

Docs mention `dump_dependencies` at  https://pyre-check.org/docs/querying-pyre.html. The [only reference](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/facebook/pyre-check%24+dump_dependencies&patternType=literal) to `dump_dependencies` are in the docs, so this doesn't look accurate. 

It looks like `dump_call_graph()` is a similar query that is valid. It would be nice to add that to the docs, and mention also that `pyre start` is required before `pyre query` works.

Not making a PR because I didn't check whether the other queries are still valid, so there should probably be a bigger sweep to check what is still valid on this page :-)

**Comment by shannonzhu** [comment]
Hey Rijnard! It's nice to hear from you, thanks for opening the issue. :) 
Linked an update - we're also expecting a more thorough revision and modernization of the documentation as a whole in the near future, so hopefully that'll help more generally where things are getting out of date.

**Comment by rvantonder** [comment]
Hey @shannonzhu. Thanks! Sure thing, I was just helping out some people who wanted to get started and noticed these.
