### ISSUE TITLE
Importing a library like 'gevent' resulting in global name is undefined

### ISSUE THREAD

**Issue by gvanderest** [facebook/pyre-check#27]
Hey there, this is likely similar to my previous question-- sorry if it's annoying! :-)

I use `gevent` in my project, and when running `pyre check` I get the following error:

```
 ƛ Found 1 type error!
mud/game.py:150:12 Undefined name [18]: Global name `gevent` is undefined.
```

I'm using a virtual environment, so I'm not sure if that should be specified as a location to look up libraries.. or if external libraries are supported.  If there is a code comment I can add to hint "stop looking in this direction" that might also be helpful.

Thanks for making pyre-check!

**Comment by dkgi** [comment]
@gvanderest: Pyre does expect all modules to be available in either stub or source form. By default it'll only look for typeshed stubs and the current directory. You can pass in more directories by setting `--search-path` or use your `PYTHONPATH` with `--preserve-pythonpath`. Depending on how much is in that path, performance might deteriorate though. We're working on the documentation for this right now.
