### ISSUE TITLE
PyPI Release (v0.0.47)

### ISSUE THREAD

**Issue by dirn** [facebook/pyre-check#271]
A tag was created for [v0.0.47] around June 4, 2020. Until this version has been
published to [PyPI], however, it can't easily be used by the projects that use
pyre for static analysis. Is there an ETA for when it might be made available?

[v0.0.47]: https://github.com/facebook/pyre-check/releases/tag/v0.0.47
[pypi]: https://pypi.org/p/pyre-check

**Comment by mathbunnyru** [comment]
It would be nice to have fresh release available for an easy install through pip.

**Comment by dirn** [comment]
I see that v0.0.48 was released a couple of days ago. Thanks.
