### ISSUE TITLE
`super` has no attribute

### ISSUE THREAD

**Issue by dirn** [facebook/pyre-check#277]
I'm working on adding a subclass of Django's [`DetailView`][detailview] to an
application. Because there isn't already a stub for it, I started working on
one as `stubs/django/views/generic/detail.pyi`.

```
# pyre-unsafe

from typing import List, Optional

from django.http import HttpRequest, HttpResponse
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View

class SingleObjectMixin(ContextMixin):
    def get_object(self, query_set=None): ...
    def get_queryset(self): ...
    def get_slug_field(self) -> str: ...
    def get_context_object_name(self, obj) -> Optional[str]: ...
    def get_context_data(self, **kwargs): ...

class BaseDetailView(SingleObjectMixin, View):
    def get(self, request: HttpRequest, *args, **kwargs) -> HttpResponse: ...

class SingleObjectTemplateResponseMixin(TemplateResponseMixin):
    template_name_field: Optional[str] = ...
    template_name_suffix: str = ...
    def get_template_name(self) -> List[str]: ...

class DetailView(SingleObjectTemplateResponseMixin, BaseDetailView):
    pass
```

My view provides its own implementation of [`get_context_data`][getcontextdata].
In it, I call the parent method.

```
context = super().get_context_data(**kwargs)
```

When I do this, however, I get an error when I run `pyre`.

```
Undefined attribute [16]: `super` has no attribute `get_context_data`.
```

If I change the line to

```
context = DetailView.get_context_data(self, **kwargs)
```

the type check passes. Do I need to do something to enable the use of `super`
here?

[detailview]: https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-display/#detailview
[getcontextdata]: https://docs.djangoproject.com/en/3.0/ref/class-based-views/mixins-single-object/#django.views.generic.detail.SingleObjectMixin.get_context_data

**Comment by pradeep90** [comment]
@dirn Thanks for the report. `super` should work as is, so this is unexpected. 

I wasn't able to repro the error with the following:

```
from typing import *

class Foo:
    def foo(self, **kwargs): ...
        
class Bar:
    def bar(): ...
        
class Child(Foo, Bar):
    pass

class GrandChild(Child):
    def something(self, **kwargs):
        super().foo(**kwargs)
```

Could you try minimizing your repro to see where the error might be?

Another option is to use `reveal_type` to see what Pyre thinks is the type of the variable (such as `reveal_type(super())`).

**Comment by dirn** [comment]
@pradeep90 I haven't had much computer time lately, but this is on my radar.

**Comment by domandinho** [comment]
@dirn Which version does this issue occurs? I've copied your example and run it on pyre-check==0.9.3 and there were no errors.

**Comment by dirn** [comment]
@domandinho well it was a year ago, so whatever was out at the time. To be honest, though, I stopped using pyre around that time so I couldn't tell you when it got fixed but since you say it is I'll close this.
