### ISSUE TITLE
Undefined import - boto3

### ISSUE THREAD

**Issue by tekumara** [facebook/pyre-check#279]
test.py:
```python
import boto3
import mypy_boto3_dynamodb as dynamodb

client: dynamodb.DynamoDBClient = boto3.client("dynamodb")
```

Running pyre check, it's not finding the boto modules:
```
test.py:1:0 Undefined import [21]: Could not find a module corresponding to import `boto3`.
test.py:2:0 Undefined import [21]: Could not find a module corresponding to import `mypy_boto3_dynamodb`.
test.py:4:8 Undefined or invalid type [11]: Annotation `dynamodb.DynamoDBClient` is not defined as a type.
```

Although they are located in the site-packages dir of the current virtualenv.

How do you configure pyre to find them?

**Comment by gbleaney** [comment]
Hey @tekumara, can you try adding your venv to your [`search_path` in your `.pyre_configuration` file](https://pyre-check.org/docs/configuration.html#persistent-configuration)?

**Comment by tekumara** [comment]
Thanks @gbleaney! 🙇‍♂️ I added my virtualenv's site-packages directory to search_path to fix this!
