### ISSUE TITLE
spurious "Impossible assertion [25]" with some dynamic isinstance checks

### ISSUE THREAD

**Issue by jesboat** [facebook/pyre-check#284]
When the right side of an isinstance is a variable, Pyre sometimes (I haven't tried to pin down the exact behavior) raises a spurious "Impossible assertion [25]" error. For example, on this file:

```
# pyre-strict

from typing import Type

def example(x: object, c: Type[object]) -> None:
    if isinstance(x, c):
        print("yes")
    else:
        print("no")

example(TypeError(), Exception)
example(42, Exception)
```

Pyre raises

```
src/x.py:6:7 Impossible assertion [25]: `x` has type `object`, assertion `not isinstance(x, c)` will always fail.
```

even though both cases are possible and, in fact, happen.

pyre 0.0.46 as macOS, as installed from pyre_check-0.0.46-py3-none-macosx_10_11_x86_64.whl. (Sorry for the report on the older version; unfortunately, it's obnoxious for me to try a newer one because reasons.)

**Comment by shannonzhu** [comment]
We've removed these impossible assertion errors for this reason in the latest release
