### ISSUE TITLE
Pyre can't find names using __getattr__

### ISSUE THREAD

**Issue by dirn** [facebook/pyre-check#286]
When trying to import from a module that uses `__getattr__` in its stub file, `pyre` can't find the name. For example

    from django.contrib.auth.decorators import login_required

results in

    Undefined import [21]: Could not find a name `login_required` defined in module `django.contrib.auth.decorators`.

This import worked prior to 5f1d94d7d29207974145427086bd7bb97f379155. I'm running into this in PyGotham/awards#78, but I'm able to reproduce this in a file that just contains the import.

**Comment by arthaud** [comment]
Hi @dirn, thanks for the report!

This is another bug in our stubs: we replaced placeholder stubs `# pyre-placeholder-stub` with `__getattr__() -> Any` where it should be `__getattr__(name: str) -> Any`. I will fix that soon.

**Comment by arthaud** [comment]
This should be fixed in 0dd5c8f1622b4d7f49b196e26b018c6f7de2297d. Thanks for the report :)
