### ISSUE TITLE
Specializing subclass type params to `None` errors spuriously

### ISSUE THREAD

**Issue by msullivan** [facebook/pyre-check#29]
When trying to typecheck mypy under pyre, I got a ton of type errors having to do with some of our visitors. I reduced it down to:
```
from typing import TypeVar, Generic

T = TypeVar('T')
class NodeVisitor(Generic[T]):
    def visit_foo(self) -> T:
        pass

class NodeVisitor(Generic[T]):
    def visit_foo(self) -> T:
        pass

# Works
class Bar(NodeVisitor[int]):
    def visit_foo(self) -> int:
        return 10

# Inconsistent override [15]: `visit_foo` overloads method defined in `foo.NodeVisitor` inconsistently.
class Foo(NodeVisitor[None]):
    def visit_foo(self) -> None:
        pass
```
Specializing the type parameter to `int` works, but specializing it to `None` fails.

**Comment by dkgi** [comment]
Nice catch :) I suspect our sub-typing consistency checks in general will be somewhat shaky around type variables.

**Comment by dkgi** [comment]
This should be fixed with https://github.com/facebook/pyre-check/commit/6da7cf59608adaf6c6098dfcb66f097c7ab6e475.
