### ISSUE TITLE
suggestion: provide example for exclude configuration

### ISSUE THREAD

**Issue by caleb15** [facebook/pyre-check#304]
I'm so used to using file globs for excluding that I tried that and was wondering why it wasn't working.

Re-reading the documentation I can see that it does say regexp, I should have paid more attention.

I would suggest making a explicit note of it (or better yet, providing an example of using exclude) so other people don't make the same assumption.

**Comment by caleb15** [comment]
For example I used `"exclude": [".*test.*"]` to exclude any test files / folders

**Comment by caleb15** [comment]
Actually even better example would be `".*\/node_modules\/.*"` because you would always want to exclude that.

**Comment by arthaud** [comment]
Hi @caleb15, thanks for reaching out.

This is something we are aware of and currently working on. Some options use a glob syntax while other use regexes. I believe we are trying to make this uniform and use the glob syntax for options.

**Comment by xmo-odoo** [comment]
Examples of non-trivial matches and / or a subcommand to dump the "run configuration" or something would also be useful, even knowing that these paths are regex and being told that it's matching against full paths getting these to work is not trivial. It would also be useful to know what dialect is involved to know whether features like backreferences are usable.

Maybe `pyre init` could prompt for files and folders to ignore, that way it could easily produce the correct syntax and therefore provide examples?

**Comment by gbleaney** [comment]
Sorry for the delay. I just started the land process to add the example to our docs. Thanks for the suggestion!
