### ISSUE TITLE
Exclude directive being ignored

### ISSUE THREAD

**Issue by darakian** [facebook/pyre-check#308]
Hey, I'm just trying to get started with pyre and it seems like the exclude directive isn't working. I've followed the getting started guide and noticed that the venv is being checked.
```
(venv) bash-5.0$ pyre init
 ƛ Also initialize a watchman configuration? [Y/n] Y
{
    "version": "4.9.0",
    "watch": "/Users/jon/tmp/test_pyre",
    "watcher": "fsevents"
}
 ƛ Which directory should pyre be initialized in? (Default: `.`):
(venv) bash-5.0$ echo "i: int = 'string'" > test.py
(venv) bash-5.0$ pyre
 ƛ Found 7643 type errors!
test.py:1:0 Incompatible variable type [9]: i is declared to have type `int` but is used as type `str`.
venv/lib/pyre_check/stubs/django/apps.pyi:1:21 Unbound name [10]: Name `Any` is used but not defined in the current scope.
venv/lib/pyre_check/stubs/django/conf/urls.pyi:5:0 Undefined import [21]: Could not find a module corresponding to import `django.core.urlresolv
...
```

I've tried moving the venv to `.venv` as it is in the guide and still it gets checked.
```
(.venv) bash-5.0$ pyre
 ƛ Found 7657 type errors!
.venv/lib/pyre_check/stubs/django/apps.pyi:1:21 Unbound name [10]: Name `Any` is used but not defined in the current scope.
.venv/lib/pyre_check/stubs/django/conf/urls.pyi:5:0 Undefined import [21]: Could not find a module corresponding to import `django.core.urlresolvers`.
...
```
and I've tried adding it to the exclude path
```
{
  "binary": "/Users/jon/tmp/test_pyre/.venv/bin/pyre.bin",
  "source_directories": [
    "."
  ],
  "exclude": [
    ".venv/*"
  ],
...
```

Still I see the venv being checked. Am I missing something basic?

**Comment by sinancepel** [comment]
The regex syntax is a bit different from what you might expect, could you instead try the following for the exclude? 

`.*/.venv/.*`?

**Comment by darakian** [comment]
That seems to have fix it. Thanks!

**Comment by yamin-oanda** [comment]
I am facing the same issue with the following `.pyre_configuration`:

```
{
  "source_directories": [
    "."
  ],
  "taint_models_path": ".../.py3dev/lib",
  "exclude": [".*/.py3dev/.*"]
}
```

```
$ pyre --version
ƛ Using virtual environment site-packages in search path...
Binary version: a50cc697c030f43cdab575dbc64a0ae5add656a7
Client version: 0.9.8

$ pyre
...tons of errors all in .py3dev...
```

The [Configuration](https://pyre-check.org/docs/configuration) page shows the regex with slashes preceded by backslashes. I tried that: `"exclude": [".*\/.py3dev\/.*"]`, no effect.

What is the correct regex to use here?

**Comment by Vishnu-Naik** [comment]
Technically, there is no problem with your regex and it should work as intended. Only issue I can think of is you might have not restarted the pyre, the command `pyre` doesn't seems to be taking updated `.pyre-configuration`, may be due to watchman package not working or not installed in your project. Hence I would suggest you to restart pyre to take your updated `.pyre-configuration` by executing the below command
```
pyre restart
```
Try restarting pyre whenever you seem to make changes to `.pyre-configuration`.
