### ISSUE TITLE
Running individual tests

### ISSUE THREAD

**Issue by theodoretliu** [facebook/pyre-check#309]
The `CONTRIBUTING.md` document states that single tests can be run with `dune exec filename.exe`. I tried running `dune exec analysis/test/integration/annotationTest.exe` but I'm getting 19 failures and errors. Is there an updated way to run single files?

**Comment by MaggieMoss** [comment]
Could you try:

```
OUNIT_SHARDS="1" dune exec analysis/test/integration/methodTest.exe
```

And let me know if that still doesn't work for you?

**Comment by OlivierNicole** [comment]
I confirm this has made individual tests work for me.
