### ISSUE TITLE
Allow running Pyre without a configuration

### ISSUE THREAD

**Issue by pradeep90** [facebook/pyre-check#317]
In v0.52 and before, when there was no configuration file, Pyre used to build a one-off configuration using the CLI arguments. 

We seem to have regressed that with https://github.com/facebook/pyre-check/commit/213f5805abf729990efa652aa7c5fc9c8798d0d4.

Following up from TomMD's comment in https://github.com/facebook/pyre-check/issues/315#issuecomment-695024261:

> Situation Details
>
> It used to be possible to call git clone $some_repo path ; cd path ; pyre --noninteractive --source-directory . --output json but now a pyre configuration is required. Perhaps that behavior was intentionally changed, but printf "\n" | pyre init is broken in the manner mentioned above which makes Pyre unusable.

#316 may be also be related.

**Comment by cooperlees** [comment]
I feel this is part of helping make #316 (venv support) friendlier / usable again too.

**Comment by pradeep90** [comment]
@cooperlees Just to make sure this is not the only blocker for your venv scenario, can you try with 0.0.52?

**Comment by grievejia** [comment]
Closing this since it has been fixed since v0.0.57

**Comment by TomMD** [comment]
And 0.0.57 works well for me - thank you all.
