### ISSUE TITLE
Is it possible to complement typeshed?

### ISSUE THREAD

**Issue by xmo-odoo** [facebook/pyre-check#327]
Say typeshed is lacking some definitions, either because it's not been merged yet or because they're not really interested in merging that definition (e.g. something which is half-public half-internal).

Is there a way to provide complementary definitions for packages typeshed already has but is not complete for? Or is providing a typeshed fork a requirement?

**Comment by gbleaney** [comment]
@xmo-odoo you can selectively override stubs in typeshed by adding them to your [`search_path` in `.pyre_configuration`](https://pyre-check.org/docs/configuration#the-global-configuration). For example, typeshed provides a [`dataclasses`](https://github.com/python/typeshed/blob/master/third_party/3/dataclasses.pyi) stub, which you could replace with your own by adding a `dataclasses.pyi` file to the top level of any directory listed in your `search_path`. Unfortunately, Pyre won't merge the stubs, so you'd have to override file-by-file.

You should be able to compliment typeshed, however, in cases where a `.pyi` file doesn't exist. For example, let's say that [`six.moves` in typeshed](https://github.com/python/typeshed/tree/master/third_party/3/six/moves) is incomplete. If you added `six/moves/foo.pyi` to your search path, Pyre would look there for imports from `six.moves.foo`, but fall back to typeshed for all other imports from `six`.

**Comment by xmo-odoo** [comment]
@gbleaney So can either implement things typeshed doesn't provide or vendor specific files from typeshed and update them internally, without having to vendor all of typeshed. Seems suitable, thanks!
