### ISSUE TITLE
Undefined attribute [16] - Iterable[typing.Any] has no attribute

### ISSUE THREAD

**Issue by feluxe** [facebook/pyre-check#34]
The following code produces some type mismatches (see comments inside the list comprehension at the end).

```python
from typing import Iterable, Tuple, List
import time


class Record(object):

    def __init__(
        self,
        parents: List[int] = [],
        tags: List[str] = [],
        owners: List[str] = [],
    ):
        self.parents = parents
        self.tags = tags
        self.owners = owners


def _insert(*records: Iterable[Record],
            name='records') -> Tuple[str, List[str]]:

    query = 'foo'

    values = [[
        r.parents,   # Error: [Pyre] Undefined attribute [16]: `Iterable[typing.Any]` has no attribute `parents`.
        r.tags,   # Error: [Pyre] Undefined attribute [16]: `Iterable[typing.Any]` has no attribute `tags`.
        r.owners,  # Error: [Pyre] Undefined attribute [16]: `Iterable[typing.Any]` has no attribute `owners`.
    ] for r in records]

    return query, values

```

I fiddled with this for a while, but I couldn't find a solution. Is this a bug, or am I doing it the wrong way?

**Comment by sinancepel** [comment]
When you type `*records` as an `Iterable[Record]`, pyre thinks that `records` has type `Iterable[Iterable[Record]]`. In general, you only need to specify the type of one argument for starred and keyword arguments, so try annotating it as `*records: Record`. Hope that helps!

**Comment by feluxe** [comment]
@sinancepel Thanks for your reply! 

It still doesn't work. I don't understand why it says `Iterable[typing.Any]` has no attribute `parents`.  Where does it get the `Iterable[typing.Any]` from?
