### ISSUE TITLE
Getting weird error from sexp.ml when running pyre analyze

### ISSUE THREAD

**Issue by abekang** [facebook/pyre-check#344]
I am scanning a pretty big project.

Getting the following:

ƛ Raised at file "string.ml", line 115, characters 19-34
ƛ Called from file "src/sexp.ml", line 113, characters 13-47
ƛ Client exited with error code 1

Looked everywhere for the sexp.ml and could not find it.

Anyone have a clue what is going on.  Another person is having a similar issue when creating models for Tensorflow.

**Comment by yangdanny97** [comment]
stale + not reproducible, closing for now. please reopen if this still affects you
