### ISSUE TITLE
Fails to detect type errors

### ISSUE THREAD

**Issue by ftruter** [facebook/pyre-check#345]
No error or warnings are generated on this code. Expected "incompatible types" warning at least on the line with exclamations.

```
from typing import *

def test():
  d: Dict[str, int] = dict(a=1, b=2)
  print('init', repr(d))
  d['a'] *= 10
  d['b'] += 45
  boo = False
  d[1] = 'Hello' # incorrect types!!
  print('done', repr(d))

test()

```

Some more info
```
me ~/projects/failures/pyre> pyre --version && python --version && pyre --strict
Binary version: 857747d8246cde76501481378a6b7cf2e7072a2c
Client version: internal-dev
Python 2.7.17
ƛ No type errors found
```

**Comment by pradeep90** [comment]
Pyre ignores functions that don't have an explicit return type annotation ([docs](https://pyre-check.org/docs/types-in-python#gradual-typing)). Making it `def test() -> None:` will show the error message you were looking for.
