### ISSUE TITLE
pyre analyze runtime exception: Analysis__ClassHierarchy.Untracked(_)

### ISSUE THREAD

**Issue by anniecherk** [facebook/pyre-check#350]
I'm running into a runtime error when I run `pyre analyze` over a fairly large codebase. 

I've built `pyre` from source to help debug the problem, and aliased it from `pyre-check/source/_build/default/main.exe`. This is the version:

```
> pyre --version
6a0fc0ab1cb38369f0e09399aa29ca2723cdb616
```

When I run `pyre analyze -debug -verbose`, it crashes with this backtrace:
```
Worker exited (code: 2)
2020-12-07 13:50:22 ERROR Uncaught exception: (exn.ml.Finally ("Worker.Worker_exited_abnormally(9370, _)")
  (Unix.Unix_error "No such process" kill ""))
Uncaught exception:

  (exn.ml.Finally ("Worker.Worker_exited_abnormally(9370, _)")
   (Unix.Unix_error "No such process" kill ""))

Raised at file "command/analyzeCommand.ml", line 206, characters 6-17
Called from file "src/command.ml", line 2453, characters 8-238
Called from file "src/exn.ml", line 111, characters 6-10
Worker interrupted with signal: sigpipe
Exception: Analysis__ClassHierarchy.Untracked(_)
Potential backtrace:
Raised at file "analysis/classHierarchy.ml", line 116, characters 4-49
Called from file "analysis/classHierarchy.ml", line 304, characters 2-35
Called from file "analysis/constraintsSet.ml", line 626, characters 27-92
Called from file "src/list.ml", line 636, characters 34-40
Called from file "analysis/typeOrder.ml", line 38, characters 6-296
Called from file "analysis/typeOrder.ml", line 178, characters 15-54
Called from file "src/option.ml", line 236, characters 27-34
Called from file "analysis/analysisError.ml", line 2749, characters 19-75
Called from file "analysis/analysisError.ml", line 2811, characters 32-68
Called from file "analysis/analysisError.ml", line 3188, characters 31-68
Called from file "src/hashtbl.ml", line 450, characters 41-56
Called from file "analysis/analysisError.ml", line 3194, characters 6-55
Called from file "list.ml", line 121, characters 24-34
Called from file "src/list0.ml" (inlined), line 21, characters 22-52
Called from file "analysis/analysisError.ml", line 3206, characters 24-62
Called from file "src/list.ml", line 636, characters 34-40
Called from file "analysis/postprocessing.ml" (inlined), line 124, characters 5-76
Called from file "analysis/postprocessing.ml", line 123, characters 2-137
Called from file "analysis/postprocessing.ml", line 136, characters 2-76
Called from file "src/list.ml", line 636, characters 34-40
Called from file "analysis/postprocessing.ml", line 199, characters 25-65
Called from file "service/scheduler.ml", line 129, characters 17-27
Re-raised at file "service/scheduler.ml", line 133, characters 13-24
Called from file "hack_parallel/hack_parallel/procs/worker.ml", line 328, characters 34-44
Called from file "hack_parallel/hack_parallel/procs/worker.ml", line 171, characters 4-37
```

The top line of the backtrace references the `raise` in the function [raise_if_untracked](https://github.com/facebook/pyre-check/blob/master/source/analysis/classHierarchy.ml#L115). 

When I replace `raise (Untracked (Type.Primitive annotation))` with a print statement and recompile, `pyre analyze` runs to completion. I was surprised to see the print statement printed many times; I'm guessing that exception must often be handled and I'm hitting some case where it is unhandled and so causes a runtime error.

The second line of the backtrace references a call to `raise_if_untracked` in the [instantiate_successors_parameters](https://github.com/facebook/pyre-check/blob/master/source/analysis/classHierarchy.ml#L300) function. I added print statements just above the call:
```
  print_endline (Type.show source);
  print_endline (Type.Primitive.show_primitive_t target); 
```

When I recompile pyre and run `pyre analyze -debug -verbose -sequential`, the last two prints I see are:
```
typing.List[typing.Any]
list
```

Those don't seem immediately suspicious, and they also aren't particularly helpful for identifying what part of the codebase-under-analysis might be causing the crash.

I looked through the functions lower down in the backtrace but I don't have the context to understand if / where I could add more print statements to help debug what's going on and how it correlates with the codebase-under-analysis. 

Do you have any advice about what I should do to get more info about why this crash is happening?

**Comment by anniecherk** [comment]
Adjusting the settings in my `.pyre_configuration` file fixed this problem! I'm still unsure of why it was crashing, but it's no longer a problem for me, so I'm going to close this issue.

**Comment by angelinag** [comment]
@anniecherk Hello, can I take a look at your `.pyre_configuration`? We have the same exact issue and we need to fix it urgently, our demo is tomorrow.
