### ISSUE TITLE
ModuleNotFoundError: No module named 'pyre-check'

### ISSUE THREAD

**Issue by apurvjain17** [facebook/pyre-check#376]
Hi 

I am using python3.8 and have all the dependencies installed using` python3.8 -m pip install <package-name>`

I was following the tutorials in the git repo whenever I am running `python3.8 generate_models.py --output-directory .` the shell throws an error `ModuleNotFoundError: No module named 'pyre-check'`, even though I've tried install pyre-check using multiple different ways.

Please help!

Thanks.

**Comment by apurvjain17** [comment]
Logs after installing pyre-check
`$ python3.8 -m pip install pyre-check
Requirement already satisfied: pyre-check in /usr/lib/python3.8/site-packages (0.0.59)
Requirement already satisfied: pywatchman in /usr/lib/python3.8/site-packages (from pyre-check) (1.4.1)
Requirement already satisfied: click in /usr/lib/python3.8/site-packages (from pyre-check) (7.1.2)
Requirement already satisfied: dataclasses in /usr/lib/python3.8/site-packages (from pyre-check) (0.6)
Requirement already satisfied: psutil in /usr/lib/python3.8/site-packages (from pyre-check) (5.8.0)
Requirement already satisfied: dataclasses-json in /usr/lib/python3.8/site-packages (from pyre-check) (0.5.2)
Requirement already satisfied: pyre-extensions in /usr/lib/python3.8/site-packages (from pyre-check) (0.0.20)
Requirement already satisfied: libcst>=0.3.6 in /usr/lib/python3.8/site-packages (from pyre-check) (0.3.16)
Requirement already satisfied: fb-sapp in /usr/lib/python3.8/site-packages (from pyre-check) (0.2.8)
Requirement already satisfied: typing-inspect>=0.4.0 in /usr/lib/python3.8/site-packages (from dataclasses-json->pyre-check) (0.6.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in /usr/lib/python3.8/site-packages (from dataclasses-json->pyre-check) (3.10.0)
Requirement already satisfied: marshmallow-enum<2.0.0,>=1.5.1 in /usr/lib/python3.8/site-packages (from dataclasses-json->pyre-check) (1.5.1)
Requirement already satisfied: stringcase<2.0.0,==1.2.0 in /usr/lib/python3.8/site-packages (from dataclasses-json->pyre-check) (1.2.0)
Requirement already satisfied: click in /usr/lib/python3.8/site-packages (from pyre-check) (7.1.2)
Requirement already satisfied: flask in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (1.1.2)
Requirement already satisfied: SQLAlchemy in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (1.3.22)
Requirement already satisfied: click-log in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (0.3.2)
Requirement already satisfied: munch in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (2.5.0)
Requirement already satisfied: graphene in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (2.1.8)
Requirement already satisfied: pygments in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (2.7.4)
Requirement already satisfied: prompt-toolkit in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (2.0.10)
Requirement already satisfied: graphene-sqlalchemy in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (2.3.0)
Requirement already satisfied: flask-graphql in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (2.0.1)
Requirement already satisfied: ipython in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (7.6.1)
Requirement already satisfied: ujson in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (1.35)
Requirement already satisfied: pyre-extensions in /usr/lib/python3.8/site-packages (from pyre-check) (0.0.20)
Requirement already satisfied: typing-extensions in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (3.7.4.3)
Requirement already satisfied: xxhash in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (1.3.0)
Requirement already satisfied: click in /usr/lib/python3.8/site-packages (from pyre-check) (7.1.2)
Requirement already satisfied: click in /usr/lib/python3.8/site-packages (from pyre-check) (7.1.2)
Requirement already satisfied: Werkzeug>=0.15 in /usr/lib/python3.8/site-packages (from flask->fb-sapp->pyre-check) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/lib/python3.8/site-packages (from flask->fb-sapp->pyre-check) (1.1.0)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/lib/python3.8/site-packages (from flask->fb-sapp->pyre-check) (2.11.3)
Requirement already satisfied: flask in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (1.1.2)
Requirement already satisfied: graphql-server-core<2,>=1.1 in /usr/lib/python3.8/site-packages (from flask-graphql->fb-sapp->pyre-check) (1.2.0)
Requirement already satisfied: graphql-core<3,>=2.1 in /usr/lib/python3.8/site-packages (from flask-graphql->fb-sapp->pyre-check) (2.3.2)
Requirement already satisfied: aniso8601<=7,>=3 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (7.0.0)
Requirement already satisfied: graphql-relay<3,>=2 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (2.0.1)
Requirement already satisfied: graphql-core<3,>=2.1 in /usr/lib/python3.8/site-packages (from flask-graphql->fb-sapp->pyre-check) (2.3.2)
Requirement already satisfied: six<2,>=1.10.0 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (1.15.0)
Requirement already satisfied: singledispatch<4,>=3.4.0.3 in /usr/lib/python3.8/site-packages (from graphene-sqlalchemy->fb-sapp->pyre-check) (3.4.0.3)
Requirement already satisfied: graphene in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (2.1.8)
Requirement already satisfied: promise>=2.3 in /usr/lib/python3.8/site-packages (from graphene-sqlalchemy->fb-sapp->pyre-check) (2.3)
Requirement already satisfied: SQLAlchemy in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (1.3.22)
Requirement already satisfied: six<2,>=1.10.0 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (1.15.0)
Requirement already satisfied: promise>=2.3 in /usr/lib/python3.8/site-packages (from graphene-sqlalchemy->fb-sapp->pyre-check) (2.3)
Requirement already satisfied: rx<2,>=1.6 in /usr/lib/python3.8/site-packages (from graphql-core<3,>=2.1->flask-graphql->fb-sapp->pyre-check) (1.6.1)
Requirement already satisfied: six<2,>=1.10.0 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (1.15.0)
Requirement already satisfied: promise>=2.3 in /usr/lib/python3.8/site-packages (from graphene-sqlalchemy->fb-sapp->pyre-check) (2.3)
Requirement already satisfied: six<2,>=1.10.0 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (1.15.0)
Requirement already satisfied: graphql-core<3,>=2.1 in /usr/lib/python3.8/site-packages (from flask-graphql->fb-sapp->pyre-check) (2.3.2)
Requirement already satisfied: promise>=2.3 in /usr/lib/python3.8/site-packages (from graphene-sqlalchemy->fb-sapp->pyre-check) (2.3)
Requirement already satisfied: graphql-core<3,>=2.1 in /usr/lib/python3.8/site-packages (from flask-graphql->fb-sapp->pyre-check) (2.3.2)
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python3.8/site-packages (from ipython->fb-sapp->pyre-check) (51.0.0.post20201207)
Requirement already satisfied: jedi>=0.10 in /usr/lib/python3.8/site-packages (from ipython->fb-sapp->pyre-check) (0.18.0)
Requirement already satisfied: traitlets>=4.2 in /usr/lib/python3.8/site-packages (from ipython->fb-sapp->pyre-check) (5.0.5)
Requirement already satisfied: pygments in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (2.7.4)
Requirement already satisfied: backcall in /usr/lib/python3.8/site-packages (from ipython->fb-sapp->pyre-check) (0.2.0)
Requirement already satisfied: pexpect in /usr/lib/python3.8/site-packages (from ipython->fb-sapp->pyre-check) (4.8.0)
Requirement already satisfied: appnope in /usr/lib/python3.8/site-packages (from ipython->fb-sapp->pyre-check) (0.1.2)
Requirement already satisfied: prompt-toolkit in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (2.0.10)
Requirement already satisfied: pickleshare in /usr/lib/python3.8/site-packages (from ipython->fb-sapp->pyre-check) (0.7.5)
Requirement already satisfied: decorator in /usr/lib/python3.8/site-packages (from ipython->fb-sapp->pyre-check) (4.4.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/lib/python3.8/site-packages (from jedi>=0.10->ipython->fb-sapp->pyre-check) (0.8.1)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.8/site-packages (from Jinja2>=2.10.1->flask->fb-sapp->pyre-check) (1.1.1)
Requirement already satisfied: typing-inspect>=0.4.0 in /usr/lib/python3.8/site-packages (from dataclasses-json->pyre-check) (0.6.0)
Requirement already satisfied: typing-extensions in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (3.7.4.3)
Requirement already satisfied: pyyaml>=5.2 in /usr/lib/python3.8/site-packages (from libcst>=0.3.6->pyre-check) (5.4.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.3.0 in /usr/lib/python3.8/site-packages (from dataclasses-json->pyre-check) (3.10.0)
Requirement already satisfied: six<2,>=1.10.0 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (1.15.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/lib/python3.8/site-packages (from pexpect->ipython->fb-sapp->pyre-check) (0.7.0)
Requirement already satisfied: six<2,>=1.10.0 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (1.15.0)
Requirement already satisfied: six<2,>=1.10.0 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (1.15.0)
Requirement already satisfied: wcwidth in /usr/lib/python3.8/site-packages (from prompt-toolkit->fb-sapp->pyre-check) (0.2.5)
Requirement already satisfied: typing-inspect>=0.4.0 in /usr/lib/python3.8/site-packages (from dataclasses-json->pyre-check) (0.6.0)
Requirement already satisfied: typing-extensions in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (3.7.4.3)
Requirement already satisfied: six<2,>=1.10.0 in /usr/lib/python3.8/site-packages (from graphene->fb-sapp->pyre-check) (1.15.0)
Requirement already satisfied: ipython-genutils in /usr/lib/python3.8/site-packages (from traitlets>=4.2->ipython->fb-sapp->pyre-check) (0.2.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/lib/python3.8/site-packages (from typing-inspect>=0.4.0->dataclasses-json->pyre-check) (0.4.3)
Requirement already satisfied: typing-extensions in /usr/lib/python3.8/site-packages (from fb-sapp->pyre-check) (3.7.4.3)`

**Comment by gbleaney** [comment]
@apurvjain17 thanks for the bug report! It looks like we changed the structure of the `pyre-check` PyPI package in the latest release, and that's affecting the lookup of the module that `generate_models.py` is trying to import. I'm looking into it and will let you know when we have a fix.

**Comment by gbleaney** [comment]
Fix is landed. If you pull the latest master branch, the exercise should be working for you again. Thanks again for letting us know, and please re-open/open another issue if anything else comes up!
