### ISSUE TITLE
Function definition does not override signature of imported function

### ISSUE THREAD

**Issue by ggoossen** [facebook/pyre-check#380]
```
from math import *

def exp(x: str) -> None:
    pass

exp("str")
```

Pyre incorrect detect a type error:
```
Incompatible parameter type [6]: Expected `typing.SupportsFloat` for 1st positional only parameter to call `math.exp` but got `str`.
```

Expected behaviour is that is uses the type signature from the new function, and thus correctly not detect any type error.

Using Pyre version 0.0.59

**Comment by arthaud** [comment]
Hi @ggoossen,

Pyre is an opinionated type checker, and does not accept overriding existing symbols. This can be avoided here by using `import math` or `from math import exp as math_exp`. In general, we try to avoid wildcard imports.
