### ISSUE TITLE
Running pyre with virtuelenv under source directories

### ISSUE THREAD

**Issue by cdonovick** [facebook/pyre-check#383]
I am trying to get to pyre to run when the virtuel env directory is under the root directory of a project.  
My typical file structure is something like:
```
project/
   project/
      __init__.py
      ...
   setup.py
   README.md
   ...
   project-env/
```
Now I want to add a `.pyre_configuration` to `project/`:
```
{
  "source_directories": [
    "."
  ],
  "search_path": [
    "./project-env/lib/python3.9/site-packages"
  ]
}
```
But because `./project-env/` is under `.` this results pyre trying to type check everything.

If I change `source_directories` to `"./project/"` then pyre doesn't understand `import project` and I get errors like:
`Undefined import [21]: Could not find a module corresponding to import 'project'`

If I add `"."` to `search_path` it resolves the issue with `import project` but seems to cause pyre to lose track of builtins and I get errors like:
`Undefined import [21]: Could not find a module corresponding to import 'abc'`

Is there anyway to resolve this?

**Comment by arthaud** [comment]
Hi @cdonovick,

You have two solutions (but actually, only one works?):
* You could put the `.pyre_configuration` in `project/project/` and have `../project-env/` in the search path
* In theory, you should be able to use `{"root": "x", "subdirectory": "y"}` inside `"source_directories"` but I have no idea how that works, and this is not documented.

**Comment by dkgi** [comment]
I've tried the root/subdirectory combination on SAPP just now and this seems to work: https://github.com/facebook/sapp/pull/9/files

Definitely missing documentation though.

@cdonovick: could you give this a try?

**Comment by dkgi** [comment]
Never mind my suggestion, it does not make sense. I think the reasonable suggestion here is to not put the virtual environment in the project directory.

**Comment by arthaud** [comment]
Hey @cdonovick,

If you use the `pyre-check-nightly` package instead of `pyre-check`, you can use:
```
  "source_directories": [
    {"root": ".", "subdirectory": "project"},
  ]
```
in your `.pyre_configuration` file at the root of your repository, and that should exclude errors from the virtual environment.

Please let us know if that worked.

**Comment by cdonovick** [comment]
@arthaud This worked! thanks.
