### ISSUE TITLE
type alias breaks pyre-check

### ISSUE THREAD

**Issue by CapCap** [facebook/pyre-check#392]
We are trying to use mypy-protobuf to generate types for our pb, and are running into a problem where pyre is unhappy with `builtins.int` not being a type, even though `builtins.int === int`, and using just `int` works fine (except this is generated code)

**Comment by Phil305** [comment]
@CapCap This issue also happens for me when, but under slightly different condition.
I'm getting an error when I do either of these:
```
SpotifyClientId: TypeAlias = NewType("SpotifyClientId", str)

SpotifyClientSecret = NewType("SpotifyClientSecret", str)
```

Error msg:
`Undefined or invalid type [11]: Annotation `auth.SpotifyClientId` is not defined as a type`

Pyre definitely should be able to handle an explicitly defined new type alias, this is surprising behavior, yeah?

**Comment by yangdanny97** [comment]
Closing because this error no longer repros in the playground, builtins.int seems to work if builtins is imported

https://pyre-check.org/play?input=import%20builtins%0Ax%3A%20builtins.int%20%3D%201
