### ISSUE TITLE
Fails basic typing.List[x] check

### ISSUE THREAD

**Issue by Ran4** [facebook/pyre-check#40]
`src/foo.py`:

```python3
#!/usr/bin/env python3
from typing import List

def f(s: str) -> List[int]:
    return [ch for ch in s]

assert f("foo") == ["f", "o", "o"]
```

The code should fail typechecking, since `f` returns a `List[str]` but is annotated as returning `List[int]`.

Output from pyre and mypy respectively:

```
$ pyre check
    No type errors found
$ mypy src
src/foo.py:4: error: List comprehension has incompatible type List[str]; expected List[int]
```

**Comment by compyman** [comment]
@Ran4 just a note - strict mode catches this (the comprehension types as List[Any] instead of List[int]
```python
# pyre-strict
from typing import List

def f(s: str) -> List[int]:
    return [ch for ch in s]

assert f("foo") == ["f", "o", "o"]
```

```bash
$ pyre check
 ƛ Found 1 type error!
test.py:6:4 Incompatible return type [7]: Expected `List[int]` but got `List[typing.Any]`.
```

**Comment by shannonzhu** [comment]
Working on this! Looks like the problem is due to an edge case in our typeorder join, where we're not instantiating type variables early enough in the case both original types are not parametric.
