### ISSUE TITLE
Cannot import pyre_extensions

### ISSUE THREAD

**Issue by mrahtz** [facebook/pyre-check#408]
Hi all,

I'm having some trouble getting Pyre to import `pyre_extensions`:

```
$ pyre --version
Binary version: 978e5ed739267ed3f3388961e1cbb47f9fdf8635
Client version: internal-dev
$ echo 'import pyre_extensions' > foo.py
$ pyre init
$ pyre check
ƛ Found 1 type error!
foo.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pyre_extensions`.
```

I notice that if I add my `site-packages` directory to Pyre's `search_path`, then everything is fine:

```
$ cat .pyre_configuration
{
  "source_directories": [
    "."
  ],
  "search_path": [
    "/home/mrahtz/.local/lib/python3.8/site-packages"
  ]
}
$ pyre check
ƛ No type errors found
```

I see in [examples/pytorch/.pyre_configuration](https://github.com/facebook/pyre-check/blob/e3394e1eb74751bf58283a961cd9383007b29823/documentation/examples/pytorch/.pyre_configuration) this should also be possible with `"site-package": "pyre_extensions"`, but...

```
$ cat .pyre_configuration
{
  "source_directories": [
    "."
  ],
  "search_path": [
    {
      "site-package": "pyre_extensions"
    }
  ]
}
$ $ pyre rage 2> /dev/null | grep pyre_extensions
2021-04-12 22:02:43,399 [PID 1163402] DEBUG Filtering out nonexistent search path: /usr/local/lib/python3.9/dist-packages/pyre_extensions
2021-04-12 22:02:43,399 [PID 1163402] DEBUG Filtering out nonexistent search path: /usr/lib/python3/dist-packages/pyre_extensions
2021-04-12 22:02:43,399 [PID 1163402] DEBUG Filtering out nonexistent search path: /usr/lib/python3.9/dist-packages/pyre_extensions
```

So...Pyre is looking in `dist-packages`, when it should be looking in `site-packages`?

(This is on Ubuntu 20.04.2, with Python 3.8.5, if relevant.)

Thanks!

**Comment by mrahtz** [comment]
Welp, my workaround ended up...not working...so I dug into this a bit more.

It looks like the issue is the use of `site.getsitepackages()`. If I change `_get_site_roots` in `client/configuration.py` to:

```python3
def _get_site_roots() -> List[str]:
    try:
        return site.getsitepackages() + [site.getusersitepackages()]
```

Then it works fine. Is it a deliberate assumption that `pyre_extensions` is installed in the global site-packages directory, as opposed to the user site-packages directory?

(@grievejia, since I notice you were the last one to change this line in the git blame 😸)

**Comment by grievejia** [comment]
@mrahtz Thank you so much for the digging! TIL there's a user-specific site package dir. I typically run Pyre in a dedicated venv so so that's why I never thought about it. I've submitted your patch internally and can make it accessible in a few days if necessary.

I was also pretty surprised to find that venv does not actually hide the user-specific site package directory, which means any libraries installed in this directory will be leaked into all venvs which are supposed to be sandboxed environments 😮

**Comment by mrahtz** [comment]
Yay, thanks! No worries about making it accessible soon - I discovered the venv workaround too.

> I was also pretty surprised to find that venv does not actually hide this user-specific site package directory, which means any libraries installed in this directory will be leaked into all venvs which are supposed to be sandboxed environments 😮

Hmm, weird - my understanding is that it _should_ do unless the venv is created with `--system-site-packages`. This is how it goes for me:

```
$ python3
>>> import tensorflow
>>> tensorflow.__file__
'/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/__init__.py'
>>> ^D
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ python3
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
```

**Comment by grievejia** [comment]
Hmm, this is how it goes for me:
```
> python -c "import site; print(site.getusersitepackages())"
/Users/grievejia/Library/Python/3.8/lib/python/site-packages

> mkdir venv
> python -m venv venv
> source venv/bin/activate
> python -c "import site; print(site.getusersitepackages())"
/Users/grievejia/Library/Python/3.8/lib/python/site-packages  # I expect this to be empty inside a venv. 
```

**Comment by mrahtz** [comment]
Wow, this is confusing. On macOS, if I `pip install tensorflow` (without sudo) it gets installed to

`/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow`

If I `pip install --user tensorflow` it gets installed to

`/Users/mrahtz/Library/Python/3.6/lib/python/site-packages/tensorflow`

`getusersitepackages()` in a venv reports:

`/Users/mrahtz/Library/Python/3.6/lib/python/site-packages`

But I still can't `import tensorflow`, because that directory isn't actually added to `sys.path` while in a venv. So I guess venvs fiddle with `sys.path` but not with `site.getusersitepackages()`?
