### ISSUE TITLE
Client exited with error code -6

### ISSUE THREAD

**Issue by belm0** [facebook/pyre-check#418]
I followed https://pyre-check.org/docs/getting-started/

```
$ mkdir my_project && cd my_project
$ python3 -m venv ~/.venvs/venv
$ source ~/.venvs/venv/bin/activate
(venv) $ pip install pyre-check
(venv) $ pyre init
ƛ Also initialize watchman in the current directory? [Y/n]
ƛ Created basic `.watchmanconfig` at /.../my_project/.watchmanconfig
ƛ Current directory is being watched by `watchman`.
ƛ Which directory should pyre be initialized in? (Default: `.`):
ƛ Successfully initialized pyre! You can view the configuration at `/.../my_project/.pyre_configuration`.
(venv) $ echo "i: int = 'string'" > test.py
(venv) $ pyre
ƛ Using virtual environment site-packages in search path...
ƛ Client exited with error code -6
```

OS X 10.13.6
```
(venv) $ pip list | grep pyre
pyre-check        0.9.0
pyre-extensions   0.0.21
(venv) $ python --version
Python 3.9.0
(venv) $ watchman --version
4.9.0
```

**Comment by arthaud** [comment]
Hi @belm0, thanks for reaching out.
Could you try running pyre with logging enabled, using `pyre -n`, and send us the output? Thanks.

**Comment by belm0** [comment]
**First, the help output is not clear at all that `-n` enables debug output.**  Otherwise I would have tried that on my own to diagnose the problem.  It would be great to fix that.

```
$ pyre -h
Usage: pyre [OPTIONS] COMMAND [ARGS]...

Options:
  ...
  -n, --noninteractive            Disable interactive logging.
```

**Comment by belm0** [comment]
**Symbol not found: ____chkstk_darwin**

It looks like an issue with older versions of OS X (I have 10.13.8 on my trusty old MacBook).

```
DEBUG dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
DEBUG Removing pid file: `/.../tmp/my_project/.pyre/pid_files/start-83044.pid`
DEBUG   Referenced from: /.../.venvs/venv/bin/pyre.bin (which was built for Mac OS X 10.15)
DEBUG   Expected in: /usr/lib/libSystem.B.dylib
DEBUG
DEBUG dyld: Symbol not found: ____chkstk_darwin
DEBUG   Referenced from: /.../.venvs/venv/bin/pyre.bin (which was built for Mac OS X 10.15)
DEBUG   Expected in: /usr/lib/libSystem.B.dylib
DEBUG
ERROR Client exited with error code -6
```

**Comment by belm0** [comment]
With this OS restriction in the stock pypi distribution I'd be reluctant to take on pyre in our project's tool chain.  Despite having a large number of Python software tools in use, up until now we haven't had a problem with the OS X version of developer computers.

**Comment by arthaud** [comment]
We definitely want to support macOS. What version of macOS are you using? I am using macOS Big Sur version 11.2.1 and had no problem with pyre.

**Comment by arthaud** [comment]
Please open a new issue if this is still a problem. We definitely support macOS users.
