### ISSUE TITLE
clarify option for debug output

### ISSUE THREAD

**Issue by belm0** [facebook/pyre-check#419]
The help output is not clear at all that `-n` enables debug output.

Would you expect something that, on first glance, appears to say "disable logging" to actually enable logging?

```
$ pyre -h
Usage: pyre [OPTIONS] COMMAND [ARGS]...

Options:
  ...
  -n, --noninteractive            Disable interactive logging.
```

suggested:
  * change help text to "Disable interactive logging / enable DEBUG logging."
  * make `-d` an alias for `-n`

raised in #418

**Comment by arthaud** [comment]
This should be an easy fix in `client/pyre.py`, if you want to try contributing. I might do this soon anyway.

**Comment by belm0** [comment]
please go ahead if you have the chance-- thank you

**Comment by arthaud** [comment]
FYI the recommended way to get logs is by using `pyre rage` after a run. I simply forgot to mention this in the other issue.
