### ISSUE TITLE
PEP 647 (TypeGuard)

### ISSUE THREAD

**Issue by JelleZijlstra** [facebook/pyre-check#425]
I'd like to start using https://www.python.org/dev/peps/pep-0647/ in typeshed. Do you have any plans in that direction already?

I can look into adding basic support to unblock typeshed, which would mean simply interpreting `TypeGuard[...]` as an alias for `bool`.

**Comment by pradeep90** [comment]
Thanks for opening an issue with Pyre. We don't have plans in that direction in the near future. Looks like you mainly want to use it Typeshed stubs (i.e., replace `bool` with `TypeGuard[...]` as the return type).

I've added a workaround to recognize `TypeGuard` as a generic bool for the time being. We'll release a new open-source version of Pyre in the next two weeks.

Btw, I'm curious which functions you plan to use `TypeGuard` on. Could you add a brief list to your original PR? :)

**Comment by JelleZijlstra** [comment]
Thanks! I added examples of functions for which TypeGuard could be useful to the typeshed issue.

**Comment by stroxler** [comment]
cc @kbansal I believe you've implemented TypeGuard support, can we close this issue?

**Comment by kbansal** [comment]
Yes, this is now implemented. Closing.
