### ISSUE TITLE
"Undefined name" on using `six`, which is in typeshed

### ISSUE THREAD

**Issue by gnprice** [facebook/pyre-check#43]
Trying to run Pyre on Zulip, I get the following errors (among many others):
```
zthumbor/loaders/helpers.py:64:11 Undefined name [18]: Global name `six` is undefined.
zthumbor/loaders/helpers.py:64:20 Undefined name [18]: Global name `six` is undefined.
zthumbor/loaders/helpers.py:70:11 Undefined name [18]: Global name `six` is undefined.
zthumbor/loaders/helpers.py:70:20 Undefined name [18]: Global name `six` is undefined.
```

This puzzles me because `six` is in typeshed -- which Pyre is supposed to refer to, right? In fact, here's the relevant import line:
```
from six.moves.urllib.parse import urlparse, parse_qs
```
and indeed that module, and those names within it, [are there in typeshed](https://github.com/python/typeshed/blob/master/third_party/3/six/moves/urllib/parse.pyi).

I don't have any good ideas for what's going wrong in this instance. If there isn't an obvious (to you as the Pyre developers) thing that this could be, I can try refining out a minimal repro case.

**Comment by sinancepel** [comment]
@gnprice by default, pyre only pulls in the stdlib stubs from typeshed. You can add the third party directory to your `.pyre_configuration` by adding the line `"search_path": "/path/to/typeshed/third_party". I'll see if we can make the documentation clearer with respect to this.

**Comment by dark** [comment]
The main reason to initially support only stdlib was simplicity. As the project grows, we will start looking into 3rd-party as well.
As a matter of fact, I am working on this feature, so I am going to reopen this issue and self-assign it for clarity.
