### ISSUE TITLE
validate_taint_models() fails for specific cases of incorrect Syntax in .pysa files

### ISSUE THREAD

**Issue by m0mosenpai** [facebook/pyre-check#431]
# Pysa Bug

**Bug description**

Validating taint models fails for specific cases of incorrect Syntax. Since the new Pysa VSCode Plugin relies on `validate_taint_models()` performing correctly, the extension is unable to publish diagnostics and highlight the errors.

**Reproduction steps**

Taking one of the example `.pysa` files provided in `documentation/pysa_tutorial/exercise2` folder,

![image](https://user-images.githubusercontent.com/17424778/119346992-8a95a780-bcb8-11eb-9f3f-b4e318c5f33e.png)

If there is an error in the way `ShellExecution` is spelt or `subprocess` is spelt, an error such as the following is displayed:

![image](https://user-images.githubusercontent.com/17424778/119347273-ed873e80-bcb8-11eb-9972-c034301e3a3a.png)
![image](https://user-images.githubusercontent.com/17424778/119347338-068fef80-bcb9-11eb-9ca0-4f17e258270a.png)

These errors make it possible for the VSCode Extension to take in the line values and publish the diagnostics. However, upon removing one the square brackets or misspelling `def` at the beginning causes:

![image](https://user-images.githubusercontent.com/17424778/119347554-4ce54e80-bcb9-11eb-9e56-18f97abbfeba.png)

**Expected behavior**

Pysa should be able to parse errors like misspelling "def" or misplacing brackets as well. The parsed output should be similar to the ones shown in the beginning - with proper line numbers, path to the file etc. This will help in publishing the errors to VSCode for the extension. Since this only seems to occur for some particular changes, it causes inconsistencies in the extensions's model validation feature where it successfully shows errors in some cases, and crashes/ ignores in cases where this happens.

**Logs**

Output with `--noninteractive` flag enabled

![image](https://user-images.githubusercontent.com/17424778/119347956-d8f77600-bcb9-11eb-93a0-7495791ab8f1.png)
```
2021-05-24 17:59:31,225 [PID 67312] DEBUG Sending `["Query", "validate_taint_models()"]`
2021-05-24 17:59:31,227 [PID 67312] DEBUG Received `["Query",{"error":"(\"PyreParser.Parser.Error(\\\"Could not parse file at $invalid_path:5:13-5:13\\\\n  ef subprocess.getoutput(cmd: TaintSink[ShellExecution]): ...\\\\n              ^\\\")\")"}]`
{"error": "(\"PyreParser.Parser.Error(\\\"Could not parse file at $invalid_path:5:13-5:13\\\\n  ef subprocess.getoutput(cmd: TaintSink[ShellExecution]): ...\\\\n              ^\\\")\")"}
```
**Additional Context**

The development of the Pysa VSCode Extension's model validation feature can be checked here https://github.com/facebook/pyre-check/pull/409 and this issue has been filed after discussions with @gbleaney.

**Comment by arthaud** [comment]
Parse errors should now be reported as any other model verification error :)
