### ISSUE TITLE
Pyre Server crashing instantly

### ISSUE THREAD

**Issue by FedericoV** [facebook/pyre-check#44]
Hi,

I installed the pyre-check package using pip install, and tried starting it in a directory.  The first time I started it worked fine, but after closing vscode the server shut down.  I tried rebooting it it and kept getting this error:

```
 ƛ Server not running at `.`. Starting...
 ƛ Client exited with error code -5:
```

I removed all the init files in the directory, tried doing a new pyre init and keep getting the same error as soon as I try starting the server.

This is on a mac, Python 3.6, with the latest osx and visual studio code insider edition.

**Comment by sinancepel** [comment]
Ugh, that looks like a rogue server refusing to stop. Does `pyre kill --with-fire` help?

**Comment by FedericoV** [comment]
Nope:

```
186590d34d15:FBA_Analytics_Utils vaggi$ pkill -9 pyre
186590d34d15:FBA_Analytics_Utils vaggi$ pyre kill --with-fire
186590d34d15:FBA_Analytics_Utils vaggi$ pyre 
 ƛ Server not running at `.`. Starting...
 ƛ Client exited with error code -5:

```

**Comment by FedericoV** [comment]
I tried doing ps aux and grepping for anything with pyre in the name and cannot find any loose processes/servers.  Anything I should manually be killing?

**Comment by sinancepel** [comment]
No, doesn't look like anything you should be manually killing - the server might just be refusing to start up. Does the simple `pyre check` workflow work for you, or does the binary crash there as well? 

For context, `pyre` is a wrapper script that shells out to `pyre.bin`, a binary that does the bulk of the work.

**Comment by FedericoV** [comment]
`pyre check` also crashes with the same error message.

**Comment by dark** [comment]
@FedericoV Please try with `pyre --debug check`, it will print more informative messages. Specifically, it will print a line stating how the binary is being started, with its full commandline. I would recommend running that process manually.

Could you please provide a gist of both full outputs? Much appreciated.

**Comment by FedericoV** [comment]
Aha - I think the second message is actually helpful:

https://gist.github.com/FedericoV/ba1f630ad5fc0982242584da062ecc59

Not sure how the symbolic link got broken after the first invocation.

**Comment by dark** [comment]
Can you please confirm the version you have installed with `pip list`?
At this point I am puzzled, and worried this is going down the path of OSX playing tricks. Could you please provide the following in a gist?
```
which pyre.bin
otool -l $(which pyre.bin)
```

**Comment by FedericoV** [comment]
The output of the first command is this:

`/Users/vaggi/anaconda3/bin/pyre.bin`

The second command is here:

https://gist.github.com/FedericoV/061044a8ab1788209eb67c7beb326f16

**Comment by dark** [comment]
Hi, sorry for not having further activity on this bug, but I am still not sure how to move forward.
We don't have much expertise about the MacOS userspace and toolchains, so we are learning as we go.

**Comment by mendozao** [comment]
I ran into the same problem as @FedericoV:

```
dyld: Symbol not found: _clock_gettime
  Referenced from: /foo/pyre.bin
  Expected in: /usr/lib/libSystem.B.dylib
```

I'm running Mac 10.11.6.

It seems that Apple introduced `clock_gettime` in Sierra (10.12), and the binary that pyre ships with was pre-compiled on 10.12 or later. Since 10.11 is missing clock_gettime, the executable fails with the runtime link error mentioned above.

My solution was to build pyre-checker from source and then edit my project's .pyre_configuration to point to the binary that was built for my system:

```
{
    "binary": "/path/to/pyre-check/_build/all/main.native",
    "source_directories": [
        "./directory/to/typecheck"
    ],
    "typeshed": "/path/to/typeshed/",
}
```

**Comment by kezabelle** [comment]
Chiming in with additional anecdata: I'm seeing the same `_clock_gettime` issue as above, also on 10.11, using the pre-packaged wheel/binary:
```
> python -V
Python 3.6.2

>  pip -V
pip 18.1 from /Users/<venv>/lib/python3.6/site-packages/pip (python 3.6)

> pip install pyre-check
Collecting pyre-check
  Downloading https://files.pythonhosted.org/packages/.../pyre_check-0.0.20-py3-none-macosx_10_11_x86_64.whl (12.3MB)
Installing collected packages: pyre-check
Successfully installed pyre-check-0.0.20

> pyre --debug --source-directory . check
2019-02-12 14:34:48,116 DEBUG No configuration found at `.pyre_configuration.local`.
2019-02-12 14:34:48,116 DEBUG No configuration found at `.pyre_configuration`.
2019-02-12 14:34:48,117 INFO No binary specified, looking for `pyre.bin` in PATH
2019-02-12 14:34:48,117 INFO Found: `/Users/<venv>/bin/pyre.bin`
2019-02-12 14:34:48,117 INFO No typeshed specified, looking for it
2019-02-12 14:34:48,117 DEBUG Trying with: `/Users/<venv>/lib/python3.6/site-packages/pyre_check/pyre_check/typeshed/`
2019-02-12 14:34:48,118 DEBUG Trying with: `/Users/<venv>/lib/python3.6/site-packages/pyre_check/typeshed/`
2019-02-12 14:34:48,118 DEBUG Trying with: `/Users/<venv>/lib/python3.6/pyre_check/typeshed/`
2019-02-12 14:34:48,118 DEBUG Trying with: `/Users/<venv>/lib/pyre_check/typeshed/`
2019-02-12 14:34:48,118 INFO Found: `/Users/<venv>/lib/pyre_check/typeshed/`
2019-02-12 14:34:48,118 WARNING Setting up a `.pyre_configuration` with `pyre init` may reduce overhead
2019-02-12 14:34:48,119 DEBUG Running `/Users/<venv>/bin/pyre.bin check -debug -project-root /Users/<venv>/<package> -filter-directories . -workers 20 -typeshed /Users/<venv>/lib/pyre_check/typeshed/ /Users/<venv>/<package>`
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/<venv>/bin/pyre.bin
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/<venv>/bin/pyre.bin
  Expected in: /usr/lib/libSystem.B.dylib

2019-02-12 14:34:48,590 ERROR Client exited with error code -5
```

**Comment by sinancepel** [comment]
Does the workaround in this stackoverflow thread help? https://stackoverflow.com/questions/49969800/why-is-pip-installing-pillow-for-os-x-10-12-when-i-have-os-x-10-11-installed/49987984#49987984

**Comment by arthaud** [comment]
Closing this since this is an old issue. Please re-open if the problem is still present.
