### ISSUE TITLE
Pysa Tutorial missing fb-sapp

### ISSUE THREAD

**Issue by jckling** [facebook/pyre-check#444]
In exercise4 I'm told to use `sapp`  but it isn't installed before. So I need to `pip3 install fb-sapp` before I continue the exercise.

The [README.md](https://github.com/facebook/pyre-check/tree/master/documentation/pysa_tutorial/exercise4#static-analysis-post-processor-sapp) file in exercise4 said:
> The Static Analysis Post Processor (SAPP) ships in a separate package from Pysa, which you should have already installed during the initial setup of this tutorial. 

Is it missing? SAPP should be installed in **Setup Instructions**.

**Comment by gbleaney** [comment]
Thanks for the report! This problem occurred because we removed `pyre-check`s dependency on `fb-sapp` a while ago, but forgot to update the tutorial. I've put up #446  to fix this.
