### ISSUE TITLE
not able to recognize 3rd party modules with pyre

### ISSUE THREAD

**Issue by mrajancsr** [facebook/pyre-check#459]
# Pyre Bug

**Bug description**
vscode is not recognizing 3rd party modules.  No issues yesterday, but today suddenly pyre is checking wrong folder

**Reproduction steps**
ran pyre-check on project folder and got the message: "Path does not exist: /Users/raj/Library/Python/3.9/lib/python/site-packages/scipy
ƛ Path does not exist: /Users/raj/Library/Python/3.9/lib/python/site-packages/scipy

I went to pyre configuration and added under search_path: "scipy", and pandas.  I'm confused why pyre is looking at the wrong directory. 

**Expected behavior**
path to my venv: '/Users/raj/.venvs/venv/lib/python3.9/site-packages'

**Logs**
Please include any relevant logs here:

```
Output goes here
```

Please run your reproduction steps followed by `pyre rage > pyre_rage.log`, and upload the file here:

<FILE>
[pyre_rage.log](https://github.com/facebook/pyre-check/files/6920576/pyre_rage.log)

**Additional context**
I'm confused why, when yesterday, i followed the installation steps, after creating virtual env, i didn't have to add any additional configuration for pyre to recognize all my modules.  But now its throwing error.  thanks

**Comment by arthaud** [comment]
Hi @mrajancsr,

Could you send me the `.pyre_configuration` file that results into that error?
I believe `pyre init` should automatically add the `site-packages` directories into the search path.

**Comment by mrajancsr** [comment]
it managed to fix it self.  not sure what happened.  so i will close this for now. thanks
