### ISSUE TITLE
Configuration Options

### ISSUE THREAD

**Issue by compyman** [facebook/pyre-check#46]
My company already has a largely type checked code base and requires all new modules to type-check, 
so we'd like to require `pyre-strict` on all new modules/existing code
There is some legacy code that doesn't type-check and it would be nice to be able to configure that on a per-file basis.

Is there a way to do this currently and if not would this be something appropriate for this project?

**Comment by sinancepel** [comment]
You can add the following line to the top of files you don't want typechecked: # pyre-do-not-check

**Comment by shannonzhu** [comment]
That sounds reasonable - we'd be happy to review a PR for this feature :)
