### ISSUE TITLE
Undefined attribute for top-level numpy functions

### ISSUE THREAD

**Issue by dangirsh** [facebook/pyre-check#47]
Following #27, I added the site-packages folder in my conda env to the "search_path" in my `.pyre-configuration`. This seems to have resolved my package lookup issues, but now pyre is unable to find top-level functions in `numpy`:

"Undefined attribute [16]: Module `numpy` has no attribute `zeros`."

The relevant code looks like:

```
import numpy
...
a = np.zeros(b)
```
(failure points to the last line)

Python 3.6.5 :: Anaconda, Inc.
Ubuntu 16.04.4 LTS
Pyre version 0.0.6

**Comment by sinancepel** [comment]
This probably has to do with the pyre's not resolving the import of zeros in https://github.com/numpy/numpy/blob/master/numpy/__init__.py. In the meantime, a workaround would be to add an empty `numpy.pyi` file to somewhere in your search path.

**Comment by sinancepel** [comment]
@dangirsh closing this issue for now, as it doesn't seem like complete numpy stubs exist for now. Feel free to reopen if they don't solve your problem. Here are some concrete suggestions (pick one):

a) Create an empty `numpy/__init__.pyi` in your project's directory, which will make pyre suppress all numpy errors.

b) It seems that there are some old numpy stubs which I have **not vetted closely** in https://github.com/machinalis/mypy-data/blob/master/numpy-mypy/numpy/__init__.pyi. Adding this stub to your `additional_stubs` path might give you some coverage and name errors.

**Comment by dark** [comment]
For the record, the exact name for the configuration item is `search_path`. :)
