### ISSUE TITLE
Equivalent to mypy's `reveal_type`

### ISSUE THREAD

**Issue by msullivan** [facebook/pyre-check#48]
Does pyre have an equivalent to mypy's `reveal_type(expr)`, which when checked displays the type of `expr`? If not, this is a feature request and if so a documentation one :)

**Comment by dkgi** [comment]
We've started surfacing types via LSPs hover feature but that hasn't found it's way back into the CLI yet. We were definitely talking about implementing this. @dark will have more information.

If you add a `pyre_dump()` call to your function pyre will print some extra information that is usually helpful for debugging.

**Comment by msullivan** [comment]
Looks like https://github.com/facebook/pyre-check/commit/324a06eeb2cb08760dd8472c6e49c4a2f2eea33f implemented this. Thanks!
