### ISSUE TITLE
Not installing on windows

### ISSUE THREAD

**Issue by spapas** [facebook/pyre-check#5]
```
(venv) C:\progr\py3\pyre>pip3 install pyre-check
Collecting pyre-check
  Could not find a version that satisfies the requirement pyre-check (from versions: )
No matching distribution found for pyre-check
```

**Comment by DanielCollins** [comment]
I have this on mac too with either of python3.5 or 3.6

**Comment by dark** [comment]
HI @spapas thanks for the report.
At the moment we are not planning to publish on Pypi official binaries of Pyre for Windows, since we do not have enough bandwidth to support and test that platform.
However, we expect most of the code to work across all platforms, except maybe for filesystem-specific functions. You should be able to get to a good state by compiling the code on your machine.

**Comment by dkgi** [comment]
Actually we rely on parts of Janestreet's `Core` library that are not portable to windows. Right now there's no plan to support windows :(

> I have this on mac too with either of python3.5 or 3.6
@DanielCollins: can you try with `pip3.6 install pyre-check`?

**Comment by spapas** [comment]
Fair enough, thanks !

**Comment by DanielCollins** [comment]
@dkgi https://gist.github.com/DanielCollins/49b16f90f2c7eccb36e08d9bf6f80176

**Comment by DanielCollins** [comment]
others with same (?) problem: https://news.ycombinator.com/item?id=17049415

**Comment by LoganDark** [comment]
If you need to use Pyre, you shouldn't be using Windows. (/s)

**Comment by polsar88** [comment]
No I didn't, but until very now I didn't know it meant `sarcasm`. A little rusty on the latest abbreviations. For that reason alone I suppose I shouldn't need to use `pyre-check` ;)

**Comment by LoganDark** [comment]
Note that Windows has an Ubuntu subsystem and I'm fairly sure Pyre can be compiled on there.

**Comment by polsar88** [comment]
Yes, I'm aware of WSL. Unfortunately, my code needs to run under native Windows. I've been playing with `mypy` today and it seems to work well, so that's what I'm going to use.

**Comment by LoganDark** [comment]
> Unfortunately, my code needs to run under native Windows.
You can run your code under Windows. You can run Pyre under Linux.
