### ISSUE TITLE
Support wildcard paths in source_directories input

### ISSUE THREAD

**Issue by lovemyliwu** [facebook/pyre-check#52]
1. Omit directories
2. wildcard path

**Comment by shannonzhu** [comment]
Hi,
You can omit directories from type checking by adding them to "autogenerated" field of the config file. 
See: https://pyre-check.org/docs/configuration.html

I'll modify this issue to focus on supporting wildcard paths when passing in directories for type checking.

**Comment by lovemyliwu** [comment]
@shannonzhu thank you

**Comment by scottkwalker** [comment]
The field name was updated to "do_not_check" [(link)](https://github.com/facebook/pyre-check/issues/26#issuecomment-410356155). 
Please can the documentation keep track of any deprecated names and tell us what new name to use, as the deprecations are not obvious.

**Comment by hawkins** [comment]
Is "ignore_all_errors" the same as "do_not_check" was last year? Either way, I think wildcards like "**" or just "*" ought to be supported in all the fields, and I'm happy to work on a PR for this if that would be allowed

**Comment by ppwwyyxx** [comment]
Found that `**/__init__.py` is not supported in `ignore_all_errors` field.

**Comment by kbansal** [comment]
1bb29f6 fixed it.
