### ISSUE TITLE
Missing documentation on error 18/21

### ISSUE THREAD

**Issue by a-rmz** [facebook/pyre-check#54]
When running the checking, if an external library is imported and has no type definition, it throws the following error:

```
Undefined name [18]: Global name `...` is undefined.
```

However, the docs only cover errors 14/15 and 16.

It would be useful to know what to do in this case, especially when it's a custom library with no type definitions, or how to configure pyre to silence the error.

**Comment by a-rmz** [comment]
Thank you! Let me know if I can be of any help. 😁

**Comment by dark** [comment]
Adding a brief note to the docs.
