### ISSUE TITLE
Generics not typechecked

### ISSUE THREAD

**Issue by msullivan** [facebook/pyre-check#55]
The following code passes typechecking:
```
# pyre-strict
from typing import TypeVar

T = TypeVar('T')
def coerce(x: T) -> int:
    1 + 'foo'
    return x
```
In general it seems that functions with types involving generics are not typechecked.

For comparison, mypy produces the following errors:
```
poly.py:6: error: Unsupported operand types for + ("int" and "str")
poly.py:7: error: Incompatible return value type (got "T", expected "int")
```

**Comment by dark** [comment]
Yeah, that seems correct. `--debug` produces: `Undefined type [11]: Type `T` is not defined.`

@dkgi, any comment?

**Comment by dkgi** [comment]
@sinancepel was looking into this recently.

**Comment by dkgi** [comment]
Basically what happens here is that we try to figure out whether `T <= int` on the return statement and then give up because we do not store variables in the type order. We haven't yet really put much thought into surfacing these issues :|

**Comment by oscarvarto** [comment]
Any further progress to support generics?

**Comment by mrkmndz** [comment]
Over the course of the past few months we have done a lot of work on correctly supporting type variables.  The given example as well as many many others now work correctly.

Please file new issues for any other type variable issues.
