### ISSUE TITLE
How to detect data flows outside the function ?

### ISSUE THREAD

**Issue by SpikeI** [facebook/pyre-check#550]
I found that I can get a issue when the code in a function, such as :
I want to find data flow from os.chdir to exec:
```
import os

def a():
    b = os.chdir("test")
    exec(b)
```
I can get issue from the code above, but there will be nothing if i scan the code like this:
```
import os

b = os.chdir("test")
exec(b)
```
How can I get this kind of data flow?

**Comment by kbansal** [comment]
@arthaud @gbleaney : I believe this is related to Pysa -- could one you respond to this? Thanks!

**Comment by arthaud** [comment]
Thanks for the report @SpikeI. I'm able to reproduce it. Let me investigate.

**Comment by arthaud** [comment]
I have a fix for it, it should be out soon. It will be in the next release.

**Comment by arthaud** [comment]
Fixed in 4b9640553d07cecf95d3fbae051bca8dd5e9638b

**Comment by SpikeI** [comment]
> Fixed in [4b96405](https://github.com/facebook/pyre-check/commit/4b9640553d07cecf95d3fbae051bca8dd5e9638b)

Should I add any config for this feature?

**Comment by arthaud** [comment]
That will be in the next pip release. Unfortunately, we don't have a schedule for this, but I can try to push one today.
Once it is out you can just run `pip install -U pyre-check`

**Comment by arthaud** [comment]
Alternatively, you could use our nightly package: `pip install pyre-check-nightly`

**Comment by SpikeI** [comment]
> Alternatively, you could use our nightly package: `pip install pyre-check-nightly`

Thanks
