### ISSUE TITLE
How to indicate [this type] or None

### ISSUE THREAD

**Issue by arush** [facebook/pyre-check#56]
It is very common for functions to return a type or None. In typescript you can say `string | null` and the checker will warn you where you forgot to defend against potential null instances. How do you indicate that something may be a type or `None` ?

**Comment by dark** [comment]
In Python, that would be `Optional[str]`, that is a shorthand for `Union[str, None]`.
You can find a full description of these type annotations, and more, at https://docs.python.org/3/library/typing.html
