### ISSUE TITLE
Obtrusive VS Code notifications

### ISSUE THREAD

**Issue by tiwilliam** [facebook/pyre-check#561]
The VS Code language server/client is very obtrusive with three notifications on every type check, sent from `pyre persistent`. I'm not fully sure if I have misconfigured something or if this is by design.

<img width="582" alt="Skärmavbild 2022-01-09 kl  23 51 08" src="https://user-images.githubusercontent.com/190349/148704428-58598cff-c5db-4775-98b8-3e27e1759950.png">

Notifications in question:
https://github.com/facebook/pyre-check/blob/10c375bea52db5d10b71cb5206fac7da9549eb0c/client/commands/persistent.py#L1213-L1218
https://github.com/facebook/pyre-check/blob/10c375bea52db5d10b71cb5206fac7da9549eb0c/client/commands/persistent.py#L1224-L1235

**Comment by tiwilliam** [comment]
Found this in the debug log:
```
2022-01-09 22:45:48,309 [PID 6703] DEBUG Client capabilities: ClientCapabilities(text_document=TextDocumentClientCapabilities(synchronization=TextDocumentSyncClientCapabilities(did_save=True), publish_diagnostics=None), window=None)
```

So my window seems to be set to `None` for some reason.

**Comment by grievejia** [comment]
Yeah I was being lame about those notifications. `window` being not-None is a Meta-internal setup where the messages are shown in status bar instead of as notifications, and it is expected that stock VSCode does not have that. 

For OSS setup, would it be fine if I just don't send those messages to begin with?

**Comment by tiwilliam** [comment]
Ok, make sense. Yeah, skipping those messages are probably the way to go to make this a bit more useful for OSS. Would be OK to keep the connect/disconnect message. Thanks for the quick response.

**Comment by tiwilliam** [comment]
Confirmed working in pyre-check-nightly. Thanks!
