### ISSUE TITLE
pyre missed a function call with missing posargs

### ISSUE THREAD

**Issue by martindemello** [facebook/pyre-check#564]
# Pyre Bug

**Bug description**

A method defined with two required posargs did not raise an error when called with one arg.

**Reproduction steps**

See this pull request: https://github.com/Instagram/LibCST/pull/595/files

The `handle_Index` method is defined with two required posargs, but is called on line 274 with just one. `pyre check`
 did not catch it.

**Comment by yangdanny97** [comment]
Doesn't that PR update the definition to have 1 fewer parameter? I don't see the problem

Closing because the issue is stale, please reopen if this still repros & it affects you

**Comment by martindemello** [comment]
the problem was that before the PR the function had two required posargs, but was being called with just one. pyre did not catch the issue. (not reopening because I haven't tested against the current pyre release; just clarifying what the bug was)

**Comment by yangdanny97** [comment]
Thanks for the clarification
