### ISSUE TITLE
Allow Annotated to wrap Final and ClassVar

### ISSUE THREAD

**Issue by GBeauregard** [facebook/pyre-check#577]
# Pyre Bug

**Bug description**
The behavior of `Annotated` has been changed so that it is allowed at runtime to wrap `ClassVar` and `Final`. This change helps avoid friction with other users of annotations; see https://bugs.python.org/issue46491 for context. This change has [landed in 3.11](https://github.com/python/cpython/commit/e1abffca45b60729c460e3e2ad50c8c1946cfd4e) and has been backported to 3.9, 3.10, and `typing_extensions`. pyre should follow suit in allowing the wrapping in order to allow the friction lifting to happen in practice.

**Reproduction steps**
```python
from typing import Annotated, ClassVar, Final

class C:
    classvar: Annotated[ClassVar[int], (2, 5)] = 4
    const: Annotated[Final[int], "metadata"] = 4
```

**Expected behavior**
The above code should type check.

**Logs**
Please include any relevant logs here:

```console
antest/antest.py:4:4 Incompatible attribute type [8]: Attribute `classvar` declared in class `C` has type `typing.Annotated[ClassVar[int]]` but is used as type `int`.
antest/antest.py:5:4 Incompatible attribute type [8]: Attribute `const` declared in class `C` has type `typing.Annotated[Final[int]]` but is used as type `int`.
antest/antest.py:5:4 Invalid type [31]: Expression `typing.Annotated[Final[int]]` is not a valid type. Final cannot be nested.
```

**Additional context**
Client version: 0.9.10
Binary version: d418f5bb10fdee9648eeea3834c8ca56944bd2ce
Corresponding issue for dataclasses (incl `InitVar`) is at https://bugs.python.org/issue46511
pyright change: https://github.com/microsoft/pyright/commit/8ce7fa6e0ad883fb17407add955273bbfbe506c5
mypy bug: https://github.com/python/mypy/issues/12061
pytype bug: https://github.com/google/pytype/issues/1110

**Comment by stroxler** [comment]
Great, thanks @GBeauregard for flagging this!

**Comment by yangdanny97** [comment]
Seems like this is fixed, the issue no longer repros in the playground

https://pyre-check.org/play?input=from%20typing%20import%20Annotated%2C%20ClassVar%2C%20Final%0A%0Aclass%20C%3A%0A%20%20%20%20classvar%3A%20Annotated%5BClassVar%5Bint%5D%2C%20(2%2C%205)%5D%20%3D%204%0A%20%20%20%20const%3A%20Annotated%5BFinal%5Bint%5D%2C%20%22metadata%22%5D%20%3D%204
