### ISSUE TITLE
Callable with variadic args cannot be called with non-variadic arguments

### ISSUE THREAD

**Issue by mrahtz** [facebook/pyre-check#579]
The following example...

```python3
from typing import Callable
from pyre_extensions import TypeVarTuple, Unpack

Ts = TypeVarTuple('Ts')

def foo(bar: Callable[[Unpack[Ts]], None]) -> None:
    return bar(1)
```

...should type-check correctly; `bar` is a function taking a single variadic positional argument, so passing a single positional argument of `1` should be fine. But Pyre (0.9.10) says:

```
test.py:7:11 Invalid argument [32]:
Argument types `typing_extensions.Literal[1]` are not compatible with expected variadic elements `*test.Ts`.
```

The only things that seems to work are

```python3
def foo(bar: Callable[[Unpack[Ts]], None], baz: tuple[Unpack[Ts]]) -> None:
    return bar(*baz)
```

and

```python3
def foo(bar: Callable[[Unpack[Ts]], None], *baz: Unpack[Ts]) -> None:
    return bar(*baz)
```

I also tried

* `bar(1, 2)`
* `bar((1, 2))`
* `baz: tuple[int, ...]; bar(baz)`
* `baz: tuple[int, ...]; bar(*baz)`
* `baz: tuple[Unpack[Ts]]; bar(baz)`

but these all gave the same error.

(@pradeep90, again, I'm guessing this is your area?)

[pyre_rage.log](https://github.com/facebook/pyre-check/files/8018126/pyre_rage.log)

**Comment by pradeep90** [comment]
> ...should type-check correctly; bar is a function taking a single variadic positional argument, so passing a single positional argument of 1 should be fine. But Pyre (0.9.10) says:

No, it should not type check. Specifically, `Ts` is bound within the scope of the function `foo`. So, `bar` is not a function taking an arbitrary `*Ts`, it is a function taking the specific `*Ts (bound in foo)`. 

We can see that the code above is unsound by calling `foo(expect_str_bool)`. `bar(1)` would be a runtime error:

```
>>> def foo(bar):
...   bar(1)
... 
>>> def expect_str_bool(s, b):
...   s + "hello"
...   
... 
>>> foo(expect_str_bool)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in foo
TypeError: expect_str_bool() missing 1 required positional argument: 'b'
```

The same goes for the other snippets at the bottom.
