### ISSUE TITLE
AnalysisTypeOrder.Cyclic error raised when subclass is named "Any" in file "types.py"

### ISSUE THREAD

**Issue by eastside** [facebook/pyre-check#59]
So this is a really weird issue. This strange error seems to only be raised if...

1. There's a class called `Any`
2. This class is *not* a top level class; i.e., it has to be descended from some other class, but it doesn't matter what the name of its parent is.
3. The class is in a file with the name `types.py`

If any of those things are not true, the error doesn't happen.

Here's a complete test example:

```
vagrant@precise64:~$ python3.6 -m venv pyretest
vagrant@precise64:~$ cd pyretest/
vagrant@precise64:~/pyretest$ . bin/activate
(pyretest) vagrant@precise64:~/pyretest$ pip install pyre-check
... snip ...
Successfully installed pyre-check-0.0.7
(pyretest) vagrant@precise64:~/pyretest$ mkdir test
(pyretest) vagrant@precise64:~/pyretest$ cd test
(pyretest) vagrant@precise64:~/pyretest/test$ touch __init__.py
(pyretest) vagrant@precise64:~/pyretest/test$ vim types.py
(pyretest) vagrant@precise64:~/pyretest/test$ cat types.py
class Foo:
    pass

class Any(Foo):
    pass

(pyretest) vagrant@precise64:~/pyretest/test$ pyre check
 ƛ Order is cyclic:
Edges:

... snip ...

Trace: `_ast.Delete` -> `_ast.stmt` -> `_ast.AST` -> `typing.Any` -> `types.Foo` -> `typing.Any`
Uncaught exception:

  AnalysisTypeOrder.Cyclic

Raised at file "format.ml" (inlined), line 242, characters 35-52
Called from file "format.ml", line 469, characters 8-33
Called from file "format.ml", line 484, characters 6-24
 ƛ Client exited with error code 1:
````

If the name of the file is something other than types.py, no error:

````
(pyretest) vagrant@precise64:~/pyretest/test$ mv types.py foo.py
(pyretest) vagrant@precise64:~/pyretest/test$ pyre check
 ƛ No type errors found
````

If the name of the class is something other than "Any", no error:

```
(pyretest) vagrant@precise64:~/pyretest/test$ mv foo.py types.py
(pyretest) vagrant@precise64:~/pyretest/test$ vim types.py
(pyretest) vagrant@precise64:~/pyretest/test$ cat types.py
class Foo:
    pass

class _Any(Foo):
    pass

(pyretest) vagrant@precise64:~/pyretest/test$ pyre check
 ƛ No type errors found
```

Or if the class `Any` is a top-level class (i.e., not a subclass), no error:

```
(pyretest) vagrant@precise64:~/pyretest/test$ vim types.py
(pyretest) vagrant@precise64:~/pyretest/test$ cat types.py
class Foo:
    pass

class Any:
    pass

(pyretest) vagrant@precise64:~/pyretest/test$ pyre check
 ƛ No type errors found
```

**Comment by eastside** [comment]
Oh, I think I know what the problem *might* be. I'm new to type annotation in Python. I see now that both `types` and `Any` are both attributes of Python's built-in `typing` module. It's probably a bad idea to use those two words, I think?

**Comment by dark** [comment]
Yes, `Any` is used to represent "any type": https://docs.python.org/3/library/typing.html#typing.Any

That will definitely generate a cyclic definition :)

**Comment by gvanrossum** [comment]
It actually looks like the problem may be the name of your file, since
typing.pyi contains `from types import CodeType, FrameType, TracebackType`.
