### ISSUE TITLE
Adding type annotations automatically to the .py files

### ISSUE THREAD

**Issue by aravind-spnp** [facebook/pyre-check#597]
Hi, i use pysa to analyze large codebase (mostly django, flask and python scripts) for potential vulnerabilities, but most of the source codes are not type defined / annotated, hence it results in false negative most of the cases are like as mentioned here (https://pyre-check.org/docs/pysa-false-negatives/#example). 

I also cannot run the source and get the type definition / annotation at runtime using MonkeyType, since i don't have all the dependencies to run the source. Is there any other way to add type definitions / annotations automatically to the source .py files without the need to run the source?.

**Comment by gbleaney** [comment]
If you can't get the code running, take a look at these coverage increasing strategies for some potential alternatives:
https://pyre-check.org/docs/pysa-coverage/

Feel free to re-open if you have any more questions!

**Comment by aravind-spnp** [comment]
``

**Comment by aravind-spnp** [comment]
``` python
from django.http import HttpRequest

class Runner:
    def run(self, command: str) -> None:
        eval(command)

# This flow WILL NOT be found, because Pysa does not know the type of
# 'runner', and thus does not know where the 'run' call dispatches to
def this_is_missed(request: HttpRequest, runner):
    runner.run(request.GET["command"])
```

In the above example is there any other way to annotate the runner instance automatically as ``` runner: Runner ``` so that pysa could recognize the type of 'runner' .

**Comment by gbleaney** [comment]
If you have access to the running code, `MonkeyType` might work. But other than that, no, we have no automated way to perform that annotation. There's simply not enough information for our tools.

**Comment by aravind-spnp** [comment]
okie... Thanks @gbleaney
