### ISSUE TITLE
'unknown' return type from `dateutil.parser.parse`

### ISSUE THREAD

**Issue by PeterJCLaw** [facebook/pyre-check#62]
`python`: 3.5.2, 3.6.5
`pyre`: 0.0.7 (from `pip list`)
`typeshed`: https://github.com/python/typeshed/commit/226f0553fe3df7682b8f808e6b10d392c8b2e553

I would expect the following file to be free from errors:
``` python
# pyre-strict

import datetime
import dateutil.parser

def expect_datetime(dt: datetime.datetime) -> None:
    print(dt)

expect_datetime(dateutil.parser.parse('2018-01-01'))
```
Yet `pyre` reports an issue stemming from the return type of `dateutil.parser.parse` (which is [stubbed in the typeshed](https://github.com/python/typeshed/blob/master/third_party/2and3/dateutil/parser.pyi#L37) and should return a `datetime.datetime`):
```
$ pyre --typeshed /path/to/typeshed/ --search-path /path/to/typeshed/third_party/ check
 ƛ Found 1 type error!
dt.py:9:16 Incompatible parameter type [6]: Expected `datetime.datetime` but got `unknown`.
```

**Comment by dark** [comment]
Thanks for the report - I will investigate the error.

**Comment by dark** [comment]
Sorry for the late reply.
This issue was fixed some releases ago when we updated typeshed to its latest version.
