### ISSUE TITLE
strict mode: Spurious 'Too many arguments' errors

### ISSUE THREAD

**Issue by PeterJCLaw** [facebook/pyre-check#63]
`python`: 3.5.2, 3.6.5
`pyre`: 0.0.7 (from `pip list`)
`typeshed`: https://github.com/python/typeshed/commit/226f0553fe3df7682b8f808e6b10d392c8b2e553

Note: I'm not sure whether this is an expected consequence of `# pyre-strict`, though it doesn't seem to match any of the documented differences from strict mode.

Given:
``` python
# pyre-strict

import pathlib
from typing import NamedTuple

# Also reproduces with class style syntax under Python 3.6
Complex = NamedTuple('Complex', (
    ('real', float),
    ('imaginary', float),
))

pathlib.Path('.')

Complex(4, 2)
```

Then `pyre` emits:
```
$ pyre --typeshed /path/to/typeshed/ check
 ƛ Found 2 type errors!
args.py:12:0 Too many arguments [19]: Call `pathlib.Path.__init__` expects 1 positional argument, 2 were provided.
args.py:14:0 Too many arguments [19]: Call `args.Complex.__init__` expects 1 positional argument, 3 were provided.
```

I'm guessing that this happens because neither `pathlib.Path` nor the generated `NamedTuple` class define an `__init__` method, meaning that `pyre` finds the definition on `object`.

**Comment by dkao1978** [comment]
I'm running into this as well with python 3.6.5, pyre-check 0.0.7, using a stubs file.

```
class ProductQuerySet(models.query.QuerySet):
...

ProductQuerySet(self.model, using=self._db)
```

Stubs file:
```
from typing import Any

class QuerySet:
    def __init__(self, model: Any=None, query: Any=None, using: Any=None, hints: Any=None): ...

    def filter(self, *args: Any, **kwargs: Any) -> self: ...
```

Error message:
```
xcommerce/catalogue/models.py:59:11 Too many arguments [19]: Call `catalogue.models.ProductQuerySet.__init__` expects 1 positional argument, 3 were provided.
```

def filter(...)... in the stubs file is working correctly.

**Comment by dark** [comment]
Thanks for the report!
I will reproduce this issue locally and let you know what I find.

**Comment by dark** [comment]
Turns out these errors reflect two different issues:
* we are not looking at `__new__` now (`pathlib.Path` uses it)
* we are not suppressing arity errors in constructors we cannot resolve.

I will edit this task to track the second issue specifically.

**Comment by sinancepel** [comment]
Pyre is properly handling `__new__` in this case now, and doesn't error for either case.
