### ISSUE TITLE
--local-configuration/-l option no longer available despite documentation covering it's use

### ISSUE THREAD

**Issue by red-avalanche** [facebook/pyre-check#637]
# Pyre Bug

**Bug description**
The [online documentation](https://pyre-check.org/docs/configuration/#local-configurations) for Pyre describes use of the option `--local-configuration` to make use of `.pyre_configuration.local` files. When using that flag `pyre` throws an error that the option no longer exists and `pyre --help` makes no mention of the option.

**Reproduction steps**
Run pyre using the `--local-configuration` option as described in the [documentation](https://pyre-check.org/docs/configuration/#local-configurations).

**Expected behavior**
Either pyre should use the local configuration as described in the configuration documentation or the configuration documentation should be updated to the proper use of local configuration files.

**Logs**
```
$ pyre --local-configuration local/config
Usage: pyre [OPTIONS] COMMAND [ARGS]...
Try 'pyre -h' for help.
```

**Additional context**
This was tested on MacOS and OpenBSD in a Python 3.9 venv where Pyre was installed via pip.

**Comment by stroxler** [comment]
Thanks for the bug report @red-avalanche!

Is local configuration support something that would be useful for your project? If so, I can work on bringing support back (the plumbing is still there because we use it in one of our mega-repos; I think we probably removed it because we thought it wouldn't be useful to external users but we forgot to strip it from the docs).

If not, I'll work on updating the docs

**Comment by red-avalanche** [comment]
> Is local configuration support something that would be useful for your project?

Yes I intended to use it for one of our mono-repos as well. It would be much appreciated if y'all kept that feature!

When using it is there a way to run Pyre against all the .local configs in one command? Will Pyre just automatically search for the .local files or is there any other configuration option to specify them all? I wasn't able to test since the option was removed.

**Comment by stroxler** [comment]
As far as I know there's no way to run against all .pyre_configuration.locals, no. It would be pretty easy to cobble together a script, although for our use case it wouldn't be feasible anyway (that script would probably run for days if it ran in serial - we only kick off CI on subprojects relevant to a specific commit).

For what it's worth, if you enforce namespace consistency across all subprojects of the monorepo, then you may be able to get away with just a single pyre configuration. Pyre can check a pretty big project in a couple of minutes in CI if the machine has many cores, and the incremental check (what you get if you just run `pyre` on the commandline). And you can scale it out more by using the saved state feature.

We use the local configurations in a monorepo that isn't a "proper" monorepo. What I mean by that is that it is a monorepo, but uses [buck](https://buck.build/) to build python tools as archives, and each buck target can potentially have its own dependencies that might differ from other targets.

As a result, it's necessary for us to run many separate Pyre instances for each subproject. A similar thing might happen for you if your monorepo actually consists of many small services that are deployed separately and can have divergent dependencies.

In that case you could use `.pyre_configuration.local` as we do, although you may find you are just as well off using separate `.pyre_configuration` files for each subproject; the benefit of local configs is really just that you can extract shared logic into a central configuration; for example we use this to manage version bumps.

At any rate I'll look into adding back local configuration logic.

**Comment by red-avalanche** [comment]
Using Pyre inside a tool like buck actually makes more sense than having Pyre iterate through all the `.local` files. Thanks for adding the `.local` file functionality back.

**Comment by stroxler** [comment]
Question for you - how big a problem would it be to use separate global configurations in each subproject of your repository?

It should behave exactly like using local configs, except that you may need to duplicate some flags that could be shared repo-wide (in reality that's all a global config + local config does anyway - the local config overlays options on top of the global config).

The context is that we ideally want to get rid of local configs if we can find a way to manage our current monorepo without them - that's not happening soon, but if we expose them to external users then we're stuck with a backward compatibility problem.

**Comment by red-avalanche** [comment]
It wouldn't be a huge problem I guess. Duplicating flags might get annoying since each project in the monorepo would be independent, but that's the only issue I can see.

If that's the route y'all are going it may be helpful to explain how to handle monorepos in the documentation, replacing the .local section.

Jul 8, 2022, 10:25 by ***@***.***:

**Comment by stroxler** [comment]
Sounds good. I've updated the docs.

If having multiple configurations turns into a major pain point let us know and we could revisit this.

Also feel free to reach out if you have any other pyre setup problems or questions!
