### ISSUE TITLE
NoneType object is not callable

### ISSUE THREAD

**Issue by Nirvi1** [facebook/pyre-check#651]
# Pyre Bug

**Bug description**
failure during 
pyre init-pysa 

**Reproduction steps**
I ran steps  according to doc

pip install pyre-check fb-sapp
pyre init-pysa

**Logs**
ƛ Would you like to generate type annotations? [Y/n] Y
Traceback (most recent call last):
  File "/home/nirvi/.local/bin/pyre", line 5, in <module>
    from pyre_check.client.pyre import main
  File "/home/nirvi/.local/lib/python3.8/site-packages/pyre_check/client/pyre.py", line 955, in <module>
    @servers.result_callback()
TypeError: 'NoneType' object is not callable
ƛ Couldn't complete Pysa initialization:
Command '['pyre', 'infer', '-i']' returned non-zero exit status 1.

Could you please help to fix this? thank you!

**Comment by grievejia** [comment]
What's the version of `click` installed on your machine?

**Comment by yangdanny97** [comment]
I'm gonna close this because the issue creator didn't respond
