### ISSUE TITLE
Full path from source point to sink point

### ISSUE THREAD

**Issue by PeteLing** [facebook/pyre-check#676]
# Pysa Feature Request

**Is your feature request related to a problem? Please describe.**
When using pysa analyze, I want to see the full path/trace from source to sink, but now the result only have one point (always the sink). It is inconvenient to figure out where the source from.

**Describe the solution you'd like**
Output all the code segment or position which belongs to the trace from source to sink.

**Describe alternatives you've considered**

**Additional context**

**Comment by r0rshark** [comment]
Hi @PeteLing  thanks for the question. You can see the entire trace (from the source to the sink) after processing the results with [SAPP](https://github.com/facebook/sapp#getting-started) which is the tool we use to interact/visualize the results of our static analysis tools. You can follow [this](https://pyre-check.org/docs/pysa-running/) guide and after having saved the results (last step) you can follow the [SAPP documentation](https://github.com/facebook/sapp#processing-the-results) to load the output (`taint-output.json`) and visualize/interact with the different issues detected :) Feel free to reopen this in case you are still having issue

**Comment by PeteLing** [comment]
@r0rshark thanks, I think I can get what I need in taint-output.json.Thanks a lot~
