### ISSUE TITLE
Playground styling for small screens

### ISSUE THREAD

**Issue by craigfrancis** [facebook/pyre-check#687]
With [https://pyre-check.org/play](https://pyre-check.org/play/), the styling is a bit wrong for small screens (e.g. mobile phones)... which makes it impossible to see the code editor.

It seems to happen because the `<main>` element has a `margin-left` of `300px`.

I wonder if the class is wrong. Rather than using `.main` (or `.main_MeqP` after preprocessing), I suspect it should be `.playgroundMain` (or `.playgroundMain_uARe`  after preprocessing), ref [styles.module.css](https://github.com/facebook/pyre-check/blob/main/documentation/website/src/pages/styles.module.css#L56), then compare [pysa-playground.js](https://github.com/facebook/pyre-check/blob/main/documentation/website/src/pages/pysa-playground.js#L233) and [play.js](https://github.com/facebook/pyre-check/blob/main/documentation/website/src/pages/play.js#L212)

**Comment by yangdanny97** [comment]
Thanks for reporting this. Sorry for the _very_ long delay here, but this has been fixed and will be reflected in the next update for the website!
