### ISSUE TITLE
Option to print current function being checked?

### ISSUE THREAD

**Issue by randolf-scholz** [facebook/pyre-check#688]
I could find any sort of `verbose` flag. How can I figure out which function pyre is stuck on?

![image](https://user-images.githubusercontent.com/39696536/201381293-81f55405-a87a-4708-a209-9f157845588f.png)

**Comment by pradeep90** [comment]
Hello, you can use `pyre -n` for verbose logging. It's a bit undiscoverable right now :|

https://github.com/facebook/pyre-check/blob/07702a6b1a0f7da9aa2781640d76cc91c13481af/client/pyre.py#L203-L208

**Comment by randolf-scholz** [comment]
@pradeep90 Hey, when I use `pyre -n`, I get

![image](https://user-images.githubusercontent.com/39696536/201479029-22a48e99-0919-4bad-8d80-15868ecc70ba.png)

which also doesn't tell me which function it is stuck on.
