### ISSUE TITLE
Links in docs are wrong

### ISSUE THREAD

**Issue by eggplants** [facebook/pyre-check#699]
Change Log link should be absolute.

https://pyre-check.org/play/
![image](https://user-images.githubusercontent.com/42153744/209437119-5b38f87b-7a84-4f04-863b-4bd77798ad15.png)
↓
https://pyre-check.org/play/docs/change-log/
![image](https://user-images.githubusercontent.com/42153744/209420549-58d81efd-6561-44d3-a0eb-1096fd383fa1.png)

**Comment by eggplants** [comment]
https://pyre-check.org/docs/change-log/
![image](https://user-images.githubusercontent.com/42153744/209437328-3ecfbb09-b2cb-460b-aab0-5620e63f0f6b.png)
↓
https://pyre-check.org/docs/change-log/docs/getting-started/
![image](https://user-images.githubusercontent.com/42153744/209437344-ae686027-22f3-4652-8fd1-b959f5d0e846.png)

**Comment by grievejia** [comment]
Closing the task as footer has been removed.
