### ISSUE TITLE
Support PEP 561?

### ISSUE THREAD

**Issue by malmaud** [facebook/pyre-check#70]
It seems like pyre doesn't currently support [PEP 561](https://www.python.org/dev/peps/pep-0561/). In short, when looking for type annotations for imported packages, it should include packages in standard package locations that have a `py.typed` marker file (with some additional complications). mypy currently implements the PEP. 

Thanks!

**Comment by dark** [comment]
Hi @malmaud, that is correct. Pyre does not support PEP 561 yet.
We are planning to implement it sometime in the future though. Stay tuned!

**Comment by malmaud** [comment]
Great, thanks for the quick response.

**Comment by arthaud** [comment]
I believe this is implemented. Let me know if this is not working.
