### ISSUE TITLE
pyre cant find builtins.

### ISSUE THREAD

**Issue by sorenmc** [facebook/pyre-check#706]
Having similar issues to what is discussed [here.](https://github.com/facebook/pyre-check/issues/383)

It looks like pyre is having trouble finding the python builtin standard libs. However it looks like the 3rd party dependencies and my own packages are being found.
I have a monorepo structure of the following format where libs are used as dependencies for other libs, and projects. 
Each lib and project has its own virtualenv created with venv. Each virtualenv as its own installation of pyre installed with poetry.

- libs
   - mylib1
      - .venv
      - mylib1
         - prod 
            - file.py
      - pyproject.toml
      - .pyre_configuration
      - .watchmanconfig
   - mylib2
      - .venv
      - mylib2
         - prod 
            - file.py
      - pyproject.toml
      - .pyre_configuration
      - .watchmanconfig
- projects   
- tools

when i run `pyre` locally i get the following errors

```bash
mylib/prod/file.py:1:0 Undefined import [21]: Could not find a module corresponding to import `pathlib`.
mylib/prod/file.py:2:0 Undefined import [21]: Could not find a module corresponding to import `typing`.
mylib/prod/file.py:24:35 Undefined or invalid type [11]: Annotation `str` is not defined as a type.
...
```

pyre_configuration:
```json
{
  "site_package_search_strategy": "all",
  "binary": "./.venv/bin/pyre.bin",
  "typeshed": "./.venv/lib/python3.8/site-packages/pyre_check/typeshed/",
  "source_directories": [
    {
      "root": ".",
      "subdirectory": "mylib"
    }
  ],
  "search_path": [
    "./.venv/lib/python3.8/site-packages/",
    "../../libs/*"
  ],
  "ignore_all_errors": [
    ".*/.venv/.*"
  ]
}

```

I have tried many different permutations of the pyre file but nothing seems to fix my issue. Can anyone see what i am missing?

**Comment by kinto0** [comment]
Pyre probably can't find typeshed, which houses all of the stdlib type signatures. How it's currently set, pyre will look for typeshed in root/.venv/lib/.../typeshed. Can you verify typeshed is there on your system?

see how others set it up here:
https://github.com/search?q=%22typeshed%22%3A+filename%3A.pyre_configuration&type=code

**Comment by sorenmc** [comment]
I checked that all these were set correctly, it was never able to find them for some reason. I ended up switching to https://github.com/microsoft/pyright as it was easier to integrate.
