### ISSUE TITLE
Inferred no-longer-optional check has weird behaviour in __init__

### ISSUE THREAD

**Issue by mikkelmk** [facebook/pyre-check#711]
# Pyre Bug

**Bug description**

The following code
```python
from typing import Optional


class Foo:
    def __init__(self, bar: Optional[str]):
        self.bar = bar
        print(self.bar)
        if self.bar:
            self.bar.lower()
            self.bar.upper()
```
gives the error
```
src/foo_class.py:10:18 Undefined attribute [16]: `Optional` has no attribute `upper`.
```
Note that there's no error for `self.bar.lower()` on line 9, only `self.bar.upper()` on line 10.
(Same pattern with calls to any other `str`-methods)

- Removing the `print` call on line 7 fixes the issue
- Using the parameter `bar` instead of `self.bar` on line 8-10 fixes the issue
- Moving the body of `__init__` to another method, and calling that from init instead, fixes the issue

**Reproduction steps**
Run `pyre check` on the above example.

**Expected behavior**
Similar behavior for line 9 and 10, regardless of adjacent `print` calls, whether or not it is a property of the class, or placed directly in the body of `__init__` or not.

**Logs**
\-
[pyre_rage.log](https://github.com/facebook/pyre-check/files/10707262/pyre_rage.log)

**Additional context**
\-

**Comment by kinto0** [comment]
you will need to set self.bar to a local variable. we error on line 10 but not 9 since function calls can modify `self`'s state.
