### ISSUE TITLE
Configuration: fail `pyre check` if there are errors

### ISSUE THREAD

**Issue by psukys** [facebook/pyre-check#72]
This is primarily for continuous integration, so that check fails (does not return 0) if there are errors. Adding an configuration value to make it fail in case of errors would solve the issue.

**Comment by dark** [comment]
Hi @psukys, PR #9 introduced this feature by default around one month ago, but we have not tagged a released since then yet.
We will likely push a new release in the next one or two weeks, and I will close this issue then.
Thanks for the report!

**Comment by psukys** [comment]
Hey @dark, thanks for the update, will be looking forward for the new release!

**Comment by dark** [comment]
I have just released `v0.0.8`, that includes PR #9.
