### ISSUE TITLE
Publish the parser/AST to opam? (or, a way to use the machinery in another OCaml program)

### ISSUE THREAD

**Issue by pablo-meier** [facebook/pyre-check#730]
Forgive me if GH Issues is not the place for this, I would normally post to something like a dev mailing list but can't find one.

# Pyre Feature Request

**Is your feature request related to a problem? Please describe.**
I'd like to write some tooling for Python code that _isn't_ type checking or taint analysis (analysis of imports on a large codebase). [Existing](https://pypi.org/project/pydeps/) [tooling](https://github.com/Trim21/snakefood3) in this space tends to freeze up when run in our codebase; I was hoping with OCaml's performance characteristics (as well as improved ergonomics for my personal taste) I could write something to identify loops, problematic modules, etc. Something like the "big black ball" from [this Instagram post](https://developers.facebook.com/blog/post/2022/06/15/python-lazy-imports-with-cinder/#u_0_4p_Ca) 😛 

**Describe the solution you'd like**
Is it possible to publish `pyrelib` to `opam`, so other executables could use it? Alternatively, maybe some docs on how `dune` packages (like [here](https://github.com/facebook/pyre-check/blob/1ecbae3a5d4f8aced366a77571704b75f9bf905a/source/dune.in#L243)) and the install flow could play with `opam` switches in other projects to access the functionality of [parser.mli](https://github.com/facebook/pyre-check/blob/1ecbae3a5d4f8aced366a77571704b75f9bf905a/source/parser/parser.mli#L22-L27)?

This may be more obvious to more seasoned OCaml developers, but I still get a little confused.

**Describe alternatives you've considered**
In the absence of this, I'll timebox some effort to move the `parser` and `ast` directories, find the correct `dune` files and incantations to build them as libraries. If the project looks like it'll complete, write a script to make ☝️ repeatable without literally keeping copies of pyre-check's source in my repo (submodules? git pull from a specific tag + a bunch of filesystem operations?), as well as licensing due diligence.

Since this will almost certainly go over any real timebox, I can use Python's `ast` module and `multiprocessing` and lightly resent my newly-Python project for as long as it lives.

**Additional context**
To be clear, I'm not attached to actually publishing this to opam as the solution. And whatever solution is proposed, I'm happy to do legwork to make it happen. I'm just proposing it so I can use Issues to ask: what is the best way to re-use your parser/ast in a new project?

Thanks, this project is awesome.

**Comment by grievejia** [comment]
If you just want the parser, I'd recommend depending on [`pyre-ast`](https://github.com/grievejia/pyre-ast) (which is what we are relying on today anyway) directly if you are writing OCaml code. Pyre's own ast module has several legacy design issues which prevents me from recommending it for reuses outside of Pyre itself.

**Comment by pablo-meier** [comment]
@grievejia Thanks for the response! That's interesting, so `pyre-check` is using `pyre-ast` now? Is that [this reference to it](https://github.com/facebook/pyre-check/blob/61063dc3de1e90e40d3ede51d29561dbca7ac09e/source/new_parser/dune#L4) under `new_parser`? I'm also curious to know more about 

> several legacy design issues

but absolutely zero pressure to go too deep on it; don't want to create work for you, just being a bit of a PL nerd haha.

Fun fact, I did manage to pull out the legacy parser into this project of mine, with a bit of effort. That said, I'd prefer to rely on an opam-published library, so I'll take a look at `pyre-ast`. Again, thanks 😄

**Comment by grievejia** [comment]
> so pyre-check is using pyre-ast now? Is that this reference to it under new_parser?

Yes both statements are correct.

> I'm also curious to know more about several legacy design issues

Pyre's own AST does some unnecessary lowering which in certain cases would unrecoverably lose information compared to the raw Python AST. There were also conceptually redundant/incorrect attributes stored within the AST but implementation wise they are hard to get rid of.
