### ISSUE TITLE
Detect usage of functions like all() to infer truthiness of Optional[]

### ISSUE THREAD

**Issue by psukys** [facebook/pyre-check#74]
How are `Optional[t]` types handled? I got into trouble, when trying to verify several `re.search` (which are of type `Optional[re.Match[str]]` and am not sure why `all` function is not acceptable to validate (or most likely I'm misunderstanding the validation mechanism).

The following examples compare it (in my bigger case there's just more `re.search`es)

```python3
import re


def do_something(output: str) -> dict:
    something = re.search(r'(a)', output)

    if all([something]):
        return {'something': something.group(1)}
    else:
        return {}
```
outputs: `Undefined attribute [16]: Optional type has no attribute 'group'.`

versus

```python3
import re


def do_something(output: str) -> dict:
    something = re.search(r'(a)', output)

    if something:
        return {'something': something.group(1)}
    else:
        return {}
```
outputs: `No type errors found`

**Comment by dark** [comment]
Hi @psukys, thanks for the report.
Pyre looks at the test inside the `if` clause to infer that, if the test is true or false, the `Optional[T]` contains an actual `T` or `None`. Right now we detect most common cases (like `if something:`), but we don't support calls to special functions like `any()` yet.
@dkgi can comment on the roadmap here.

**Comment by kflu** [comment]
This is very noisy. If pyre isn't sure if an optional type is `None` or actual value, should it just not warn?

**Comment by yangdanny97** [comment]
We don't refine calls to `all()` with array literals containing only variables. This seems like a very specific edge case so it's unlikely we'd support this type of refinement in the future (and I don't think the other major typecheckers support it either).

Feel free to reopen if you disagree with this assessment.
