### ISSUE TITLE
[Suggestion] Search inside Documentation

### ISSUE THREAD

**Issue by anydayeol** [facebook/pyre-check#745]
Hi,

This is a gentle suggestion on your documentation -- Could you add search in the docs?
I find it hard to find out right page from your [docs website](https://pyre-check.org/docs/getting-started/), because it doesn't support search.
So every time I need to search, I use Google or just search in the code base (which is fine, but annoying).
I think Docusaurus has a few options to enable searching [ref](https://docusaurus.io/docs/search).

Thanks a lot!
Dayeol

**Comment by yangdanny97** [comment]
The docs site has a search bar now!
