### ISSUE TITLE
Pysa check fail at step"Run and test pysa output" with error message "Output differs from expected"

### ISSUE THREAD

**Issue by WangGithubUser** [facebook/pyre-check#755]
Follow up #753 
After the PR above, we still get error at Pysa check:`Output differs from expected`
![image](https://github.com/facebook/pyre-check/assets/120731947/834aad51-bcf6-40a4-9a4c-ff9912e66169)
Is this a bug of Pysa?Or our [result.json](https://github.com/facebook/pyre-check/blob/main/stubs/integration_test/result.json) was outdated?

**Comment by r0rshark** [comment]
Hi @WangGithubUser can you share the content of the `results.actual` file and the command you run to generate it? Thanks!

**Comment by WangGithubUser** [comment]
> Hi @WangGithubUser can you share the content of the file and the command you run to generate it? Thanks!`results.actual`

These are generated by CI. You can get them the output of the check [there](https://github.com/facebook/pyre-check/actions/runs/5543138011/jobs/10119206840?pr=753)

**Comment by WangGithubUser** [comment]
The `position_invariant_result.json` equals this [file](https://github.com/facebook/pyre-check/blob/main/stubs/integration_test/result.json)
And the `position_invariant_result.actual` equals [this](https://github.com/facebook/pyre-check/actions/runs/5543138011/jobs/10119206840?pr=753#step:8:714)

**Comment by WangGithubUser** [comment]
@arthaud Could you fix this?

**Comment by WangGithubUser** [comment]
Fixed in 805b01f878e386d83a28d146c8758e4dc704f291, I will close this.
