### ISSUE TITLE
unknown subcommand newcheck

### ISSUE THREAD

**Issue by r-barnes** [facebook/pyre-check#757]
# Pyre Bug

**Bug description**
I run:
```
pip install pyre-check
pyre init
pyre
```
I see:
```
ƛ No watchman binary found. 
To enable pyre incremental, you can install watchman: https://facebook.github.io/watchman/docs/install
ƛ Defaulting to non-incremental check.
ƛ Check command exited with non-zero return code: 1.
```
If I run `pyre rage` the most suspicious line I see is:
```
DEBUG unknown subcommand newcheck
```

**Reproduction steps**
See above.

**Expected behavior**
Pyre performs a check.

**Logs**
See above

Please run your reproduction steps followed by `pyre rage > pyre_rage.log`, and upload the file here:

[Link to log file](https://gist.github.com/r-barnes/b093cbc32a0a8424a3cbfbca4f07aa8e)

**Comment by stroxler** [comment]
Your logs claim that the config wants to use binary version `8ebc243adc0a7e2bcd9823da34216724146c2de2`, but that won't do anything with open-source Pyre. It then says it's falling back to `pyre.bin` from your `PATH`.

My current best guess is that you may have a very old `pyre.bin` sitting on your path. In that shell, what do you get from `which pyre` and what do you get from `which pyre.bin`? Is one of them getting picked up from a different virtualenv than another?
