### ISSUE TITLE
How to resolve relative imports? `from .foo import bar`

### ISSUE THREAD

**Issue by haakenlid** [facebook/pyre-check#76]
I couldn't find any mention of relative imports in the docs.
Pyre gives me a `Undefined import [21]` everywhere I use relative imports. 

    # foo/bar/baz.py
    FooBar = 'foobar'

    # foo/bar/foo.py
    from .baz import FooBar

    # pyre error
    foo/bar/foo.py:1:0 Undefined import [21]: Could not find a module corresponding to import `.baz`.

Python runs the code with no problems, and mypy doesn't complain. How can I make pyre understand the relative import?

**Comment by dark** [comment]
Hi @haakenlid, thanks for the report.
The fix for this bug is going to be included in the upcoming `v0.0.10` release. Stay tuned!

**Comment by dark** [comment]
This fix is now available in the `v0.0.10` release.
