### ISSUE TITLE
Set Custom Log Path Directory Via CLI or Config File

### ISSUE THREAD

**Issue by quantumpacket** [facebook/pyre-check#768]
# Pyre Feature Request

**Is your feature request related to a problem? Please describe.**

When Pyre is ran it creates a log file in the project root under `.pyre/pyre.stderr`. This log file increases in size every time Pyre is ran. Even for a simple package the log file is larger than my entire package codebase. I have to make sure I exclude it from Git, and also delete it if I need to send the zipped project to someone.

**Describe the solution you'd like**

I would like the ability to change the path where this file is created, or have the ability to disable its creation. It really should only be created if some debug flag is provided, as that is when the contents of the file would actually be useful.

**Comment by connernilsen** [comment]
Hey @quantumpacket, thanks for bringing this issue up! I'll bring it up in our next team meeting.

**Comment by connernilsen** [comment]
Hey @quantumpacket, you can change the directory logging is output to with `--dot-pyre-directory` and decrease the verbosity of the logs with `--log-level CRITICAL`. Hope this helps!

**Comment by quantumpacket** [comment]
@connernilsen Thanks! I'll try that out.

Is this undocumented? Because it is not mentioned anywhere in https://pyre-check.org/docs/configuration/ or in `--help` AFAIK.

**Comment by connernilsen** [comment]
It is undocumented, but I'll be adding it soon and seeing why we have it listed as a hidden flag.
