### ISSUE TITLE
Basic usage info: configuration error or doc updates needed?

### ISSUE THREAD

**Issue by bbarker** [facebook/pyre-check#79]
Hi,

New user here so perhaps I missed something important. I've been looking at the pyre docs at https://pyre-check.org/ and they tend to suggest using `pyre init`, but I didn't see this subcommand. I was on version 0.0.8 (here is the [nix build file](https://github.com/NixOS/nixpkgs/blob/17fe19f5bf691af54249cca804055ca217a6f8c3/pkgs/development/tools/pyre/default.nix#L38-L50)) and updated to 0.0.10 locally to check if this was a new feature, but it looks as though the result is the same:

```
$ pyre version
pyre-nixpkgs 0.0.10
0.0.10
$ pyre help
Analyze Python files

  pyre SUBCOMMAND

=== subcommands ===

  check        Runs a full check without a server (default)
  codex        Generates JSON for Codex without a server
  incremental  Shows current errors by asking the server. Starts a daemon server
               in the current directory if it does not exist.
  persistent   Opens a persistent connection to the server (IDE integration)
  query        Queries the server for type order information.
  rage         Reports debugging diagnostics for Pyre to the standard output.
  start        Starts a server in the foreground by default. See help for daemon
               options.
  stop         Stop the server
  watchman     Starts a watchman listener in the current directory. Starts a
               server in the current directory if it does not exist.
  version      print version information
  help         explain a given subcommand (perhaps recursively)


```

Also, when I run `pyre check` from my python module directory, it just seems to spit out a lot of unreadable JSON output. Is this a normal default behavior? Once again, it seems this was not the case in the docs.

Thanks,

**Comment by dark** [comment]
Hi @bbarker, thanks for the report. It looks like the nix build file is re-packaging things incorrectly.

At runtime, Pyre uses a binary (`pyre.bin`) to do all the heavy lifting, and a Python client (`pyre`) to connect to the binary and take care of initialization features and bootstrap. Specifically, `pyre init` is implemented in the client.

The build file you linked is compiling the binary and naming it `pyre` instead, and it is not packaging the Python client at all. This simply won't work, and that build script should be fixed. I am not a NixOS expert, so unfortunately I cannot help with that :/

In the meantime I would suggest to install `pyre` from `pypi`, if that is possible/desired in the distribution.

**Comment by bbarker** [comment]
Thanks @dark , I'll see if I can fix up the build. I'm not very familiar with the OCaml ecosystem (unfortunately!), though it sounds like I won't need to be. I'll close this, but will reply back here if I have non-nix questions (and reply when it is fixed).

**Comment by bbarker** [comment]
@dark From [what I can tell](https://github.com/facebook/pyre-check/blob/master/scripts/build-pypi-package.sh) there isn't a single command to locally install the python bits (the client), but as a starting point, it looks as though I should just need to add typeshed as a dependency in nix.

Note to self: it looks as though [buildPythonPath](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/wrap.sh) in package examples (e.g. development/libraries/geis/default.nix) might be a good starting point for looking at how to make this work.

**Comment by dark** [comment]
That is correct - `build-pypi-package.sh` builds the right source tree directories for Python in the expected format, then it bundles typeshed and calls setup.py to build the package. All steps are interconnected.
