### ISSUE TITLE
Internal crash: Raised in src/string.ml

### ISSUE THREAD

**Issue by hubyrod** [facebook/pyre-check#790]
# Pyre Bug

**Bug description**
I hit the following error. 

```terminal
ƛ Raised at Base__String.index_from_exn_internal in file "src/string.ml", line 83, characters 7-22
ƛ Called from Base__String.lsplit2_exn.lsplit2_exn in file "src/string.ml", line 590, characters 14-54
ƛ Called from Base__String.lsplit2 in file "src/string.ml", line 608, characters 11-33
```

**Reproduction steps**
my `.pyre_configuration` file content: 
```json
{
  "site_package_search_strategy": "all",
  "source_directories": [
    "."
  ]
}
```

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Logs**

[pyre_rage.log](https://github.com/facebook/pyre-check/files/12613909/pyre_rage.log)

**Additional context**
Note that it works with the following configuration: 
```json
{
  "site_package_search_strategy": "pep561",
  "source_directories": [
    "apps",
    "shared"
  ],
  "search_path": [
    "."
  ]
}
```
But it won't find any package I import in the project. 
So i tried and added a path in `search_path` and it fails with the following configuration 
```json
{
  "site_package_search_strategy": "pep561",
  "source_directories": [
    "apps",
    "shared"
  ],
  "search_path": [
    ".", ".venv/lib/python3.11/site-packages"
  ]
}
```

My poetry env:
```poetry
poetry env info

Virtualenv
Python:         3.11.3
Implementation: CPython
Path:           /Users/<my_alias>/dev/project-with-pyre/.venv
Executable:     /Users/<my_alias>/dev/project-with-pyre/.venv/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.11.3
Path:       /Users/<my_alias>/.pyenv/versions/3.11.3
Executable: /Users/<my_alias>/.pyenv/versions/3.11.3/bin/python3.11
```

**Comment by connernilsen** [comment]
Hey @hubyrod, thanks for letting us know about this. I'm not able to get too much from your error logs, so I'm going to try to reproduce it locally. When it fails with the last configuration you gave (`search_path: [".", ".venv/lib/python3.11/site-packages"]`), does it give you the same error?

**Comment by hubyrod** [comment]
hey @connernilsen 
Sorry for the late reply. yes it does give me the same error.

**Comment by connernilsen** [comment]
Try setting your Pyre configuration to this and see if that helps:
```
{
  "site_package_search_strategy": "pep561",
  "source_directories": [
    "apps",
    "shared"
  ],
  "search_path": [
    ".venv/lib/python3.11/site-packages"
  ]
}
```
(so remove the `"."` search path). It's similar to the second configuration, but I'm hoping the difference in search path might be what's going wrong there.

I haven't been able to reproduce this myself on a couple of different machines, so if that's still not working, maybe try installing [pyre-check-nightly](https://pypi.org/project/pyre-check-nightly/) (or building Pyre from source). I just checked and it seems that we haven't updated open source Pyre in a while, so it's possible it is a bug that we fixed a while ago that newer versions won't have.

**Comment by connernilsen** [comment]
I'm working on publishing a new version now. It might take a day or two to get all the permissions needed, so let me know how your attempt works in the meantime.

Also, I'm glad to hear we can help out with your codebase!

**Comment by connernilsen** [comment]
Hey @hubyrod, I've had some team members that were trying to do a release last week, but we've been running into permissions issues. I think they've been sorted out, so they're expecting for the release to go out tomorrow.

As for the module not found issue, are you sourcing your venv after setting the `PYTHONPATH`?

**Comment by connernilsen** [comment]
Okay @hubyrod, I just finished a release! Try that out and see if it helps.

**Comment by hubyrod** [comment]
That's great, and it seems indeed to be solved. Let's close this issue.

**Comment by hubyrod** [comment]
@connernilsen thank you again for your help !

**Comment by connernilsen** [comment]
No problem @hubyrod, glad we were able to fix it!
