### ISSUE TITLE
pyre can't find a local module when running `pyre persistent`

### ISSUE THREAD

**Issue by w0rp** [facebook/pyre-check#82]
I tried the following.

1. Load my virtualenv.
2. pip install pyre-check.
3. Run `pyre init` and hit Enter.

A configuration file like this was generated.

```json
{
  "binary": "/some/dir/ve/bin/pyre.bin",
  "source_directories": [
    "."
  ],
  "typeshed": "/some/dir/ve/lib/pyre_check/typeshed/"
}
```

I ran the language server with `ve/bin/pyre persistent` via ALE, and the first thing I did was open up an example file in my project. It complained about not being able to find a module that's in my project. How do you get it to work?

**Comment by dark** [comment]
Thanks for the report.
Could run the procedure again and provide the output of `pyre rage` in a gist? Thanks.

**Comment by w0rp** [comment]
I'll provide some more information when I return to work.

**Comment by dark** [comment]
Please reopen when more info is available.
