### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by ucdstudent95618** [facebook/pyre-check#83]
Hi pyre-check team,

I want to translate the GitHub page to Spanish, where can I find the files to do it?

Thanks,

Miguel

**Comment by sinancepel** [comment]
Hello Miguel, 

Thanks for offering to contribute; we'd be excited to have Spanish documentation as well :) 

The structure I would suggest would be to translate the `README.md` as `README.es.md` and add a link it in the preamble of `README.md`. 

Once again, thank you!

**Comment by sinancepel** [comment]
#84 is landing.
