### ISSUE TITLE
Pyre cannot narrow literal types

### ISSUE THREAD

**Issue by vthemelis** [facebook/pyre-check#911]
# Pyre Bug

**Bug description**

Pyre cannot reason about narrowing of literal types:
```Python
from typing import Literal, assert_never

def foo(x: Literal["a", "b"]) -> str:
    if x == "a":
        return "a"
    if x == "b":
        return "b"
    else:
        assert_never(x)
```

This should obviously type check (and it does for `pyright`)

See [Pyre playground](https://pyre-check.org/play?input=from%20typing%20import%20Literal%2C%20assert_never%0A%0Adef%20foo(x%3A%20Literal%5B%22a%22%2C%20%22b%22%5D)%20-%3E%20str%3A%0A%20%20%20%20if%20x%20%3D%3D%20%22a%22%3A%0A%20%20%20%20%20%20%20%20return%20%22a%22%0A%20%20%20%20if%20x%20%3D%3D%20%22b%22%3A%0A%20%20%20%20%20%20%20%20return%20%22b%22%0A%20%20%20%20else%3A%0A%20%20%20%20%20%20%20%20assert_never(x)%0A%0A%20%20%20%20%20%20%20%20)

**Comment by yangdanny97** [comment]
Thanks for reporting! This has been fixed in https://github.com/facebook/pyre-check/commit/58b242612f8e0e2f27c8ca40729b011d7e3edd26 and should be available in the next release.
