### ISSUE TITLE
do_not_check configuration doesn't seem to work

### ISSUE THREAD

**Issue by luke14free** [facebook/pyre-check#92]
This configuration doesn't prevent pyre to type check the whole venv folder (which is in `./venv`)

```
{
  "binary": "/Users/xxx/miniconda3/envs/python3/bin/pyre.bin",
  "source_directories": [
    "."
  ],
  "do_not_check":[
    "venv"
  ],
  "typeshed": "/Users/xxx/miniconda3/envs/python3/lib/pyre_check/typeshed/"
}
```

**Comment by dark** [comment]
Thanks for the report.
To confirm, which version of pyre are you using? (I am asking because the code that handles that functionality has changed a bit, quite recently)

**Comment by rpgoldman** [comment]
For me, replacing `["stubs", "autostubs"]` with absolute pathnames:
```
  "do_not_check": ["/Users/rpg/pymc3/stubs", "/Users/rpg/pymc3/autostubs"],
```
seems to do the trick.  No idea why this would make a difference.  It's also not clear what pyre wants here from the docs (which haven't been updated to the new field name): absolute pathname? relative pathname? glob pattern (absolute or relative)? regexp (absolute or relative)?
Thanks!

**Comment by rpgoldman** [comment]
Sorry, previous report was wrong.  That replacement means that pyre correctly did not check the "stubs" directory, but it *still* tried to parse the "autostubs" directory.  So, really, no idea what's wrong.

**Comment by luke14free** [comment]
> Thanks for the report.
> To confirm, which version of pyre are you using? (I am asking because the code that handles that functionality has changed a bit, quite recently)

pyre version 0.0.10

**Comment by rpgoldman** [comment]
I'm using 0.0.10, also.

**Comment by rpgoldman** [comment]
Awesome!  Any idea when this will be available?

**Comment by dark** [comment]
We don't have a timeline yet, but it shouldn't take long.
Soon (TM) :)

**Comment by dark** [comment]
`0.0.14` has just been released with this fix.
