### ISSUE TITLE
Model for list.append not working in version 0.9.23

### ISSUE THREAD

**Issue by draftyfrog** [facebook/pyre-check#940]
# Pysa Bug
**Pre-submission checklist**
[x] I've checked the list of [common issues](https://pyre-check.org/docs/pysa-quickstart/#common-issues) and mine does not appear

**Bug description**
I have a model to trace taint along lists, just as described in [#163 Tainted lists](https://github.com/facebook/pyre-check/issues/163#issuecomment-489336873).

```
def list.append(self, data: TaintInTaintOut[Updates[self]]): ...
```

This worked up until including pyre-check Version: 0.9.22. But now with version 0.9.23 I get the following error message:
```
general.pysa:2:0 Model signature parameters for `list.append` do not match implementation `(list[_T], _T) -> None`. Reason: unexpected named parameter: `self`.
```

What can I do to make this work again?

**Comment by arthaud** [comment]
Hi @draftyfrog, thanks for reaching out.

If you look at typeshed, this is how `list.append` is defined:
https://github.com/facebook/pyre-check/blob/d87b2608d2b7d31da9f971a027618fe0de472875/stubs/typeshed/typeshed/stdlib/builtins.pyi#L1030

The additional `/` means that parameters up until that point are unnamed, i.e `x.append(object=1)` will not work.
You need to make the taint stub match the signature:
```
def list.append(self, data: TaintInTaintOut[Updates[self]], /): ...
```

Note that by default, pysa should include the `stubs/taint` directory, which already includes that model (in a more precise version):
https://github.com/facebook/pyre-check/blob/d87b2608d2b7d31da9f971a027618fe0de472875/stubs/taint/common/collection_propagation.pysa#L131
