### ISSUE TITLE
Discussion forum?

### ISSUE THREAD

**Issue by rpgoldman** [facebook/pyre-check#99]
Sorry to add noise to the issues, but is there a place where users can discuss pyre, ask questions (like "I'm not sure if this is a bug?"), etc.? If so, would you mind adding it to `pyre-check.org`?

**Comment by dark** [comment]
Thanks for the suggestion.
We're planning to use the "Issues" feature itself for such discussions for now. We might reconsider that if/when the volume of requests will grow over time.

**Comment by rpgoldman** [comment]
OK, I'm asking because I'm having what look like trivial problems.  For example, with pyre version 0.0.10, the `do_not_check` option in `.pyre_configuration` does not seem to work, and I don't know how to debug that.  It's quite possible that my file is somehow incorrect, but I don't see any parsing errors for it, I just see processing of directories that should be skipped. Is there some way to infer why this is happening?  Is there any chance that pyre has some specific rules about how it interprets that field that I could be missing?
Here's what I have:
```
{
  "binary": "/Users/rpg/Library/Python/3.7/bin/pyre.bin",
  "source_directories": [
    "."
  ],
  "do_not_check": ["stubs", "autostubs"],
  "typeshed": "/Users/rpg/Library/Python/3.7/lib/pyre_check/typeshed/"
}
```
and some files in `stubs` are being checked, because I'm seeing parse errors from them.

**Comment by dark** [comment]
I suspect this is the same issue as #92. We haven't got a chance to debug it yet, though.

**Comment by dark** [comment]
We will keep the discussion going in #92 then.
